
# This file is automatically generated, you probably don't want to edit this

.jmvrefs <- list(
    `ggplots`=list(
        `type`="software", 
        `author`="Larmarange, J.", 
        `year`=2025, 
        `title`="ggstats: Extension to 'ggplot2' for Plotting Stats", 
        `publisher`="[R package]. Retrieved from https://cran.r-project.org/package=ggstats", 
        `url`="https://cran.r-project.org/package=ggstats"), 
    `qqplotr`=list(
        `type`="software", 
        `author`="Almeida, A., Loy, A., Hofmann, H.", 
        `year`=2023, 
        `title`="qqplotr: Quantile-Quantile Plot Extensions for 'ggplot2'", 
        `publisher`="[R package]. Retrieved from https://CRAN.R-project.org/package=qqplotr", 
        `url`="https://CRAN.R-project.org/package=qqplotr"), 
    `factominer`=list(
        `type`="software", 
        `author`="Husson, F., Josse, J., Le, S., Mazet, J.", 
        `year`=2025, 
        `title`="FactoMineR: Multivariate Exploratory Data Analysis and Data Mining", 
        `publisher`="[R package]. Retrieved from https://cran.r-project.org/package=FactoMineR", 
        `url`="https://cran.r-project.org/package=FactoMineR"), 
    `psych`=list(
        `type`="software", 
        `author`="Revelle, W.", 
        `year`=2025, 
        `title`="psych: Procedures for Psychological, Psychometric, and Personality Research", 
        `publisher`="[R package]. Retrieved from https://cran.r-project.org/package=psych", 
        `url`="https://cran.r-project.org/package=psych"), 
    `greenacre`=list(
        `type`="book", 
        `author`="Greenacre, M.", 
        `year`=2010, 
        `title`="Biplots in Practice", 
        `publisher`="Fundaci\u00F3n BBVA. Retrieved from https://www.fbbva.es/en/publicaciones/biplots-in-practice-7/", 
        `url`="https://www.fbbva.es/en/publicaciones/biplots-in-practice-7/"), 
    `gpa`=list(
        `type`="software", 
        `author`="Bernaards, C., Gilbert, P., Jennrich, R.", 
        `year`=2025, 
        `title`="GPArotation: Gradient Projection Factor Rotation", 
        `publisher`="[R package]. Retrieved from https://cran.r-project.org/package=GPArotation", 
        `url`="https://cran.r-project.org/package=GPArotation"))
