
# This file is automatically generated, you probably don't want to edit this

barchartOptions <- if (requireNamespace("jmvcore", quietly=TRUE)) R6::R6Class(
    "barchartOptions",
    inherit = jmvcore::Options,
    public = list(
        initialize = function(
            yVar = NULL,
            xVar = NULL,
            group = NULL,
            facet = NULL,
            yaxis = "mean",
            order = "none",
            barType = "dodge2",
            horizontal = FALSE,
            ignoreNA = TRUE,
            reverseStack = FALSE,
            showLabels = TRUE,
            decimalPrecision = 1,
            labelTextSize = 12,
            errorBars = "none",
            ciLevel = 95,
            bootstrap = FALSE,
            errorBarWidth = 0.2,
            errorBarLineSize = 0.5,
            singleColor = TRUE,
            colorNo = 1,
            colorPalette = "jmv",
            borderColor = "none",
            textColor = "auto",
            facetBy = "column",
            facetNumber = 1,
            titleText = NULL,
            titleFontFace = "bold",
            titleFontSize = "14",
            titleAlign = "0.5",
            subtitleText = NULL,
            subtitleFontFace = "plain",
            subtitleFontSize = "12",
            subtitleAlign = "0.5",
            captionText = NULL,
            captionFontFace = "italic",
            captionFontSize = "10",
            captionAlign = "1",
            legendText = NULL,
            legendFontSize = "14",
            legendPosition = "right",
            xAxisText = NULL,
            xAxisFontSize = "16",
            xAxisPosition = "0.5",
            yAxisText = NULL,
            yAxisFontSize = "16",
            yAxisPosition = "0.5",
            yAxisLabelFontSize = 12,
            yAxisLabelRotation = 0,
            yAxisRangeType = "auto",
            yAxisRangeMin = 0,
            yAxisRangeMax = 10,
            xAxisLabelFontSize = 12,
            xAxisLabelRotation = 0,
            xAxisRangeType = "auto",
            xAxisRangeMin = 0,
            xAxisRangeMax = 10,
            xTicks = 0,
            yTicks = 0, ...) {

            super$initialize(
                package="vijPlots",
                name="barchart",
                requiresData=TRUE,
                ...)

            private$..yVar <- jmvcore::OptionVariable$new(
                "yVar",
                yVar,
                suggested=list(
                    "continuous"),
                permitted=list(
                    "numeric"))
            private$..xVar <- jmvcore::OptionVariable$new(
                "xVar",
                xVar,
                suggested=list(
                    "nominal",
                    "ordinal"),
                permitted=list(
                    "factor"))
            private$..group <- jmvcore::OptionVariable$new(
                "group",
                group,
                suggested=list(
                    "nominal",
                    "ordinal"),
                permitted=list(
                    "factor"))
            private$..facet <- jmvcore::OptionVariable$new(
                "facet",
                facet,
                suggested=list(
                    "nominal",
                    "ordinal"),
                permitted=list(
                    "factor"))
            private$..yaxis <- jmvcore::OptionList$new(
                "yaxis",
                yaxis,
                options=list(
                    "mean",
                    "median",
                    "max",
                    "min",
                    "sum"),
                default="mean")
            private$..order <- jmvcore::OptionList$new(
                "order",
                order,
                options=list(
                    "decreasing",
                    "increasing",
                    "none"),
                default="none")
            private$..barType <- jmvcore::OptionList$new(
                "barType",
                barType,
                options=list(
                    "dodge2",
                    "dodge",
                    "stack"),
                default="dodge2")
            private$..horizontal <- jmvcore::OptionBool$new(
                "horizontal",
                horizontal,
                default=FALSE)
            private$..ignoreNA <- jmvcore::OptionBool$new(
                "ignoreNA",
                ignoreNA,
                default=TRUE)
            private$..reverseStack <- jmvcore::OptionBool$new(
                "reverseStack",
                reverseStack,
                default=FALSE)
            private$..showLabels <- jmvcore::OptionBool$new(
                "showLabels",
                showLabels,
                default=TRUE)
            private$..decimalPrecision <- jmvcore::OptionInteger$new(
                "decimalPrecision",
                decimalPrecision,
                min=0,
                max=99,
                default=1)
            private$..labelTextSize <- jmvcore::OptionInteger$new(
                "labelTextSize",
                labelTextSize,
                min=6,
                max=18,
                default=12)
            private$..errorBars <- jmvcore::OptionList$new(
                "errorBars",
                errorBars,
                options=list(
                    "none",
                    "sd",
                    "se",
                    "ci"),
                default="none")
            private$..ciLevel <- jmvcore::OptionNumber$new(
                "ciLevel",
                ciLevel,
                min=0,
                max=100,
                default=95)
            private$..bootstrap <- jmvcore::OptionBool$new(
                "bootstrap",
                bootstrap,
                default=FALSE)
            private$..errorBarWidth <- jmvcore::OptionNumber$new(
                "errorBarWidth",
                errorBarWidth,
                min=0,
                max=1,
                default=0.2)
            private$..errorBarLineSize <- jmvcore::OptionNumber$new(
                "errorBarLineSize",
                errorBarLineSize,
                min=0,
                max=5,
                default=0.5)
            private$..singleColor <- jmvcore::OptionBool$new(
                "singleColor",
                singleColor,
                default=TRUE)
            private$..colorNo <- jmvcore::OptionInteger$new(
                "colorNo",
                colorNo,
                min=1,
                max=255,
                default=1)
            private$..colorPalette <- jmvcore::OptionList$new(
                "colorPalette",
                colorPalette,
                options=list(
                    "jmv",
                    "Set1",
                    "Set2",
                    "Set3",
                    "Pastel1",
                    "Pastel2",
                    "Accent",
                    "Paired",
                    "Dark2",
                    "Spectral",
                    "RdYlGn",
                    "RdYlBu",
                    "RdGy",
                    "RdBu",
                    "PuOr",
                    "PRGn",
                    "PiYG",
                    "BrBG",
                    "Blues",
                    "Greens",
                    "Greys",
                    "Oranges",
                    "Purples",
                    "Reds",
                    "BuGn",
                    "BuPu",
                    "GnBu",
                    "OrRd",
                    "PuBu",
                    "PuBuGn",
                    "PuRd",
                    "RdPu",
                    "YlGn",
                    "YlGnBu",
                    "YlOrBr",
                    "YlOrRd",
                    "viridis::viridis",
                    "viridis::magma",
                    "viridis::inferno",
                    "viridis::plasma",
                    "viridis::turbo",
                    "dichromat::Categorical.12",
                    "tidy::friendly",
                    "tidy::seaside",
                    "tidy::apple",
                    "tidy::ibm",
                    "tidy::candy",
                    "tidy::alger",
                    "tidy::rainbow",
                    "tidy::metro",
                    "custom::lemovice"),
                default="jmv")
            private$..borderColor <- jmvcore::OptionList$new(
                "borderColor",
                borderColor,
                options=list(
                    "none",
                    "black",
                    "white",
                    "gray"),
                default="none")
            private$..textColor <- jmvcore::OptionList$new(
                "textColor",
                textColor,
                options=list(
                    "black",
                    "white",
                    "red",
                    "auto"),
                default="auto")
            private$..facetBy <- jmvcore::OptionList$new(
                "facetBy",
                facetBy,
                options=list(
                    "row",
                    "column"),
                default="column")
            private$..facetNumber <- jmvcore::OptionInteger$new(
                "facetNumber",
                facetNumber,
                min=1,
                max=10,
                default=1)
            private$..titleText <- jmvcore::OptionString$new(
                "titleText",
                titleText)
            private$..titleFontFace <- jmvcore::OptionList$new(
                "titleFontFace",
                titleFontFace,
                options=list(
                    "plain",
                    "bold",
                    "italic",
                    "bold.italic"),
                default="bold")
            private$..titleFontSize <- jmvcore::OptionList$new(
                "titleFontSize",
                titleFontSize,
                options=list(
                    "12",
                    "14",
                    "16",
                    "18",
                    "20",
                    "22",
                    "24"),
                default="14")
            private$..titleAlign <- jmvcore::OptionList$new(
                "titleAlign",
                titleAlign,
                options=list(
                    "0",
                    "0.5",
                    "1"),
                default="0.5")
            private$..subtitleText <- jmvcore::OptionString$new(
                "subtitleText",
                subtitleText)
            private$..subtitleFontFace <- jmvcore::OptionList$new(
                "subtitleFontFace",
                subtitleFontFace,
                options=list(
                    "plain",
                    "bold",
                    "italic",
                    "bold.italic"),
                default="plain")
            private$..subtitleFontSize <- jmvcore::OptionList$new(
                "subtitleFontSize",
                subtitleFontSize,
                options=list(
                    "10",
                    "12",
                    "14",
                    "16",
                    "18",
                    "20",
                    "22"),
                default="12")
            private$..subtitleAlign <- jmvcore::OptionList$new(
                "subtitleAlign",
                subtitleAlign,
                options=list(
                    "0",
                    "0.5",
                    "1"),
                default="0.5")
            private$..captionText <- jmvcore::OptionString$new(
                "captionText",
                captionText)
            private$..captionFontFace <- jmvcore::OptionList$new(
                "captionFontFace",
                captionFontFace,
                options=list(
                    "plain",
                    "bold",
                    "italic",
                    "bold.italic"),
                default="italic")
            private$..captionFontSize <- jmvcore::OptionList$new(
                "captionFontSize",
                captionFontSize,
                options=list(
                    "8",
                    "10",
                    "12",
                    "14",
                    "16",
                    "18",
                    "20"),
                default="10")
            private$..captionAlign <- jmvcore::OptionList$new(
                "captionAlign",
                captionAlign,
                options=list(
                    "0",
                    "0.5",
                    "1"),
                default="1")
            private$..legendText <- jmvcore::OptionString$new(
                "legendText",
                legendText)
            private$..legendFontSize <- jmvcore::OptionList$new(
                "legendFontSize",
                legendFontSize,
                options=list(
                    "10",
                    "12",
                    "14",
                    "16",
                    "18",
                    "20"),
                default="14")
            private$..legendPosition <- jmvcore::OptionList$new(
                "legendPosition",
                legendPosition,
                options=list(
                    "right",
                    "bottom",
                    "left",
                    "top"),
                default="right")
            private$..xAxisText <- jmvcore::OptionString$new(
                "xAxisText",
                xAxisText)
            private$..xAxisFontSize <- jmvcore::OptionList$new(
                "xAxisFontSize",
                xAxisFontSize,
                options=list(
                    "10",
                    "12",
                    "14",
                    "16",
                    "18",
                    "20"),
                default="16")
            private$..xAxisPosition <- jmvcore::OptionList$new(
                "xAxisPosition",
                xAxisPosition,
                options=list(
                    "0",
                    "0.5",
                    "1"),
                default="0.5")
            private$..yAxisText <- jmvcore::OptionString$new(
                "yAxisText",
                yAxisText)
            private$..yAxisFontSize <- jmvcore::OptionList$new(
                "yAxisFontSize",
                yAxisFontSize,
                options=list(
                    "10",
                    "12",
                    "14",
                    "16",
                    "18",
                    "20"),
                default="16")
            private$..yAxisPosition <- jmvcore::OptionList$new(
                "yAxisPosition",
                yAxisPosition,
                options=list(
                    "1",
                    "0.5",
                    "0"),
                default="0.5")
            private$..yAxisLabelFontSize <- jmvcore::OptionNumber$new(
                "yAxisLabelFontSize",
                yAxisLabelFontSize,
                default=12)
            private$..yAxisLabelRotation <- jmvcore::OptionNumber$new(
                "yAxisLabelRotation",
                yAxisLabelRotation,
                default=0,
                min=0,
                max=360)
            private$..yAxisRangeType <- jmvcore::OptionList$new(
                "yAxisRangeType",
                yAxisRangeType,
                options=list(
                    "auto",
                    "manual"),
                default="auto")
            private$..yAxisRangeMin <- jmvcore::OptionNumber$new(
                "yAxisRangeMin",
                yAxisRangeMin,
                default=0)
            private$..yAxisRangeMax <- jmvcore::OptionNumber$new(
                "yAxisRangeMax",
                yAxisRangeMax,
                default=10)
            private$..xAxisLabelFontSize <- jmvcore::OptionNumber$new(
                "xAxisLabelFontSize",
                xAxisLabelFontSize,
                default=12)
            private$..xAxisLabelRotation <- jmvcore::OptionNumber$new(
                "xAxisLabelRotation",
                xAxisLabelRotation,
                default=0,
                min=0,
                max=360)
            private$..xAxisRangeType <- jmvcore::OptionList$new(
                "xAxisRangeType",
                xAxisRangeType,
                options=list(
                    "auto",
                    "manual"),
                default="auto")
            private$..xAxisRangeMin <- jmvcore::OptionNumber$new(
                "xAxisRangeMin",
                xAxisRangeMin,
                default=0)
            private$..xAxisRangeMax <- jmvcore::OptionNumber$new(
                "xAxisRangeMax",
                xAxisRangeMax,
                default=10)
            private$..xTicks <- jmvcore::OptionInteger$new(
                "xTicks",
                xTicks,
                default=0,
                min=0,
                max=99)
            private$..yTicks <- jmvcore::OptionInteger$new(
                "yTicks",
                yTicks,
                default=0,
                min=0,
                max=99)

            self$.addOption(private$..yVar)
            self$.addOption(private$..xVar)
            self$.addOption(private$..group)
            self$.addOption(private$..facet)
            self$.addOption(private$..yaxis)
            self$.addOption(private$..order)
            self$.addOption(private$..barType)
            self$.addOption(private$..horizontal)
            self$.addOption(private$..ignoreNA)
            self$.addOption(private$..reverseStack)
            self$.addOption(private$..showLabels)
            self$.addOption(private$..decimalPrecision)
            self$.addOption(private$..labelTextSize)
            self$.addOption(private$..errorBars)
            self$.addOption(private$..ciLevel)
            self$.addOption(private$..bootstrap)
            self$.addOption(private$..errorBarWidth)
            self$.addOption(private$..errorBarLineSize)
            self$.addOption(private$..singleColor)
            self$.addOption(private$..colorNo)
            self$.addOption(private$..colorPalette)
            self$.addOption(private$..borderColor)
            self$.addOption(private$..textColor)
            self$.addOption(private$..facetBy)
            self$.addOption(private$..facetNumber)
            self$.addOption(private$..titleText)
            self$.addOption(private$..titleFontFace)
            self$.addOption(private$..titleFontSize)
            self$.addOption(private$..titleAlign)
            self$.addOption(private$..subtitleText)
            self$.addOption(private$..subtitleFontFace)
            self$.addOption(private$..subtitleFontSize)
            self$.addOption(private$..subtitleAlign)
            self$.addOption(private$..captionText)
            self$.addOption(private$..captionFontFace)
            self$.addOption(private$..captionFontSize)
            self$.addOption(private$..captionAlign)
            self$.addOption(private$..legendText)
            self$.addOption(private$..legendFontSize)
            self$.addOption(private$..legendPosition)
            self$.addOption(private$..xAxisText)
            self$.addOption(private$..xAxisFontSize)
            self$.addOption(private$..xAxisPosition)
            self$.addOption(private$..yAxisText)
            self$.addOption(private$..yAxisFontSize)
            self$.addOption(private$..yAxisPosition)
            self$.addOption(private$..yAxisLabelFontSize)
            self$.addOption(private$..yAxisLabelRotation)
            self$.addOption(private$..yAxisRangeType)
            self$.addOption(private$..yAxisRangeMin)
            self$.addOption(private$..yAxisRangeMax)
            self$.addOption(private$..xAxisLabelFontSize)
            self$.addOption(private$..xAxisLabelRotation)
            self$.addOption(private$..xAxisRangeType)
            self$.addOption(private$..xAxisRangeMin)
            self$.addOption(private$..xAxisRangeMax)
            self$.addOption(private$..xTicks)
            self$.addOption(private$..yTicks)
        }),
    active = list(
        yVar = function() private$..yVar$value,
        xVar = function() private$..xVar$value,
        group = function() private$..group$value,
        facet = function() private$..facet$value,
        yaxis = function() private$..yaxis$value,
        order = function() private$..order$value,
        barType = function() private$..barType$value,
        horizontal = function() private$..horizontal$value,
        ignoreNA = function() private$..ignoreNA$value,
        reverseStack = function() private$..reverseStack$value,
        showLabels = function() private$..showLabels$value,
        decimalPrecision = function() private$..decimalPrecision$value,
        labelTextSize = function() private$..labelTextSize$value,
        errorBars = function() private$..errorBars$value,
        ciLevel = function() private$..ciLevel$value,
        bootstrap = function() private$..bootstrap$value,
        errorBarWidth = function() private$..errorBarWidth$value,
        errorBarLineSize = function() private$..errorBarLineSize$value,
        singleColor = function() private$..singleColor$value,
        colorNo = function() private$..colorNo$value,
        colorPalette = function() private$..colorPalette$value,
        borderColor = function() private$..borderColor$value,
        textColor = function() private$..textColor$value,
        facetBy = function() private$..facetBy$value,
        facetNumber = function() private$..facetNumber$value,
        titleText = function() private$..titleText$value,
        titleFontFace = function() private$..titleFontFace$value,
        titleFontSize = function() private$..titleFontSize$value,
        titleAlign = function() private$..titleAlign$value,
        subtitleText = function() private$..subtitleText$value,
        subtitleFontFace = function() private$..subtitleFontFace$value,
        subtitleFontSize = function() private$..subtitleFontSize$value,
        subtitleAlign = function() private$..subtitleAlign$value,
        captionText = function() private$..captionText$value,
        captionFontFace = function() private$..captionFontFace$value,
        captionFontSize = function() private$..captionFontSize$value,
        captionAlign = function() private$..captionAlign$value,
        legendText = function() private$..legendText$value,
        legendFontSize = function() private$..legendFontSize$value,
        legendPosition = function() private$..legendPosition$value,
        xAxisText = function() private$..xAxisText$value,
        xAxisFontSize = function() private$..xAxisFontSize$value,
        xAxisPosition = function() private$..xAxisPosition$value,
        yAxisText = function() private$..yAxisText$value,
        yAxisFontSize = function() private$..yAxisFontSize$value,
        yAxisPosition = function() private$..yAxisPosition$value,
        yAxisLabelFontSize = function() private$..yAxisLabelFontSize$value,
        yAxisLabelRotation = function() private$..yAxisLabelRotation$value,
        yAxisRangeType = function() private$..yAxisRangeType$value,
        yAxisRangeMin = function() private$..yAxisRangeMin$value,
        yAxisRangeMax = function() private$..yAxisRangeMax$value,
        xAxisLabelFontSize = function() private$..xAxisLabelFontSize$value,
        xAxisLabelRotation = function() private$..xAxisLabelRotation$value,
        xAxisRangeType = function() private$..xAxisRangeType$value,
        xAxisRangeMin = function() private$..xAxisRangeMin$value,
        xAxisRangeMax = function() private$..xAxisRangeMax$value,
        xTicks = function() private$..xTicks$value,
        yTicks = function() private$..yTicks$value),
    private = list(
        ..yVar = NA,
        ..xVar = NA,
        ..group = NA,
        ..facet = NA,
        ..yaxis = NA,
        ..order = NA,
        ..barType = NA,
        ..horizontal = NA,
        ..ignoreNA = NA,
        ..reverseStack = NA,
        ..showLabels = NA,
        ..decimalPrecision = NA,
        ..labelTextSize = NA,
        ..errorBars = NA,
        ..ciLevel = NA,
        ..bootstrap = NA,
        ..errorBarWidth = NA,
        ..errorBarLineSize = NA,
        ..singleColor = NA,
        ..colorNo = NA,
        ..colorPalette = NA,
        ..borderColor = NA,
        ..textColor = NA,
        ..facetBy = NA,
        ..facetNumber = NA,
        ..titleText = NA,
        ..titleFontFace = NA,
        ..titleFontSize = NA,
        ..titleAlign = NA,
        ..subtitleText = NA,
        ..subtitleFontFace = NA,
        ..subtitleFontSize = NA,
        ..subtitleAlign = NA,
        ..captionText = NA,
        ..captionFontFace = NA,
        ..captionFontSize = NA,
        ..captionAlign = NA,
        ..legendText = NA,
        ..legendFontSize = NA,
        ..legendPosition = NA,
        ..xAxisText = NA,
        ..xAxisFontSize = NA,
        ..xAxisPosition = NA,
        ..yAxisText = NA,
        ..yAxisFontSize = NA,
        ..yAxisPosition = NA,
        ..yAxisLabelFontSize = NA,
        ..yAxisLabelRotation = NA,
        ..yAxisRangeType = NA,
        ..yAxisRangeMin = NA,
        ..yAxisRangeMax = NA,
        ..xAxisLabelFontSize = NA,
        ..xAxisLabelRotation = NA,
        ..xAxisRangeType = NA,
        ..xAxisRangeMin = NA,
        ..xAxisRangeMax = NA,
        ..xTicks = NA,
        ..yTicks = NA)
)

barchartResults <- if (requireNamespace("jmvcore", quietly=TRUE)) R6::R6Class(
    "barchartResults",
    inherit = jmvcore::Group,
    active = list(
        plot = function() private$.items[["plot"]]),
    private = list(),
    public=list(
        initialize=function(options) {
            super$initialize(
                options=options,
                name="",
                title="Bar Chart")
            self$add(jmvcore::Image$new(
                options=options,
                name="plot",
                title="",
                width=600,
                height=400,
                renderFun=".plot"))}))

barchartBase <- if (requireNamespace("jmvcore", quietly=TRUE)) R6::R6Class(
    "barchartBase",
    inherit = jmvcore::Analysis,
    public = list(
        initialize = function(options, data=NULL, datasetId="", analysisId="", revision=0) {
            super$initialize(
                package = "vijPlots",
                name = "barchart",
                version = c(1,0,0),
                options = options,
                results = barchartResults$new(options=options),
                data = data,
                datasetId = datasetId,
                analysisId = analysisId,
                revision = revision,
                pause = NULL,
                completeWhenFilled = FALSE,
                requiresMissings = FALSE,
                weightsSupport = 'auto')
        }))

#' Bar Chart
#'
#' 
#' @param data .
#' @param yVar .
#' @param xVar .
#' @param group .
#' @param facet .
#' @param yaxis .
#' @param order .
#' @param barType .
#' @param horizontal .
#' @param ignoreNA .
#' @param reverseStack .
#' @param showLabels .
#' @param decimalPrecision .
#' @param labelTextSize .
#' @param errorBars .
#' @param ciLevel .
#' @param bootstrap .
#' @param errorBarWidth .
#' @param errorBarLineSize .
#' @param singleColor .
#' @param colorNo .
#' @param colorPalette .
#' @param borderColor .
#' @param textColor .
#' @param facetBy .
#' @param facetNumber .
#' @param titleText .
#' @param titleFontFace .
#' @param titleFontSize .
#' @param titleAlign .
#' @param subtitleText .
#' @param subtitleFontFace .
#' @param subtitleFontSize .
#' @param subtitleAlign .
#' @param captionText .
#' @param captionFontFace .
#' @param captionFontSize .
#' @param captionAlign .
#' @param legendText .
#' @param legendFontSize .
#' @param legendPosition .
#' @param xAxisText .
#' @param xAxisFontSize .
#' @param xAxisPosition .
#' @param yAxisText .
#' @param yAxisFontSize .
#' @param yAxisPosition .
#' @param yAxisLabelFontSize .
#' @param yAxisLabelRotation .
#' @param yAxisRangeType .
#' @param yAxisRangeMin .
#' @param yAxisRangeMax .
#' @param xAxisLabelFontSize .
#' @param xAxisLabelRotation .
#' @param xAxisRangeType .
#' @param xAxisRangeMin .
#' @param xAxisRangeMax .
#' @param xTicks .
#' @param yTicks .
#' @return A results object containing:
#' \tabular{llllll}{
#'   \code{results$plot} \tab \tab \tab \tab \tab an image \cr
#' }
#'
#' @export
barchart <- function(
    data,
    yVar,
    xVar,
    group,
    facet,
    yaxis = "mean",
    order = "none",
    barType = "dodge2",
    horizontal = FALSE,
    ignoreNA = TRUE,
    reverseStack = FALSE,
    showLabels = TRUE,
    decimalPrecision = 1,
    labelTextSize = 12,
    errorBars = "none",
    ciLevel = 95,
    bootstrap = FALSE,
    errorBarWidth = 0.2,
    errorBarLineSize = 0.5,
    singleColor = TRUE,
    colorNo = 1,
    colorPalette = "jmv",
    borderColor = "none",
    textColor = "auto",
    facetBy = "column",
    facetNumber = 1,
    titleText,
    titleFontFace = "bold",
    titleFontSize = "14",
    titleAlign = "0.5",
    subtitleText,
    subtitleFontFace = "plain",
    subtitleFontSize = "12",
    subtitleAlign = "0.5",
    captionText,
    captionFontFace = "italic",
    captionFontSize = "10",
    captionAlign = "1",
    legendText,
    legendFontSize = "14",
    legendPosition = "right",
    xAxisText,
    xAxisFontSize = "16",
    xAxisPosition = "0.5",
    yAxisText,
    yAxisFontSize = "16",
    yAxisPosition = "0.5",
    yAxisLabelFontSize = 12,
    yAxisLabelRotation = 0,
    yAxisRangeType = "auto",
    yAxisRangeMin = 0,
    yAxisRangeMax = 10,
    xAxisLabelFontSize = 12,
    xAxisLabelRotation = 0,
    xAxisRangeType = "auto",
    xAxisRangeMin = 0,
    xAxisRangeMax = 10,
    xTicks = 0,
    yTicks = 0) {

    if ( ! requireNamespace("jmvcore", quietly=TRUE))
        stop("barchart requires jmvcore to be installed (restart may be required)")

    if ( ! missing(yVar)) yVar <- jmvcore::resolveQuo(jmvcore::enquo(yVar))
    if ( ! missing(xVar)) xVar <- jmvcore::resolveQuo(jmvcore::enquo(xVar))
    if ( ! missing(group)) group <- jmvcore::resolveQuo(jmvcore::enquo(group))
    if ( ! missing(facet)) facet <- jmvcore::resolveQuo(jmvcore::enquo(facet))
    if (missing(data))
        data <- jmvcore::marshalData(
            parent.frame(),
            `if`( ! missing(yVar), yVar, NULL),
            `if`( ! missing(xVar), xVar, NULL),
            `if`( ! missing(group), group, NULL),
            `if`( ! missing(facet), facet, NULL))

    for (v in xVar) if (v %in% names(data)) data[[v]] <- as.factor(data[[v]])
    for (v in group) if (v %in% names(data)) data[[v]] <- as.factor(data[[v]])
    for (v in facet) if (v %in% names(data)) data[[v]] <- as.factor(data[[v]])

    options <- barchartOptions$new(
        yVar = yVar,
        xVar = xVar,
        group = group,
        facet = facet,
        yaxis = yaxis,
        order = order,
        barType = barType,
        horizontal = horizontal,
        ignoreNA = ignoreNA,
        reverseStack = reverseStack,
        showLabels = showLabels,
        decimalPrecision = decimalPrecision,
        labelTextSize = labelTextSize,
        errorBars = errorBars,
        ciLevel = ciLevel,
        bootstrap = bootstrap,
        errorBarWidth = errorBarWidth,
        errorBarLineSize = errorBarLineSize,
        singleColor = singleColor,
        colorNo = colorNo,
        colorPalette = colorPalette,
        borderColor = borderColor,
        textColor = textColor,
        facetBy = facetBy,
        facetNumber = facetNumber,
        titleText = titleText,
        titleFontFace = titleFontFace,
        titleFontSize = titleFontSize,
        titleAlign = titleAlign,
        subtitleText = subtitleText,
        subtitleFontFace = subtitleFontFace,
        subtitleFontSize = subtitleFontSize,
        subtitleAlign = subtitleAlign,
        captionText = captionText,
        captionFontFace = captionFontFace,
        captionFontSize = captionFontSize,
        captionAlign = captionAlign,
        legendText = legendText,
        legendFontSize = legendFontSize,
        legendPosition = legendPosition,
        xAxisText = xAxisText,
        xAxisFontSize = xAxisFontSize,
        xAxisPosition = xAxisPosition,
        yAxisText = yAxisText,
        yAxisFontSize = yAxisFontSize,
        yAxisPosition = yAxisPosition,
        yAxisLabelFontSize = yAxisLabelFontSize,
        yAxisLabelRotation = yAxisLabelRotation,
        yAxisRangeType = yAxisRangeType,
        yAxisRangeMin = yAxisRangeMin,
        yAxisRangeMax = yAxisRangeMax,
        xAxisLabelFontSize = xAxisLabelFontSize,
        xAxisLabelRotation = xAxisLabelRotation,
        xAxisRangeType = xAxisRangeType,
        xAxisRangeMin = xAxisRangeMin,
        xAxisRangeMax = xAxisRangeMax,
        xTicks = xTicks,
        yTicks = yTicks)

    analysis <- barchartClass$new(
        options = options,
        data = data)

    analysis$run()

    analysis$results
}

