
# This file is automatically generated, you probably don't want to edit this

correspOptions <- if (requireNamespace("jmvcore", quietly=TRUE)) R6::R6Class(
    "correspOptions",
    inherit = jmvcore::Options,
    public = list(
        initialize = function(
            mode = NULL,
            rows = NULL,
            cols = NULL,
            columns = NULL,
            rowLabels = NULL,
            columnTitle = "Columns",
            counts = NULL,
            showContingency = FALSE,
            showProfiles = FALSE,
            showInertia = TRUE,
            showSummaries = FALSE,
            showRowPlot = FALSE,
            showColPlot = FALSE,
            showBiPlot = TRUE,
            supplementaryRows = NULL,
            supplementaryCols = NULL,
            dimNum = 2,
            xaxis = 1,
            yaxis = 2,
            normalization = "principal",
            labelSize = 12,
            rowColor = "blue",
            colColor = "red",
            supColor = "darkgray",
            columnTitleText = "default",
            rowTitleText = "default",
            biplotTitleText = "default",
            titleAlign = "0.5",
            titleFontSize = 16,
            titleFontFace = "plain",
            columnSubtitleText = "default",
            rowSubtitleText = "default",
            biplotSubtitleText = "default",
            subtitleAlign = "0.5",
            subtitleFontSize = 12,
            subtitleFontFace = "italic",
            rowCaptionText = NULL,
            columnCaptionText = NULL,
            biplotCaptionText = NULL,
            captionAlign = "1",
            captionFontSize = 12,
            captionFontFace = "plain",
            xAxisText = NULL,
            xAxisFontSize = "16",
            xAxisPosition = "0.5",
            yAxisText = NULL,
            yAxisFontSize = "16",
            yAxisPosition = "0.5",
            descAsVarName = FALSE, ...) {

            super$initialize(
                package="vijPlots",
                name="corresp",
                requiresData=TRUE,
                ...)

            private$..mode <- jmvcore::OptionList$new(
                "mode",
                mode,
                options=list(
                    "obsTable",
                    "contTable"))
            private$..rows <- jmvcore::OptionVariable$new(
                "rows",
                rows,
                suggested=list(
                    "nominal",
                    "ordinal"),
                permitted=list(
                    "factor"))
            private$..cols <- jmvcore::OptionVariable$new(
                "cols",
                cols,
                suggested=list(
                    "nominal",
                    "ordinal"),
                permitted=list(
                    "factor"))
            private$..columns <- jmvcore::OptionVariables$new(
                "columns",
                columns,
                suggested=list(
                    "continuous"),
                permitted=list(
                    "numeric"))
            private$..rowLabels <- jmvcore::OptionVariable$new(
                "rowLabels",
                rowLabels,
                suggested=list(
                    "nominal",
                    "ordinal"),
                permitted=list(
                    "factor"))
            private$..columnTitle <- jmvcore::OptionString$new(
                "columnTitle",
                columnTitle,
                default="Columns")
            private$..counts <- jmvcore::OptionVariable$new(
                "counts",
                counts,
                suggested=list(
                    "continuous"),
                permitted=list(
                    "numeric"))
            private$..showContingency <- jmvcore::OptionBool$new(
                "showContingency",
                showContingency,
                default=FALSE)
            private$..showProfiles <- jmvcore::OptionBool$new(
                "showProfiles",
                showProfiles,
                default=FALSE)
            private$..showInertia <- jmvcore::OptionBool$new(
                "showInertia",
                showInertia,
                default=TRUE)
            private$..showSummaries <- jmvcore::OptionBool$new(
                "showSummaries",
                showSummaries,
                default=FALSE)
            private$..showRowPlot <- jmvcore::OptionBool$new(
                "showRowPlot",
                showRowPlot,
                default=FALSE)
            private$..showColPlot <- jmvcore::OptionBool$new(
                "showColPlot",
                showColPlot,
                default=FALSE)
            private$..showBiPlot <- jmvcore::OptionBool$new(
                "showBiPlot",
                showBiPlot,
                default=TRUE)
            private$..supplementaryRows <- jmvcore::OptionString$new(
                "supplementaryRows",
                supplementaryRows)
            private$..supplementaryCols <- jmvcore::OptionString$new(
                "supplementaryCols",
                supplementaryCols)
            private$..dimNum <- jmvcore::OptionNumber$new(
                "dimNum",
                dimNum,
                min=2,
                max=10,
                default=2)
            private$..xaxis <- jmvcore::OptionNumber$new(
                "xaxis",
                xaxis,
                min=1,
                max=10,
                default=1)
            private$..yaxis <- jmvcore::OptionNumber$new(
                "yaxis",
                yaxis,
                min=1,
                max=10,
                default=2)
            private$..normalization <- jmvcore::OptionList$new(
                "normalization",
                normalization,
                options=list(
                    "principal",
                    "symmetric",
                    "rowprincipal",
                    "colprincipal",
                    "standard"),
                default="principal")
            private$..labelSize <- jmvcore::OptionInteger$new(
                "labelSize",
                labelSize,
                default=12,
                min=8,
                max=24)
            private$..rowColor <- jmvcore::OptionList$new(
                "rowColor",
                rowColor,
                options=list(
                    "blue",
                    "red",
                    "forestgreen",
                    "purple",
                    "hotpink",
                    "darkorange1"),
                default="blue")
            private$..colColor <- jmvcore::OptionList$new(
                "colColor",
                colColor,
                options=list(
                    "blue",
                    "red",
                    "forestgreen",
                    "purple",
                    "hotpink",
                    "darkorange1"),
                default="red")
            private$..supColor <- jmvcore::OptionList$new(
                "supColor",
                supColor,
                options=list(
                    "darkgray",
                    "black",
                    "yellow2",
                    "white"),
                default="darkgray")
            private$..columnTitleText <- jmvcore::OptionString$new(
                "columnTitleText",
                columnTitleText,
                default="default")
            private$..rowTitleText <- jmvcore::OptionString$new(
                "rowTitleText",
                rowTitleText,
                default="default")
            private$..biplotTitleText <- jmvcore::OptionString$new(
                "biplotTitleText",
                biplotTitleText,
                default="default")
            private$..titleAlign <- jmvcore::OptionList$new(
                "titleAlign",
                titleAlign,
                options=list(
                    "0",
                    "0.5",
                    "1"),
                default="0.5")
            private$..titleFontSize <- jmvcore::OptionNumber$new(
                "titleFontSize",
                titleFontSize,
                default=16,
                min=8,
                max=24)
            private$..titleFontFace <- jmvcore::OptionList$new(
                "titleFontFace",
                titleFontFace,
                options=list(
                    "plain",
                    "bold",
                    "italic",
                    "bold.italic"),
                default="plain")
            private$..columnSubtitleText <- jmvcore::OptionString$new(
                "columnSubtitleText",
                columnSubtitleText,
                default="default")
            private$..rowSubtitleText <- jmvcore::OptionString$new(
                "rowSubtitleText",
                rowSubtitleText,
                default="default")
            private$..biplotSubtitleText <- jmvcore::OptionString$new(
                "biplotSubtitleText",
                biplotSubtitleText,
                default="default")
            private$..subtitleAlign <- jmvcore::OptionList$new(
                "subtitleAlign",
                subtitleAlign,
                options=list(
                    "0",
                    "0.5",
                    "1"),
                default="0.5")
            private$..subtitleFontSize <- jmvcore::OptionNumber$new(
                "subtitleFontSize",
                subtitleFontSize,
                default=12,
                min=8,
                max=24)
            private$..subtitleFontFace <- jmvcore::OptionList$new(
                "subtitleFontFace",
                subtitleFontFace,
                options=list(
                    "plain",
                    "bold",
                    "italic",
                    "bold.italic"),
                default="italic")
            private$..rowCaptionText <- jmvcore::OptionString$new(
                "rowCaptionText",
                rowCaptionText)
            private$..columnCaptionText <- jmvcore::OptionString$new(
                "columnCaptionText",
                columnCaptionText)
            private$..biplotCaptionText <- jmvcore::OptionString$new(
                "biplotCaptionText",
                biplotCaptionText)
            private$..captionAlign <- jmvcore::OptionList$new(
                "captionAlign",
                captionAlign,
                options=list(
                    "0",
                    "0.5",
                    "1"),
                default="1")
            private$..captionFontSize <- jmvcore::OptionNumber$new(
                "captionFontSize",
                captionFontSize,
                default=12,
                min=8,
                max=24)
            private$..captionFontFace <- jmvcore::OptionList$new(
                "captionFontFace",
                captionFontFace,
                options=list(
                    "plain",
                    "bold",
                    "italic",
                    "bold.italic"),
                default="plain")
            private$..xAxisText <- jmvcore::OptionString$new(
                "xAxisText",
                xAxisText)
            private$..xAxisFontSize <- jmvcore::OptionList$new(
                "xAxisFontSize",
                xAxisFontSize,
                options=list(
                    "10",
                    "12",
                    "14",
                    "16",
                    "18",
                    "20"),
                default="16")
            private$..xAxisPosition <- jmvcore::OptionList$new(
                "xAxisPosition",
                xAxisPosition,
                options=list(
                    "0",
                    "0.5",
                    "1"),
                default="0.5")
            private$..yAxisText <- jmvcore::OptionString$new(
                "yAxisText",
                yAxisText)
            private$..yAxisFontSize <- jmvcore::OptionList$new(
                "yAxisFontSize",
                yAxisFontSize,
                options=list(
                    "10",
                    "12",
                    "14",
                    "16",
                    "18",
                    "20"),
                default="16")
            private$..yAxisPosition <- jmvcore::OptionList$new(
                "yAxisPosition",
                yAxisPosition,
                options=list(
                    "1",
                    "0.5",
                    "0"),
                default="0.5")
            private$..descAsVarName <- jmvcore::OptionBool$new(
                "descAsVarName",
                descAsVarName,
                default=FALSE)

            self$.addOption(private$..mode)
            self$.addOption(private$..rows)
            self$.addOption(private$..cols)
            self$.addOption(private$..columns)
            self$.addOption(private$..rowLabels)
            self$.addOption(private$..columnTitle)
            self$.addOption(private$..counts)
            self$.addOption(private$..showContingency)
            self$.addOption(private$..showProfiles)
            self$.addOption(private$..showInertia)
            self$.addOption(private$..showSummaries)
            self$.addOption(private$..showRowPlot)
            self$.addOption(private$..showColPlot)
            self$.addOption(private$..showBiPlot)
            self$.addOption(private$..supplementaryRows)
            self$.addOption(private$..supplementaryCols)
            self$.addOption(private$..dimNum)
            self$.addOption(private$..xaxis)
            self$.addOption(private$..yaxis)
            self$.addOption(private$..normalization)
            self$.addOption(private$..labelSize)
            self$.addOption(private$..rowColor)
            self$.addOption(private$..colColor)
            self$.addOption(private$..supColor)
            self$.addOption(private$..columnTitleText)
            self$.addOption(private$..rowTitleText)
            self$.addOption(private$..biplotTitleText)
            self$.addOption(private$..titleAlign)
            self$.addOption(private$..titleFontSize)
            self$.addOption(private$..titleFontFace)
            self$.addOption(private$..columnSubtitleText)
            self$.addOption(private$..rowSubtitleText)
            self$.addOption(private$..biplotSubtitleText)
            self$.addOption(private$..subtitleAlign)
            self$.addOption(private$..subtitleFontSize)
            self$.addOption(private$..subtitleFontFace)
            self$.addOption(private$..rowCaptionText)
            self$.addOption(private$..columnCaptionText)
            self$.addOption(private$..biplotCaptionText)
            self$.addOption(private$..captionAlign)
            self$.addOption(private$..captionFontSize)
            self$.addOption(private$..captionFontFace)
            self$.addOption(private$..xAxisText)
            self$.addOption(private$..xAxisFontSize)
            self$.addOption(private$..xAxisPosition)
            self$.addOption(private$..yAxisText)
            self$.addOption(private$..yAxisFontSize)
            self$.addOption(private$..yAxisPosition)
            self$.addOption(private$..descAsVarName)
        }),
    active = list(
        mode = function() private$..mode$value,
        rows = function() private$..rows$value,
        cols = function() private$..cols$value,
        columns = function() private$..columns$value,
        rowLabels = function() private$..rowLabels$value,
        columnTitle = function() private$..columnTitle$value,
        counts = function() private$..counts$value,
        showContingency = function() private$..showContingency$value,
        showProfiles = function() private$..showProfiles$value,
        showInertia = function() private$..showInertia$value,
        showSummaries = function() private$..showSummaries$value,
        showRowPlot = function() private$..showRowPlot$value,
        showColPlot = function() private$..showColPlot$value,
        showBiPlot = function() private$..showBiPlot$value,
        supplementaryRows = function() private$..supplementaryRows$value,
        supplementaryCols = function() private$..supplementaryCols$value,
        dimNum = function() private$..dimNum$value,
        xaxis = function() private$..xaxis$value,
        yaxis = function() private$..yaxis$value,
        normalization = function() private$..normalization$value,
        labelSize = function() private$..labelSize$value,
        rowColor = function() private$..rowColor$value,
        colColor = function() private$..colColor$value,
        supColor = function() private$..supColor$value,
        columnTitleText = function() private$..columnTitleText$value,
        rowTitleText = function() private$..rowTitleText$value,
        biplotTitleText = function() private$..biplotTitleText$value,
        titleAlign = function() private$..titleAlign$value,
        titleFontSize = function() private$..titleFontSize$value,
        titleFontFace = function() private$..titleFontFace$value,
        columnSubtitleText = function() private$..columnSubtitleText$value,
        rowSubtitleText = function() private$..rowSubtitleText$value,
        biplotSubtitleText = function() private$..biplotSubtitleText$value,
        subtitleAlign = function() private$..subtitleAlign$value,
        subtitleFontSize = function() private$..subtitleFontSize$value,
        subtitleFontFace = function() private$..subtitleFontFace$value,
        rowCaptionText = function() private$..rowCaptionText$value,
        columnCaptionText = function() private$..columnCaptionText$value,
        biplotCaptionText = function() private$..biplotCaptionText$value,
        captionAlign = function() private$..captionAlign$value,
        captionFontSize = function() private$..captionFontSize$value,
        captionFontFace = function() private$..captionFontFace$value,
        xAxisText = function() private$..xAxisText$value,
        xAxisFontSize = function() private$..xAxisFontSize$value,
        xAxisPosition = function() private$..xAxisPosition$value,
        yAxisText = function() private$..yAxisText$value,
        yAxisFontSize = function() private$..yAxisFontSize$value,
        yAxisPosition = function() private$..yAxisPosition$value,
        descAsVarName = function() private$..descAsVarName$value),
    private = list(
        ..mode = NA,
        ..rows = NA,
        ..cols = NA,
        ..columns = NA,
        ..rowLabels = NA,
        ..columnTitle = NA,
        ..counts = NA,
        ..showContingency = NA,
        ..showProfiles = NA,
        ..showInertia = NA,
        ..showSummaries = NA,
        ..showRowPlot = NA,
        ..showColPlot = NA,
        ..showBiPlot = NA,
        ..supplementaryRows = NA,
        ..supplementaryCols = NA,
        ..dimNum = NA,
        ..xaxis = NA,
        ..yaxis = NA,
        ..normalization = NA,
        ..labelSize = NA,
        ..rowColor = NA,
        ..colColor = NA,
        ..supColor = NA,
        ..columnTitleText = NA,
        ..rowTitleText = NA,
        ..biplotTitleText = NA,
        ..titleAlign = NA,
        ..titleFontSize = NA,
        ..titleFontFace = NA,
        ..columnSubtitleText = NA,
        ..rowSubtitleText = NA,
        ..biplotSubtitleText = NA,
        ..subtitleAlign = NA,
        ..subtitleFontSize = NA,
        ..subtitleFontFace = NA,
        ..rowCaptionText = NA,
        ..columnCaptionText = NA,
        ..biplotCaptionText = NA,
        ..captionAlign = NA,
        ..captionFontSize = NA,
        ..captionFontFace = NA,
        ..xAxisText = NA,
        ..xAxisFontSize = NA,
        ..xAxisPosition = NA,
        ..yAxisText = NA,
        ..yAxisFontSize = NA,
        ..yAxisPosition = NA,
        ..descAsVarName = NA)
)

correspResults <- if (requireNamespace("jmvcore", quietly=TRUE)) R6::R6Class(
    "correspResults",
    inherit = jmvcore::Group,
    active = list(
        contingency = function() private$.items[["contingency"]],
        rowProfiles = function() private$.items[["rowProfiles"]],
        colProfiles = function() private$.items[["colProfiles"]],
        eigenvalues = function() private$.items[["eigenvalues"]],
        rowSummary = function() private$.items[["rowSummary"]],
        colSummary = function() private$.items[["colSummary"]],
        rowplot = function() private$.items[["rowplot"]],
        colplot = function() private$.items[["colplot"]],
        biplot = function() private$.items[["biplot"]]),
    private = list(),
    public=list(
        initialize=function(options) {
            super$initialize(
                options=options,
                name="",
                title="Correspondence Analysis",
                refs=list(
                    "factominer"))
            self$add(jmvcore::Table$new(
                options=options,
                name="contingency",
                title="Contingency Table",
                visible="(showContingency)",
                rows=0,
                columns=list(),
                clearWith=list(
                    "rows",
                    "cols",
                    "descAsVarName",
                    "columns",
                    "rowLabels",
                    "columnTitle")))
            self$add(jmvcore::Table$new(
                options=options,
                name="rowProfiles",
                title="Row Profiles",
                visible="(showProfiles)",
                rows=0,
                columns=list(),
                clearWith=list(
                    "rows",
                    "cols",
                    "descAsVarName",
                    "columns",
                    "rowLabels",
                    "columnTitle")))
            self$add(jmvcore::Table$new(
                options=options,
                name="colProfiles",
                title="Column Profiles",
                visible="(showProfiles)",
                rows=0,
                columns=list(),
                clearWith=list(
                    "rows",
                    "cols",
                    "descAsVarName",
                    "columns",
                    "rowLabels",
                    "columnTitle")))
            self$add(jmvcore::Table$new(
                options=options,
                name="eigenvalues",
                title="Summary",
                visible="(showInertia)",
                rows=0,
                columns=list(
                    list(
                        `name`="dim", 
                        `title`="Dimension", 
                        `type`="number"),
                    list(
                        `name`="singular", 
                        `title`="Singular Value", 
                        `type`="number", 
                        `format`="zto"),
                    list(
                        `name`="inertia", 
                        `title`="Inertia", 
                        `type`="number", 
                        `format`="zto"),
                    list(
                        `name`="proportion", 
                        `title`="% of Inertia", 
                        `type`="integer", 
                        `format`="pc"),
                    list(
                        `name`="cumulative", 
                        `title`="Cumulative %", 
                        `type`="number", 
                        `format`="pc")),
                clearWith=list(
                    "rows",
                    "cols",
                    "counts",
                    "columns",
                    "rowLabels")))
            self$add(jmvcore::Table$new(
                options=options,
                name="rowSummary",
                title="Row Summary",
                rows=0,
                visible="(showSummaries)",
                columns=list(),
                clearWith=list(
                    "rows",
                    "cols",
                    "counts",
                    "dimNum",
                    "normalization",
                    "descAsVarName",
                    "columns",
                    "rowLabels")))
            self$add(jmvcore::Table$new(
                options=options,
                name="colSummary",
                title="Column Summary",
                rows=0,
                visible="(showSummaries)",
                columns=list(),
                clearWith=list(
                    "rows",
                    "cols",
                    "counts",
                    "dimNum",
                    "normalization",
                    "descAsVarName",
                    "columns",
                    "rowLabels",
                    "columnTitle")))
            self$add(jmvcore::Image$new(
                options=options,
                name="rowplot",
                title="Row Plot",
                visible="(showRowPlot)",
                width=600,
                height=450,
                renderFun=".rowplot",
                clearWith=list(
                    "rows",
                    "cols",
                    "counts",
                    "columns",
                    "rowLabels",
                    "xaxis",
                    "yaxis",
                    "rowColor",
                    "supColor",
                    "supplementaryRows",
                    "supplementaryCols",
                    "normalization",
                    "descAsVarName",
                    "rowTitleText",
                    "titleFontFace",
                    "titleFontSize",
                    "titleAlign",
                    "rowSubtitleText",
                    "subtitleFontFace",
                    "subtitleFontSize",
                    "subtitleAlign",
                    "rowCaptionText",
                    "captionFontFace",
                    "captionFontSize",
                    "captionAlign",
                    "xAxisText",
                    "xAxisFontSize",
                    "xAxisPosition",
                    "yAxisText",
                    "yAxisFontSize",
                    "yAxisPosition",
                    "labelSize")))
            self$add(jmvcore::Image$new(
                options=options,
                name="colplot",
                title="Column Plot",
                visible="(showColPlot)",
                width=600,
                height=450,
                renderFun=".colplot",
                clearWith=list(
                    "rows",
                    "cols",
                    "counts",
                    "columns",
                    "rowLabels",
                    "columnTitle",
                    "xaxis",
                    "yaxis",
                    "colColor",
                    "supColor",
                    "supplementaryRows",
                    "supplementaryCols",
                    "normalization",
                    "descAsVarName",
                    "columnTitleText",
                    "titleFontFace",
                    "titleFontSize",
                    "titleAlign",
                    "columnSubtitleText",
                    "subtitleFontFace",
                    "subtitleFontSize",
                    "subtitleAlign",
                    "columnCaptionText",
                    "captionFontFace",
                    "captionFontSize",
                    "captionAlign",
                    "xAxisText",
                    "xAxisFontSize",
                    "xAxisPosition",
                    "yAxisText",
                    "yAxisFontSize",
                    "yAxisPosition",
                    "labelSize")))
            self$add(jmvcore::Image$new(
                options=options,
                name="biplot",
                title="Biplot",
                visible="(showBiPlot)",
                width=600,
                height=450,
                renderFun=".biplot",
                clearWith=list(
                    "rows",
                    "cols",
                    "counts",
                    "columns",
                    "rowLabels",
                    "columnTitle",
                    "xaxis",
                    "yaxis",
                    "rowColor",
                    "colColor",
                    "supColor",
                    "supplementaryRows",
                    "supplementaryCols",
                    "normalization",
                    "descAsVarName",
                    "biplotTitleText",
                    "titleFontFace",
                    "titleFontSize",
                    "titleAlign",
                    "biplotSubtitleText",
                    "subtitleFontFace",
                    "subtitleFontSize",
                    "subtitleAlign",
                    "biplotCaptionText",
                    "captionFontFace",
                    "captionFontSize",
                    "captionAlign",
                    "xAxisText",
                    "xAxisFontSize",
                    "xAxisPosition",
                    "yAxisText",
                    "yAxisFontSize",
                    "yAxisPosition",
                    "labelSize")))}))

correspBase <- if (requireNamespace("jmvcore", quietly=TRUE)) R6::R6Class(
    "correspBase",
    inherit = jmvcore::Analysis,
    public = list(
        initialize = function(options, data=NULL, datasetId="", analysisId="", revision=0) {
            super$initialize(
                package = "vijPlots",
                name = "corresp",
                version = c(1,0,0),
                options = options,
                results = correspResults$new(options=options),
                data = data,
                datasetId = datasetId,
                analysisId = analysisId,
                revision = revision,
                pause = NULL,
                completeWhenFilled = FALSE,
                requiresMissings = FALSE,
                weightsSupport = 'full')
        }))

#' Correspondence Analysis
#'
#' 
#' @param data .
#' @param mode .
#' @param rows .
#' @param cols .
#' @param columns .
#' @param rowLabels .
#' @param columnTitle .
#' @param counts .
#' @param showContingency .
#' @param showProfiles .
#' @param showInertia .
#' @param showSummaries .
#' @param showRowPlot .
#' @param showColPlot .
#' @param showBiPlot .
#' @param supplementaryRows .
#' @param supplementaryCols .
#' @param dimNum .
#' @param xaxis .
#' @param yaxis .
#' @param normalization .
#' @param labelSize .
#' @param rowColor .
#' @param colColor .
#' @param supColor .
#' @param columnTitleText .
#' @param rowTitleText .
#' @param biplotTitleText .
#' @param titleAlign .
#' @param titleFontSize .
#' @param titleFontFace .
#' @param columnSubtitleText .
#' @param rowSubtitleText .
#' @param biplotSubtitleText .
#' @param subtitleAlign .
#' @param subtitleFontSize .
#' @param subtitleFontFace .
#' @param rowCaptionText .
#' @param columnCaptionText .
#' @param biplotCaptionText .
#' @param captionAlign .
#' @param captionFontSize .
#' @param captionFontFace .
#' @param xAxisText .
#' @param xAxisFontSize .
#' @param xAxisPosition .
#' @param yAxisText .
#' @param yAxisFontSize .
#' @param yAxisPosition .
#' @param descAsVarName .
#' @return A results object containing:
#' \tabular{llllll}{
#'   \code{results$contingency} \tab \tab \tab \tab \tab a table \cr
#'   \code{results$rowProfiles} \tab \tab \tab \tab \tab a table \cr
#'   \code{results$colProfiles} \tab \tab \tab \tab \tab a table \cr
#'   \code{results$eigenvalues} \tab \tab \tab \tab \tab a table \cr
#'   \code{results$rowSummary} \tab \tab \tab \tab \tab a table \cr
#'   \code{results$colSummary} \tab \tab \tab \tab \tab a table \cr
#'   \code{results$rowplot} \tab \tab \tab \tab \tab an image \cr
#'   \code{results$colplot} \tab \tab \tab \tab \tab an image \cr
#'   \code{results$biplot} \tab \tab \tab \tab \tab an image \cr
#' }
#'
#' Tables can be converted to data frames with \code{asDF} or \code{\link{as.data.frame}}. For example:
#'
#' \code{results$contingency$asDF}
#'
#' \code{as.data.frame(results$contingency)}
#'
#' @export
corresp <- function(
    data,
    mode,
    rows,
    cols,
    columns,
    rowLabels,
    columnTitle = "Columns",
    counts,
    showContingency = FALSE,
    showProfiles = FALSE,
    showInertia = TRUE,
    showSummaries = FALSE,
    showRowPlot = FALSE,
    showColPlot = FALSE,
    showBiPlot = TRUE,
    supplementaryRows,
    supplementaryCols,
    dimNum = 2,
    xaxis = 1,
    yaxis = 2,
    normalization = "principal",
    labelSize = 12,
    rowColor = "blue",
    colColor = "red",
    supColor = "darkgray",
    columnTitleText = "default",
    rowTitleText = "default",
    biplotTitleText = "default",
    titleAlign = "0.5",
    titleFontSize = 16,
    titleFontFace = "plain",
    columnSubtitleText = "default",
    rowSubtitleText = "default",
    biplotSubtitleText = "default",
    subtitleAlign = "0.5",
    subtitleFontSize = 12,
    subtitleFontFace = "italic",
    rowCaptionText,
    columnCaptionText,
    biplotCaptionText,
    captionAlign = "1",
    captionFontSize = 12,
    captionFontFace = "plain",
    xAxisText,
    xAxisFontSize = "16",
    xAxisPosition = "0.5",
    yAxisText,
    yAxisFontSize = "16",
    yAxisPosition = "0.5",
    descAsVarName = FALSE) {

    if ( ! requireNamespace("jmvcore", quietly=TRUE))
        stop("corresp requires jmvcore to be installed (restart may be required)")

    if ( ! missing(rows)) rows <- jmvcore::resolveQuo(jmvcore::enquo(rows))
    if ( ! missing(cols)) cols <- jmvcore::resolveQuo(jmvcore::enquo(cols))
    if ( ! missing(columns)) columns <- jmvcore::resolveQuo(jmvcore::enquo(columns))
    if ( ! missing(rowLabels)) rowLabels <- jmvcore::resolveQuo(jmvcore::enquo(rowLabels))
    if ( ! missing(counts)) counts <- jmvcore::resolveQuo(jmvcore::enquo(counts))
    if (missing(data))
        data <- jmvcore::marshalData(
            parent.frame(),
            `if`( ! missing(rows), rows, NULL),
            `if`( ! missing(cols), cols, NULL),
            `if`( ! missing(columns), columns, NULL),
            `if`( ! missing(rowLabels), rowLabels, NULL),
            `if`( ! missing(counts), counts, NULL))

    for (v in rows) if (v %in% names(data)) data[[v]] <- as.factor(data[[v]])
    for (v in cols) if (v %in% names(data)) data[[v]] <- as.factor(data[[v]])
    for (v in rowLabels) if (v %in% names(data)) data[[v]] <- as.factor(data[[v]])

    options <- correspOptions$new(
        mode = mode,
        rows = rows,
        cols = cols,
        columns = columns,
        rowLabels = rowLabels,
        columnTitle = columnTitle,
        counts = counts,
        showContingency = showContingency,
        showProfiles = showProfiles,
        showInertia = showInertia,
        showSummaries = showSummaries,
        showRowPlot = showRowPlot,
        showColPlot = showColPlot,
        showBiPlot = showBiPlot,
        supplementaryRows = supplementaryRows,
        supplementaryCols = supplementaryCols,
        dimNum = dimNum,
        xaxis = xaxis,
        yaxis = yaxis,
        normalization = normalization,
        labelSize = labelSize,
        rowColor = rowColor,
        colColor = colColor,
        supColor = supColor,
        columnTitleText = columnTitleText,
        rowTitleText = rowTitleText,
        biplotTitleText = biplotTitleText,
        titleAlign = titleAlign,
        titleFontSize = titleFontSize,
        titleFontFace = titleFontFace,
        columnSubtitleText = columnSubtitleText,
        rowSubtitleText = rowSubtitleText,
        biplotSubtitleText = biplotSubtitleText,
        subtitleAlign = subtitleAlign,
        subtitleFontSize = subtitleFontSize,
        subtitleFontFace = subtitleFontFace,
        rowCaptionText = rowCaptionText,
        columnCaptionText = columnCaptionText,
        biplotCaptionText = biplotCaptionText,
        captionAlign = captionAlign,
        captionFontSize = captionFontSize,
        captionFontFace = captionFontFace,
        xAxisText = xAxisText,
        xAxisFontSize = xAxisFontSize,
        xAxisPosition = xAxisPosition,
        yAxisText = yAxisText,
        yAxisFontSize = yAxisFontSize,
        yAxisPosition = yAxisPosition,
        descAsVarName = descAsVarName)

    analysis <- correspClass$new(
        options = options,
        data = data)

    analysis$run()

    analysis$results
}

