
# This file is automatically generated, you probably don't want to edit this

histogramOptions <- if (requireNamespace("jmvcore", quietly=TRUE)) R6::R6Class(
    "histogramOptions",
    inherit = jmvcore::Options,
    public = list(
        initialize = function(
            aVar = NULL,
            group = NULL,
            facet = NULL,
            histtype = "count",
            normalCurve = FALSE,
            density = FALSE,
            dashedDensity = FALSE,
            binWidth = 0,
            binBoundary = 0,
            densityOpacity = 0.2,
            densityLineSize = 0.5,
            normalCurveLineSize = 1,
            fillColor = "#A6C4F1",
            borderColor = "black",
            grouping = "none",
            groupingN = "stack",
            colorPalette = "jmv",
            usePalette = "forFilling",
            titleText = NULL,
            titleFontFace = "bold",
            titleFontSize = "14",
            titleAlign = "0.5",
            subtitleText = NULL,
            subtitleFontFace = "plain",
            subtitleFontSize = "12",
            subtitleAlign = "0.5",
            captionText = NULL,
            captionFontFace = "italic",
            captionFontSize = "10",
            captionAlign = "1",
            legendText = NULL,
            legendFontSize = "14",
            legendPosition = "right",
            xAxisText = NULL,
            xAxisFontSize = "16",
            xAxisPosition = "0.5",
            yAxisText = NULL,
            yAxisFontSize = "16",
            yAxisPosition = "0.5",
            facetBy = "column",
            facetNumber = 1,
            yAxisLabelFontSize = 12,
            yAxisLabelRotation = 0,
            yAxisRangeType = "auto",
            yAxisRangeMin = 0,
            yAxisRangeMax = 10,
            xAxisLabelFontSize = 12,
            xAxisLabelRotation = 0,
            xAxisRangeType = "auto",
            xAxisRangeMin = 0,
            xAxisRangeMax = 10,
            xTicks = 0,
            yTicks = 0, ...) {

            super$initialize(
                package="vijPlots",
                name="histogram",
                requiresData=TRUE,
                ...)

            private$..aVar <- jmvcore::OptionVariable$new(
                "aVar",
                aVar,
                suggested=list(
                    "continuous"),
                permitted=list(
                    "numeric"),
                default=NULL)
            private$..group <- jmvcore::OptionVariable$new(
                "group",
                group,
                suggested=list(
                    "nominal",
                    "ordinal"),
                permitted=list(
                    "factor"))
            private$..facet <- jmvcore::OptionVariable$new(
                "facet",
                facet,
                suggested=list(
                    "nominal",
                    "ordinal"),
                permitted=list(
                    "factor"))
            private$..histtype <- jmvcore::OptionList$new(
                "histtype",
                histtype,
                options=list(
                    "count",
                    "density"),
                default="count")
            private$..normalCurve <- jmvcore::OptionBool$new(
                "normalCurve",
                normalCurve,
                default=FALSE)
            private$..density <- jmvcore::OptionBool$new(
                "density",
                density,
                default=FALSE)
            private$..dashedDensity <- jmvcore::OptionBool$new(
                "dashedDensity",
                dashedDensity,
                default=FALSE)
            private$..binWidth <- jmvcore::OptionNumber$new(
                "binWidth",
                binWidth,
                min=0,
                default=0)
            private$..binBoundary <- jmvcore::OptionNumber$new(
                "binBoundary",
                binBoundary,
                min=0,
                default=0)
            private$..densityOpacity <- jmvcore::OptionNumber$new(
                "densityOpacity",
                densityOpacity,
                default=0.2,
                min=0,
                max=1)
            private$..densityLineSize <- jmvcore::OptionNumber$new(
                "densityLineSize",
                densityLineSize,
                default=0.5,
                min=0.1,
                max=5)
            private$..normalCurveLineSize <- jmvcore::OptionNumber$new(
                "normalCurveLineSize",
                normalCurveLineSize,
                default=1,
                min=0.1,
                max=5)
            private$..fillColor <- jmvcore::OptionList$new(
                "fillColor",
                fillColor,
                options=list(
                    "none",
                    "white",
                    "black",
                    "#A6C4F1",
                    "#C5C5C5",
                    "#F0CD8C",
                    "#88C38B",
                    "#E18A8A",
                    "#E41A1C",
                    "#377EB8",
                    "#4DAF4A",
                    "#984EA3",
                    "#FF7F00",
                    "#FFFF33",
                    "#A65628",
                    "#F781BF",
                    "#999999",
                    "#FBB4AE",
                    "#B3CDE3",
                    "#CCEBC5",
                    "#DECBE4",
                    "#FED9A6",
                    "#FFFFCC",
                    "#E5D8BD",
                    "#FDDAEC",
                    "#F2F2F2"),
                default="#A6C4F1")
            private$..borderColor <- jmvcore::OptionList$new(
                "borderColor",
                borderColor,
                options=list(
                    "none",
                    "black",
                    "white",
                    "gray"),
                default="black")
            private$..grouping <- jmvcore::OptionList$new(
                "grouping",
                grouping,
                hidden=TRUE,
                options=list(
                    "none",
                    "identity",
                    "stack",
                    "dodge"),
                default="none")
            private$..groupingN <- jmvcore::OptionList$new(
                "groupingN",
                groupingN,
                options=list(
                    "identity",
                    "stack"),
                default="stack")
            private$..colorPalette <- jmvcore::OptionList$new(
                "colorPalette",
                colorPalette,
                options=list(
                    "jmv",
                    "Set1",
                    "Set2",
                    "Set3",
                    "Pastel1",
                    "Pastel2",
                    "Accent",
                    "Paired",
                    "Dark2",
                    "Spectral",
                    "RdYlGn",
                    "RdYlBu",
                    "RdGy",
                    "RdBu",
                    "PuOr",
                    "PRGn",
                    "PiYG",
                    "BrBG",
                    "Blues",
                    "Greens",
                    "Greys",
                    "Oranges",
                    "Purples",
                    "Reds",
                    "BuGn",
                    "BuPu",
                    "GnBu",
                    "OrRd",
                    "PuBu",
                    "PuBuGn",
                    "PuRd",
                    "RdPu",
                    "YlGn",
                    "YlGnBu",
                    "YlOrBr",
                    "YlOrRd",
                    "viridis::viridis",
                    "viridis::magma",
                    "viridis::inferno",
                    "viridis::plasma",
                    "viridis::turbo",
                    "dichromat::Categorical.12",
                    "tidy::friendly",
                    "tidy::seaside",
                    "tidy::apple",
                    "tidy::ibm",
                    "tidy::candy",
                    "tidy::alger",
                    "tidy::rainbow",
                    "tidy::metro",
                    "custom::lemovice"),
                default="jmv")
            private$..usePalette <- jmvcore::OptionList$new(
                "usePalette",
                usePalette,
                options=list(
                    "forFilling",
                    "forBorder"),
                default="forFilling")
            private$..titleText <- jmvcore::OptionString$new(
                "titleText",
                titleText)
            private$..titleFontFace <- jmvcore::OptionList$new(
                "titleFontFace",
                titleFontFace,
                options=list(
                    "plain",
                    "bold",
                    "italic",
                    "bold.italic"),
                default="bold")
            private$..titleFontSize <- jmvcore::OptionList$new(
                "titleFontSize",
                titleFontSize,
                options=list(
                    "12",
                    "14",
                    "16",
                    "18",
                    "20",
                    "22",
                    "24"),
                default="14")
            private$..titleAlign <- jmvcore::OptionList$new(
                "titleAlign",
                titleAlign,
                options=list(
                    "0",
                    "0.5",
                    "1"),
                default="0.5")
            private$..subtitleText <- jmvcore::OptionString$new(
                "subtitleText",
                subtitleText)
            private$..subtitleFontFace <- jmvcore::OptionList$new(
                "subtitleFontFace",
                subtitleFontFace,
                options=list(
                    "plain",
                    "bold",
                    "italic",
                    "bold.italic"),
                default="plain")
            private$..subtitleFontSize <- jmvcore::OptionList$new(
                "subtitleFontSize",
                subtitleFontSize,
                options=list(
                    "10",
                    "12",
                    "14",
                    "16",
                    "18",
                    "20",
                    "22"),
                default="12")
            private$..subtitleAlign <- jmvcore::OptionList$new(
                "subtitleAlign",
                subtitleAlign,
                options=list(
                    "0",
                    "0.5",
                    "1"),
                default="0.5")
            private$..captionText <- jmvcore::OptionString$new(
                "captionText",
                captionText)
            private$..captionFontFace <- jmvcore::OptionList$new(
                "captionFontFace",
                captionFontFace,
                options=list(
                    "plain",
                    "bold",
                    "italic",
                    "bold.italic"),
                default="italic")
            private$..captionFontSize <- jmvcore::OptionList$new(
                "captionFontSize",
                captionFontSize,
                options=list(
                    "8",
                    "10",
                    "12",
                    "14",
                    "16",
                    "18",
                    "20"),
                default="10")
            private$..captionAlign <- jmvcore::OptionList$new(
                "captionAlign",
                captionAlign,
                options=list(
                    "0",
                    "0.5",
                    "1"),
                default="1")
            private$..legendText <- jmvcore::OptionString$new(
                "legendText",
                legendText)
            private$..legendFontSize <- jmvcore::OptionList$new(
                "legendFontSize",
                legendFontSize,
                options=list(
                    "10",
                    "12",
                    "14",
                    "16",
                    "18",
                    "20"),
                default="14")
            private$..legendPosition <- jmvcore::OptionList$new(
                "legendPosition",
                legendPosition,
                options=list(
                    "right",
                    "bottom",
                    "left",
                    "top"),
                default="right")
            private$..xAxisText <- jmvcore::OptionString$new(
                "xAxisText",
                xAxisText)
            private$..xAxisFontSize <- jmvcore::OptionList$new(
                "xAxisFontSize",
                xAxisFontSize,
                options=list(
                    "10",
                    "12",
                    "14",
                    "16",
                    "18",
                    "20"),
                default="16")
            private$..xAxisPosition <- jmvcore::OptionList$new(
                "xAxisPosition",
                xAxisPosition,
                options=list(
                    "0",
                    "0.5",
                    "1"),
                default="0.5")
            private$..yAxisText <- jmvcore::OptionString$new(
                "yAxisText",
                yAxisText)
            private$..yAxisFontSize <- jmvcore::OptionList$new(
                "yAxisFontSize",
                yAxisFontSize,
                options=list(
                    "10",
                    "12",
                    "14",
                    "16",
                    "18",
                    "20"),
                default="16")
            private$..yAxisPosition <- jmvcore::OptionList$new(
                "yAxisPosition",
                yAxisPosition,
                options=list(
                    "1",
                    "0.5",
                    "0"),
                default="0.5")
            private$..facetBy <- jmvcore::OptionList$new(
                "facetBy",
                facetBy,
                options=list(
                    "row",
                    "column"),
                default="column")
            private$..facetNumber <- jmvcore::OptionInteger$new(
                "facetNumber",
                facetNumber,
                min=1,
                max=10,
                default=1)
            private$..yAxisLabelFontSize <- jmvcore::OptionNumber$new(
                "yAxisLabelFontSize",
                yAxisLabelFontSize,
                default=12)
            private$..yAxisLabelRotation <- jmvcore::OptionNumber$new(
                "yAxisLabelRotation",
                yAxisLabelRotation,
                default=0,
                min=0,
                max=360)
            private$..yAxisRangeType <- jmvcore::OptionList$new(
                "yAxisRangeType",
                yAxisRangeType,
                options=list(
                    "auto",
                    "manual"),
                default="auto")
            private$..yAxisRangeMin <- jmvcore::OptionNumber$new(
                "yAxisRangeMin",
                yAxisRangeMin,
                default=0)
            private$..yAxisRangeMax <- jmvcore::OptionNumber$new(
                "yAxisRangeMax",
                yAxisRangeMax,
                default=10)
            private$..xAxisLabelFontSize <- jmvcore::OptionNumber$new(
                "xAxisLabelFontSize",
                xAxisLabelFontSize,
                default=12)
            private$..xAxisLabelRotation <- jmvcore::OptionNumber$new(
                "xAxisLabelRotation",
                xAxisLabelRotation,
                default=0,
                min=0,
                max=360)
            private$..xAxisRangeType <- jmvcore::OptionList$new(
                "xAxisRangeType",
                xAxisRangeType,
                options=list(
                    "auto",
                    "manual"),
                default="auto")
            private$..xAxisRangeMin <- jmvcore::OptionNumber$new(
                "xAxisRangeMin",
                xAxisRangeMin,
                default=0)
            private$..xAxisRangeMax <- jmvcore::OptionNumber$new(
                "xAxisRangeMax",
                xAxisRangeMax,
                default=10)
            private$..xTicks <- jmvcore::OptionInteger$new(
                "xTicks",
                xTicks,
                default=0,
                min=0,
                max=99)
            private$..yTicks <- jmvcore::OptionInteger$new(
                "yTicks",
                yTicks,
                default=0,
                min=0,
                max=99)

            self$.addOption(private$..aVar)
            self$.addOption(private$..group)
            self$.addOption(private$..facet)
            self$.addOption(private$..histtype)
            self$.addOption(private$..normalCurve)
            self$.addOption(private$..density)
            self$.addOption(private$..dashedDensity)
            self$.addOption(private$..binWidth)
            self$.addOption(private$..binBoundary)
            self$.addOption(private$..densityOpacity)
            self$.addOption(private$..densityLineSize)
            self$.addOption(private$..normalCurveLineSize)
            self$.addOption(private$..fillColor)
            self$.addOption(private$..borderColor)
            self$.addOption(private$..grouping)
            self$.addOption(private$..groupingN)
            self$.addOption(private$..colorPalette)
            self$.addOption(private$..usePalette)
            self$.addOption(private$..titleText)
            self$.addOption(private$..titleFontFace)
            self$.addOption(private$..titleFontSize)
            self$.addOption(private$..titleAlign)
            self$.addOption(private$..subtitleText)
            self$.addOption(private$..subtitleFontFace)
            self$.addOption(private$..subtitleFontSize)
            self$.addOption(private$..subtitleAlign)
            self$.addOption(private$..captionText)
            self$.addOption(private$..captionFontFace)
            self$.addOption(private$..captionFontSize)
            self$.addOption(private$..captionAlign)
            self$.addOption(private$..legendText)
            self$.addOption(private$..legendFontSize)
            self$.addOption(private$..legendPosition)
            self$.addOption(private$..xAxisText)
            self$.addOption(private$..xAxisFontSize)
            self$.addOption(private$..xAxisPosition)
            self$.addOption(private$..yAxisText)
            self$.addOption(private$..yAxisFontSize)
            self$.addOption(private$..yAxisPosition)
            self$.addOption(private$..facetBy)
            self$.addOption(private$..facetNumber)
            self$.addOption(private$..yAxisLabelFontSize)
            self$.addOption(private$..yAxisLabelRotation)
            self$.addOption(private$..yAxisRangeType)
            self$.addOption(private$..yAxisRangeMin)
            self$.addOption(private$..yAxisRangeMax)
            self$.addOption(private$..xAxisLabelFontSize)
            self$.addOption(private$..xAxisLabelRotation)
            self$.addOption(private$..xAxisRangeType)
            self$.addOption(private$..xAxisRangeMin)
            self$.addOption(private$..xAxisRangeMax)
            self$.addOption(private$..xTicks)
            self$.addOption(private$..yTicks)
        }),
    active = list(
        aVar = function() private$..aVar$value,
        group = function() private$..group$value,
        facet = function() private$..facet$value,
        histtype = function() private$..histtype$value,
        normalCurve = function() private$..normalCurve$value,
        density = function() private$..density$value,
        dashedDensity = function() private$..dashedDensity$value,
        binWidth = function() private$..binWidth$value,
        binBoundary = function() private$..binBoundary$value,
        densityOpacity = function() private$..densityOpacity$value,
        densityLineSize = function() private$..densityLineSize$value,
        normalCurveLineSize = function() private$..normalCurveLineSize$value,
        fillColor = function() private$..fillColor$value,
        borderColor = function() private$..borderColor$value,
        grouping = function() private$..grouping$value,
        groupingN = function() private$..groupingN$value,
        colorPalette = function() private$..colorPalette$value,
        usePalette = function() private$..usePalette$value,
        titleText = function() private$..titleText$value,
        titleFontFace = function() private$..titleFontFace$value,
        titleFontSize = function() private$..titleFontSize$value,
        titleAlign = function() private$..titleAlign$value,
        subtitleText = function() private$..subtitleText$value,
        subtitleFontFace = function() private$..subtitleFontFace$value,
        subtitleFontSize = function() private$..subtitleFontSize$value,
        subtitleAlign = function() private$..subtitleAlign$value,
        captionText = function() private$..captionText$value,
        captionFontFace = function() private$..captionFontFace$value,
        captionFontSize = function() private$..captionFontSize$value,
        captionAlign = function() private$..captionAlign$value,
        legendText = function() private$..legendText$value,
        legendFontSize = function() private$..legendFontSize$value,
        legendPosition = function() private$..legendPosition$value,
        xAxisText = function() private$..xAxisText$value,
        xAxisFontSize = function() private$..xAxisFontSize$value,
        xAxisPosition = function() private$..xAxisPosition$value,
        yAxisText = function() private$..yAxisText$value,
        yAxisFontSize = function() private$..yAxisFontSize$value,
        yAxisPosition = function() private$..yAxisPosition$value,
        facetBy = function() private$..facetBy$value,
        facetNumber = function() private$..facetNumber$value,
        yAxisLabelFontSize = function() private$..yAxisLabelFontSize$value,
        yAxisLabelRotation = function() private$..yAxisLabelRotation$value,
        yAxisRangeType = function() private$..yAxisRangeType$value,
        yAxisRangeMin = function() private$..yAxisRangeMin$value,
        yAxisRangeMax = function() private$..yAxisRangeMax$value,
        xAxisLabelFontSize = function() private$..xAxisLabelFontSize$value,
        xAxisLabelRotation = function() private$..xAxisLabelRotation$value,
        xAxisRangeType = function() private$..xAxisRangeType$value,
        xAxisRangeMin = function() private$..xAxisRangeMin$value,
        xAxisRangeMax = function() private$..xAxisRangeMax$value,
        xTicks = function() private$..xTicks$value,
        yTicks = function() private$..yTicks$value),
    private = list(
        ..aVar = NA,
        ..group = NA,
        ..facet = NA,
        ..histtype = NA,
        ..normalCurve = NA,
        ..density = NA,
        ..dashedDensity = NA,
        ..binWidth = NA,
        ..binBoundary = NA,
        ..densityOpacity = NA,
        ..densityLineSize = NA,
        ..normalCurveLineSize = NA,
        ..fillColor = NA,
        ..borderColor = NA,
        ..grouping = NA,
        ..groupingN = NA,
        ..colorPalette = NA,
        ..usePalette = NA,
        ..titleText = NA,
        ..titleFontFace = NA,
        ..titleFontSize = NA,
        ..titleAlign = NA,
        ..subtitleText = NA,
        ..subtitleFontFace = NA,
        ..subtitleFontSize = NA,
        ..subtitleAlign = NA,
        ..captionText = NA,
        ..captionFontFace = NA,
        ..captionFontSize = NA,
        ..captionAlign = NA,
        ..legendText = NA,
        ..legendFontSize = NA,
        ..legendPosition = NA,
        ..xAxisText = NA,
        ..xAxisFontSize = NA,
        ..xAxisPosition = NA,
        ..yAxisText = NA,
        ..yAxisFontSize = NA,
        ..yAxisPosition = NA,
        ..facetBy = NA,
        ..facetNumber = NA,
        ..yAxisLabelFontSize = NA,
        ..yAxisLabelRotation = NA,
        ..yAxisRangeType = NA,
        ..yAxisRangeMin = NA,
        ..yAxisRangeMax = NA,
        ..xAxisLabelFontSize = NA,
        ..xAxisLabelRotation = NA,
        ..xAxisRangeType = NA,
        ..xAxisRangeMin = NA,
        ..xAxisRangeMax = NA,
        ..xTicks = NA,
        ..yTicks = NA)
)

histogramResults <- if (requireNamespace("jmvcore", quietly=TRUE)) R6::R6Class(
    "histogramResults",
    inherit = jmvcore::Group,
    active = list(
        plot = function() private$.items[["plot"]]),
    private = list(),
    public=list(
        initialize=function(options) {
            super$initialize(
                options=options,
                name="",
                title="Histogram")
            self$add(jmvcore::Image$new(
                options=options,
                name="plot",
                title="",
                width=600,
                height=400,
                renderFun=".plot"))}))

histogramBase <- if (requireNamespace("jmvcore", quietly=TRUE)) R6::R6Class(
    "histogramBase",
    inherit = jmvcore::Analysis,
    public = list(
        initialize = function(options, data=NULL, datasetId="", analysisId="", revision=0) {
            super$initialize(
                package = "vijPlots",
                name = "histogram",
                version = c(1,0,0),
                options = options,
                results = histogramResults$new(options=options),
                data = data,
                datasetId = datasetId,
                analysisId = analysisId,
                revision = revision,
                pause = NULL,
                completeWhenFilled = FALSE,
                requiresMissings = FALSE,
                weightsSupport = 'auto')
        }))

#' Histogram
#'
#' 
#' @param data .
#' @param aVar .
#' @param group .
#' @param facet .
#' @param histtype .
#' @param normalCurve .
#' @param density .
#' @param dashedDensity .
#' @param binWidth .
#' @param binBoundary .
#' @param densityOpacity .
#' @param densityLineSize .
#' @param normalCurveLineSize .
#' @param fillColor .
#' @param borderColor .
#' @param grouping .
#' @param groupingN .
#' @param colorPalette .
#' @param usePalette .
#' @param titleText .
#' @param titleFontFace .
#' @param titleFontSize .
#' @param titleAlign .
#' @param subtitleText .
#' @param subtitleFontFace .
#' @param subtitleFontSize .
#' @param subtitleAlign .
#' @param captionText .
#' @param captionFontFace .
#' @param captionFontSize .
#' @param captionAlign .
#' @param legendText .
#' @param legendFontSize .
#' @param legendPosition .
#' @param xAxisText .
#' @param xAxisFontSize .
#' @param xAxisPosition .
#' @param yAxisText .
#' @param yAxisFontSize .
#' @param yAxisPosition .
#' @param facetBy .
#' @param facetNumber .
#' @param yAxisLabelFontSize .
#' @param yAxisLabelRotation .
#' @param yAxisRangeType .
#' @param yAxisRangeMin .
#' @param yAxisRangeMax .
#' @param xAxisLabelFontSize .
#' @param xAxisLabelRotation .
#' @param xAxisRangeType .
#' @param xAxisRangeMin .
#' @param xAxisRangeMax .
#' @param xTicks .
#' @param yTicks .
#' @return A results object containing:
#' \tabular{llllll}{
#'   \code{results$plot} \tab \tab \tab \tab \tab an image \cr
#' }
#'
#' @export
histogram <- function(
    data,
    aVar = NULL,
    group,
    facet,
    histtype = "count",
    normalCurve = FALSE,
    density = FALSE,
    dashedDensity = FALSE,
    binWidth = 0,
    binBoundary = 0,
    densityOpacity = 0.2,
    densityLineSize = 0.5,
    normalCurveLineSize = 1,
    fillColor = "#A6C4F1",
    borderColor = "black",
    grouping = "none",
    groupingN = "stack",
    colorPalette = "jmv",
    usePalette = "forFilling",
    titleText,
    titleFontFace = "bold",
    titleFontSize = "14",
    titleAlign = "0.5",
    subtitleText,
    subtitleFontFace = "plain",
    subtitleFontSize = "12",
    subtitleAlign = "0.5",
    captionText,
    captionFontFace = "italic",
    captionFontSize = "10",
    captionAlign = "1",
    legendText,
    legendFontSize = "14",
    legendPosition = "right",
    xAxisText,
    xAxisFontSize = "16",
    xAxisPosition = "0.5",
    yAxisText,
    yAxisFontSize = "16",
    yAxisPosition = "0.5",
    facetBy = "column",
    facetNumber = 1,
    yAxisLabelFontSize = 12,
    yAxisLabelRotation = 0,
    yAxisRangeType = "auto",
    yAxisRangeMin = 0,
    yAxisRangeMax = 10,
    xAxisLabelFontSize = 12,
    xAxisLabelRotation = 0,
    xAxisRangeType = "auto",
    xAxisRangeMin = 0,
    xAxisRangeMax = 10,
    xTicks = 0,
    yTicks = 0) {

    if ( ! requireNamespace("jmvcore", quietly=TRUE))
        stop("histogram requires jmvcore to be installed (restart may be required)")

    if ( ! missing(aVar)) aVar <- jmvcore::resolveQuo(jmvcore::enquo(aVar))
    if ( ! missing(group)) group <- jmvcore::resolveQuo(jmvcore::enquo(group))
    if ( ! missing(facet)) facet <- jmvcore::resolveQuo(jmvcore::enquo(facet))
    if (missing(data))
        data <- jmvcore::marshalData(
            parent.frame(),
            `if`( ! missing(aVar), aVar, NULL),
            `if`( ! missing(group), group, NULL),
            `if`( ! missing(facet), facet, NULL))

    for (v in group) if (v %in% names(data)) data[[v]] <- as.factor(data[[v]])
    for (v in facet) if (v %in% names(data)) data[[v]] <- as.factor(data[[v]])

    options <- histogramOptions$new(
        aVar = aVar,
        group = group,
        facet = facet,
        histtype = histtype,
        normalCurve = normalCurve,
        density = density,
        dashedDensity = dashedDensity,
        binWidth = binWidth,
        binBoundary = binBoundary,
        densityOpacity = densityOpacity,
        densityLineSize = densityLineSize,
        normalCurveLineSize = normalCurveLineSize,
        fillColor = fillColor,
        borderColor = borderColor,
        grouping = grouping,
        groupingN = groupingN,
        colorPalette = colorPalette,
        usePalette = usePalette,
        titleText = titleText,
        titleFontFace = titleFontFace,
        titleFontSize = titleFontSize,
        titleAlign = titleAlign,
        subtitleText = subtitleText,
        subtitleFontFace = subtitleFontFace,
        subtitleFontSize = subtitleFontSize,
        subtitleAlign = subtitleAlign,
        captionText = captionText,
        captionFontFace = captionFontFace,
        captionFontSize = captionFontSize,
        captionAlign = captionAlign,
        legendText = legendText,
        legendFontSize = legendFontSize,
        legendPosition = legendPosition,
        xAxisText = xAxisText,
        xAxisFontSize = xAxisFontSize,
        xAxisPosition = xAxisPosition,
        yAxisText = yAxisText,
        yAxisFontSize = yAxisFontSize,
        yAxisPosition = yAxisPosition,
        facetBy = facetBy,
        facetNumber = facetNumber,
        yAxisLabelFontSize = yAxisLabelFontSize,
        yAxisLabelRotation = yAxisLabelRotation,
        yAxisRangeType = yAxisRangeType,
        yAxisRangeMin = yAxisRangeMin,
        yAxisRangeMax = yAxisRangeMax,
        xAxisLabelFontSize = xAxisLabelFontSize,
        xAxisLabelRotation = xAxisLabelRotation,
        xAxisRangeType = xAxisRangeType,
        xAxisRangeMin = xAxisRangeMin,
        xAxisRangeMax = xAxisRangeMax,
        xTicks = xTicks,
        yTicks = yTicks)

    analysis <- histogramClass$new(
        options = options,
        data = data)

    analysis$run()

    analysis$results
}

