
# This file is automatically generated, you probably don't want to edit this

likertplotOptions <- if (requireNamespace("jmvcore", quietly=TRUE)) R6::R6Class(
    "likertplotOptions",
    inherit = jmvcore::Options,
    public = list(
        initialize = function(
            liks = NULL,
            group = NULL,
            type = "centered",
            sorting = "none",
            groupBy = "variable",
            addLabels = TRUE,
            hideLabelsBelow = FALSE,
            addTotals = TRUE,
            addMedianLine = TRUE,
            reverseLikert = FALSE,
            toInteger = FALSE,
            tidyUp = FALSE,
            ignoreNA = TRUE,
            textSize = NULL,
            labelSize = 11,
            groupSize = 12,
            accuracy = "1",
            vLabelWrap = "20",
            hLabelWrap = "30",
            plotColor = "BrBG",
            labelColor = "auto",
            frequencyTable = FALSE,
            showMedian = FALSE,
            showMean = FALSE,
            frequencies = "counts",
            showMannU = FALSE,
            showKW = FALSE,
            showPostHoc = FALSE,
            postHoc = "dunn",
            pValue = "none",
            adjustMethod = "holm",
            descAsVarName = FALSE,
            titleText = NULL,
            titleFontFace = "bold",
            titleFontSize = "14",
            titleAlign = "0.5",
            subtitleText = NULL,
            subtitleFontFace = "plain",
            subtitleFontSize = "12",
            subtitleAlign = "0.5",
            captionText = NULL,
            captionFontFace = "italic",
            captionFontSize = "10",
            captionAlign = "1",
            legendText = NULL,
            legendFontSize = "11",
            legendPosition = "bottom",
            yAxisLabelFontSize = 11,
            yAxisLabelRotation = 0,
            xAxisLabelFontSize = 11,
            xAxisLabelRotation = 0, ...) {

            super$initialize(
                package="vijPlots",
                name="likertplot",
                requiresData=TRUE,
                ...)

            private$..liks <- jmvcore::OptionVariables$new(
                "liks",
                liks,
                required=TRUE,
                suggested=list(
                    "ordinal"),
                permitted=list(
                    "factor",
                    "numeric"))
            private$..group <- jmvcore::OptionVariable$new(
                "group",
                group,
                suggested=list(
                    "nominal"),
                permitted=list(
                    "factor"))
            private$..type <- jmvcore::OptionList$new(
                "type",
                type,
                options=list(
                    "centered",
                    "stacked"),
                default="centered")
            private$..sorting <- jmvcore::OptionList$new(
                "sorting",
                sorting,
                options=list(
                    "none",
                    "ascending",
                    "descending"),
                default="none")
            private$..groupBy <- jmvcore::OptionList$new(
                "groupBy",
                groupBy,
                options=list(
                    "variable",
                    "group"),
                default="variable")
            private$..addLabels <- jmvcore::OptionBool$new(
                "addLabels",
                addLabels,
                default=TRUE)
            private$..hideLabelsBelow <- jmvcore::OptionBool$new(
                "hideLabelsBelow",
                hideLabelsBelow,
                default=FALSE)
            private$..addTotals <- jmvcore::OptionBool$new(
                "addTotals",
                addTotals,
                default=TRUE)
            private$..addMedianLine <- jmvcore::OptionBool$new(
                "addMedianLine",
                addMedianLine,
                default=TRUE)
            private$..reverseLikert <- jmvcore::OptionBool$new(
                "reverseLikert",
                reverseLikert,
                default=FALSE)
            private$..toInteger <- jmvcore::OptionBool$new(
                "toInteger",
                toInteger,
                default=FALSE)
            private$..tidyUp <- jmvcore::OptionBool$new(
                "tidyUp",
                tidyUp,
                default=FALSE)
            private$..ignoreNA <- jmvcore::OptionBool$new(
                "ignoreNA",
                ignoreNA,
                default=TRUE)
            private$..textSize <- jmvcore::OptionNumber$new(
                "textSize",
                textSize,
                hidden=TRUE)
            private$..labelSize <- jmvcore::OptionNumber$new(
                "labelSize",
                labelSize,
                min=6,
                max=24,
                default=11)
            private$..groupSize <- jmvcore::OptionNumber$new(
                "groupSize",
                groupSize,
                min=6,
                max=24,
                default=12)
            private$..accuracy <- jmvcore::OptionList$new(
                "accuracy",
                accuracy,
                options=list(
                    "1",
                    "0.1"),
                default="1")
            private$..vLabelWrap <- jmvcore::OptionList$new(
                "vLabelWrap",
                vLabelWrap,
                options=list(
                    "10",
                    "15",
                    "20",
                    "25",
                    "30",
                    "35"),
                default="20")
            private$..hLabelWrap <- jmvcore::OptionList$new(
                "hLabelWrap",
                hLabelWrap,
                options=list(
                    "10",
                    "20",
                    "30",
                    "40",
                    "60",
                    "80"),
                default="30")
            private$..plotColor <- jmvcore::OptionList$new(
                "plotColor",
                plotColor,
                options=list(
                    "BrBG",
                    "PiYG",
                    "PRGn",
                    "PuOr",
                    "RdBu",
                    "RdGy",
                    "RdYlBu",
                    "RdYlGn",
                    "Spectral"),
                default="BrBG")
            private$..labelColor <- jmvcore::OptionList$new(
                "labelColor",
                labelColor,
                options=list(
                    "auto",
                    "black",
                    "darkgrey",
                    "white"),
                default="auto")
            private$..frequencyTable <- jmvcore::OptionBool$new(
                "frequencyTable",
                frequencyTable,
                default=FALSE)
            private$..showMedian <- jmvcore::OptionBool$new(
                "showMedian",
                showMedian,
                default=FALSE)
            private$..showMean <- jmvcore::OptionBool$new(
                "showMean",
                showMean,
                default=FALSE)
            private$..frequencies <- jmvcore::OptionList$new(
                "frequencies",
                frequencies,
                options=list(
                    "counts",
                    "percentages"),
                default="counts")
            private$..showMannU <- jmvcore::OptionBool$new(
                "showMannU",
                showMannU,
                default=FALSE)
            private$..showKW <- jmvcore::OptionBool$new(
                "showKW",
                showKW,
                default=FALSE)
            private$..showPostHoc <- jmvcore::OptionBool$new(
                "showPostHoc",
                showPostHoc,
                default=FALSE)
            private$..postHoc <- jmvcore::OptionList$new(
                "postHoc",
                postHoc,
                options=list(
                    "conover",
                    "dunn",
                    "dscf"),
                default="dunn")
            private$..pValue <- jmvcore::OptionList$new(
                "pValue",
                pValue,
                options=list(
                    "none",
                    "group",
                    "overall"),
                default="none")
            private$..adjustMethod <- jmvcore::OptionList$new(
                "adjustMethod",
                adjustMethod,
                options=list(
                    "bonferroni",
                    "holm",
                    "hochberg",
                    "hommel",
                    "BH",
                    "BY"),
                default="holm")
            private$..descAsVarName <- jmvcore::OptionBool$new(
                "descAsVarName",
                descAsVarName,
                default=FALSE)
            private$..titleText <- jmvcore::OptionString$new(
                "titleText",
                titleText)
            private$..titleFontFace <- jmvcore::OptionList$new(
                "titleFontFace",
                titleFontFace,
                options=list(
                    "plain",
                    "bold",
                    "italic",
                    "bold.italic"),
                default="bold")
            private$..titleFontSize <- jmvcore::OptionList$new(
                "titleFontSize",
                titleFontSize,
                options=list(
                    "12",
                    "14",
                    "16",
                    "18",
                    "20",
                    "22",
                    "24"),
                default="14")
            private$..titleAlign <- jmvcore::OptionList$new(
                "titleAlign",
                titleAlign,
                options=list(
                    "0",
                    "0.5",
                    "1"),
                default="0.5")
            private$..subtitleText <- jmvcore::OptionString$new(
                "subtitleText",
                subtitleText)
            private$..subtitleFontFace <- jmvcore::OptionList$new(
                "subtitleFontFace",
                subtitleFontFace,
                options=list(
                    "plain",
                    "bold",
                    "italic",
                    "bold.italic"),
                default="plain")
            private$..subtitleFontSize <- jmvcore::OptionList$new(
                "subtitleFontSize",
                subtitleFontSize,
                options=list(
                    "10",
                    "12",
                    "14",
                    "16",
                    "18",
                    "20",
                    "22"),
                default="12")
            private$..subtitleAlign <- jmvcore::OptionList$new(
                "subtitleAlign",
                subtitleAlign,
                options=list(
                    "0",
                    "0.5",
                    "1"),
                default="0.5")
            private$..captionText <- jmvcore::OptionString$new(
                "captionText",
                captionText)
            private$..captionFontFace <- jmvcore::OptionList$new(
                "captionFontFace",
                captionFontFace,
                options=list(
                    "plain",
                    "bold",
                    "italic",
                    "bold.italic"),
                default="italic")
            private$..captionFontSize <- jmvcore::OptionList$new(
                "captionFontSize",
                captionFontSize,
                options=list(
                    "8",
                    "10",
                    "12",
                    "14",
                    "16",
                    "18",
                    "20"),
                default="10")
            private$..captionAlign <- jmvcore::OptionList$new(
                "captionAlign",
                captionAlign,
                options=list(
                    "0",
                    "0.5",
                    "1"),
                default="1")
            private$..legendText <- jmvcore::OptionString$new(
                "legendText",
                legendText)
            private$..legendFontSize <- jmvcore::OptionList$new(
                "legendFontSize",
                legendFontSize,
                options=list(
                    "8",
                    "9",
                    "10",
                    "11",
                    "12",
                    "13",
                    "14"),
                default="11")
            private$..legendPosition <- jmvcore::OptionList$new(
                "legendPosition",
                legendPosition,
                options=list(
                    "right",
                    "bottom",
                    "left",
                    "top"),
                default="bottom")
            private$..yAxisLabelFontSize <- jmvcore::OptionNumber$new(
                "yAxisLabelFontSize",
                yAxisLabelFontSize,
                default=11)
            private$..yAxisLabelRotation <- jmvcore::OptionNumber$new(
                "yAxisLabelRotation",
                yAxisLabelRotation,
                default=0,
                min=0,
                max=360)
            private$..xAxisLabelFontSize <- jmvcore::OptionNumber$new(
                "xAxisLabelFontSize",
                xAxisLabelFontSize,
                default=11)
            private$..xAxisLabelRotation <- jmvcore::OptionNumber$new(
                "xAxisLabelRotation",
                xAxisLabelRotation,
                default=0,
                min=0,
                max=360)

            self$.addOption(private$..liks)
            self$.addOption(private$..group)
            self$.addOption(private$..type)
            self$.addOption(private$..sorting)
            self$.addOption(private$..groupBy)
            self$.addOption(private$..addLabels)
            self$.addOption(private$..hideLabelsBelow)
            self$.addOption(private$..addTotals)
            self$.addOption(private$..addMedianLine)
            self$.addOption(private$..reverseLikert)
            self$.addOption(private$..toInteger)
            self$.addOption(private$..tidyUp)
            self$.addOption(private$..ignoreNA)
            self$.addOption(private$..textSize)
            self$.addOption(private$..labelSize)
            self$.addOption(private$..groupSize)
            self$.addOption(private$..accuracy)
            self$.addOption(private$..vLabelWrap)
            self$.addOption(private$..hLabelWrap)
            self$.addOption(private$..plotColor)
            self$.addOption(private$..labelColor)
            self$.addOption(private$..frequencyTable)
            self$.addOption(private$..showMedian)
            self$.addOption(private$..showMean)
            self$.addOption(private$..frequencies)
            self$.addOption(private$..showMannU)
            self$.addOption(private$..showKW)
            self$.addOption(private$..showPostHoc)
            self$.addOption(private$..postHoc)
            self$.addOption(private$..pValue)
            self$.addOption(private$..adjustMethod)
            self$.addOption(private$..descAsVarName)
            self$.addOption(private$..titleText)
            self$.addOption(private$..titleFontFace)
            self$.addOption(private$..titleFontSize)
            self$.addOption(private$..titleAlign)
            self$.addOption(private$..subtitleText)
            self$.addOption(private$..subtitleFontFace)
            self$.addOption(private$..subtitleFontSize)
            self$.addOption(private$..subtitleAlign)
            self$.addOption(private$..captionText)
            self$.addOption(private$..captionFontFace)
            self$.addOption(private$..captionFontSize)
            self$.addOption(private$..captionAlign)
            self$.addOption(private$..legendText)
            self$.addOption(private$..legendFontSize)
            self$.addOption(private$..legendPosition)
            self$.addOption(private$..yAxisLabelFontSize)
            self$.addOption(private$..yAxisLabelRotation)
            self$.addOption(private$..xAxisLabelFontSize)
            self$.addOption(private$..xAxisLabelRotation)
        }),
    active = list(
        liks = function() private$..liks$value,
        group = function() private$..group$value,
        type = function() private$..type$value,
        sorting = function() private$..sorting$value,
        groupBy = function() private$..groupBy$value,
        addLabels = function() private$..addLabels$value,
        hideLabelsBelow = function() private$..hideLabelsBelow$value,
        addTotals = function() private$..addTotals$value,
        addMedianLine = function() private$..addMedianLine$value,
        reverseLikert = function() private$..reverseLikert$value,
        toInteger = function() private$..toInteger$value,
        tidyUp = function() private$..tidyUp$value,
        ignoreNA = function() private$..ignoreNA$value,
        textSize = function() private$..textSize$value,
        labelSize = function() private$..labelSize$value,
        groupSize = function() private$..groupSize$value,
        accuracy = function() private$..accuracy$value,
        vLabelWrap = function() private$..vLabelWrap$value,
        hLabelWrap = function() private$..hLabelWrap$value,
        plotColor = function() private$..plotColor$value,
        labelColor = function() private$..labelColor$value,
        frequencyTable = function() private$..frequencyTable$value,
        showMedian = function() private$..showMedian$value,
        showMean = function() private$..showMean$value,
        frequencies = function() private$..frequencies$value,
        showMannU = function() private$..showMannU$value,
        showKW = function() private$..showKW$value,
        showPostHoc = function() private$..showPostHoc$value,
        postHoc = function() private$..postHoc$value,
        pValue = function() private$..pValue$value,
        adjustMethod = function() private$..adjustMethod$value,
        descAsVarName = function() private$..descAsVarName$value,
        titleText = function() private$..titleText$value,
        titleFontFace = function() private$..titleFontFace$value,
        titleFontSize = function() private$..titleFontSize$value,
        titleAlign = function() private$..titleAlign$value,
        subtitleText = function() private$..subtitleText$value,
        subtitleFontFace = function() private$..subtitleFontFace$value,
        subtitleFontSize = function() private$..subtitleFontSize$value,
        subtitleAlign = function() private$..subtitleAlign$value,
        captionText = function() private$..captionText$value,
        captionFontFace = function() private$..captionFontFace$value,
        captionFontSize = function() private$..captionFontSize$value,
        captionAlign = function() private$..captionAlign$value,
        legendText = function() private$..legendText$value,
        legendFontSize = function() private$..legendFontSize$value,
        legendPosition = function() private$..legendPosition$value,
        yAxisLabelFontSize = function() private$..yAxisLabelFontSize$value,
        yAxisLabelRotation = function() private$..yAxisLabelRotation$value,
        xAxisLabelFontSize = function() private$..xAxisLabelFontSize$value,
        xAxisLabelRotation = function() private$..xAxisLabelRotation$value),
    private = list(
        ..liks = NA,
        ..group = NA,
        ..type = NA,
        ..sorting = NA,
        ..groupBy = NA,
        ..addLabels = NA,
        ..hideLabelsBelow = NA,
        ..addTotals = NA,
        ..addMedianLine = NA,
        ..reverseLikert = NA,
        ..toInteger = NA,
        ..tidyUp = NA,
        ..ignoreNA = NA,
        ..textSize = NA,
        ..labelSize = NA,
        ..groupSize = NA,
        ..accuracy = NA,
        ..vLabelWrap = NA,
        ..hLabelWrap = NA,
        ..plotColor = NA,
        ..labelColor = NA,
        ..frequencyTable = NA,
        ..showMedian = NA,
        ..showMean = NA,
        ..frequencies = NA,
        ..showMannU = NA,
        ..showKW = NA,
        ..showPostHoc = NA,
        ..postHoc = NA,
        ..pValue = NA,
        ..adjustMethod = NA,
        ..descAsVarName = NA,
        ..titleText = NA,
        ..titleFontFace = NA,
        ..titleFontSize = NA,
        ..titleAlign = NA,
        ..subtitleText = NA,
        ..subtitleFontFace = NA,
        ..subtitleFontSize = NA,
        ..subtitleAlign = NA,
        ..captionText = NA,
        ..captionFontFace = NA,
        ..captionFontSize = NA,
        ..captionAlign = NA,
        ..legendText = NA,
        ..legendFontSize = NA,
        ..legendPosition = NA,
        ..yAxisLabelFontSize = NA,
        ..yAxisLabelRotation = NA,
        ..xAxisLabelFontSize = NA,
        ..xAxisLabelRotation = NA)
)

likertplotResults <- if (requireNamespace("jmvcore", quietly=TRUE)) R6::R6Class(
    "likertplotResults",
    inherit = jmvcore::Group,
    active = list(
        frequencies = function() private$.items[["frequencies"]],
        comp = function() private$.items[["comp"]],
        plot = function() private$.items[["plot"]]),
    private = list(),
    public=list(
        initialize=function(options) {
            super$initialize(
                options=options,
                name="",
                title="Likert Plot",
                refs=list(
                    "ggplots"))
            self$add(jmvcore::Table$new(
                options=options,
                name="frequencies",
                title="Frequency Table",
                visible="(frequencyTable)",
                rows=0,
                columns=list(
                    list(
                        `name`="ques", 
                        `title`="Questions", 
                        `type`="text")),
                clearWith=list(
                    "liks",
                    "group",
                    "type",
                    "frequencies",
                    "showMean",
                    "frequencyTable",
                    "toInteger",
                    "tidyUp",
                    "descAsVarName")))
            self$add(R6::R6Class(
                inherit = jmvcore::Group,
                active = list(
                    uTestTable = function() private$.items[["uTestTable"]],
                    kwTable = function() private$.items[["kwTable"]],
                    pwTable = function() private$.items[["pwTable"]]),
                private = list(),
                public=list(
                    initialize=function(options) {
                        super$initialize(
                            options=options,
                            name="comp",
                            title="Comparison Tests")
                        self$add(jmvcore::Table$new(
                            options=options,
                            name="uTestTable",
                            title="Mann-Whitney U Tests",
                            rows="(liks)",
                            visible="(showMannU)",
                            columns=list(
                                list(
                                    `name`="ques", 
                                    `title`="Questions", 
                                    `type`="text", 
                                    `content`="($key)"),
                                list(
                                    `name`="statistic", 
                                    `title`="U", 
                                    `type`="number"),
                                list(
                                    `name`="p.value", 
                                    `title`="p", 
                                    `type`="number", 
                                    `format`="zto,pvalue")),
                            clearWith=list(
                                "liks",
                                "group",
                                "adjustMethod",
                                "pValue",
                                "descAsVarName")))
                        self$add(jmvcore::Table$new(
                            options=options,
                            name="kwTable",
                            title="Kruskal-Wallis Tests",
                            rows="(liks)",
                            visible="(showKW)",
                            columns=list(
                                list(
                                    `name`="ques", 
                                    `title`="Questions", 
                                    `type`="text", 
                                    `content`="($key)"),
                                list(
                                    `name`="statistic", 
                                    `title`="\u03C7\u00B2", 
                                    `type`="number"),
                                list(
                                    `name`="parameter", 
                                    `title`="df", 
                                    `type`="integer"),
                                list(
                                    `name`="p.value", 
                                    `title`="p", 
                                    `type`="number", 
                                    `format`="zto,pvalue")),
                            clearWith=list(
                                "liks",
                                "group",
                                "adjustMethod",
                                "pValue",
                                "descAsVarName")))
                        self$add(jmvcore::Table$new(
                            options=options,
                            name="pwTable",
                            title="Pairwise Comparisons",
                            rows=0,
                            visible="(showPostHoc)",
                            columns=list(
                                list(
                                    `name`="group1", 
                                    `title`="", 
                                    `type`="text"),
                                list(
                                    `name`="group2", 
                                    `title`="", 
                                    `type`="text")),
                            clearWith=list(
                                "liks",
                                "group",
                                "adjustMethod",
                                "postHoc",
                                "pValue",
                                "descAsVarName")))}))$new(options=options))
            self$add(jmvcore::Image$new(
                options=options,
                name="plot",
                title="Plot",
                width=600,
                height=400,
                renderFun=".plot",
                clearWith=list(
                    "liks",
                    "group",
                    "groupBy",
                    "type",
                    "sorting",
                    "addLabels",
                    "hideLabelsBelow",
                    "addTotals",
                    "addMedianLine",
                    "reverseLikert",
                    "toInteger",
                    "tidyUp",
                    "ignoreNA",
                    "labelSize",
                    "groupSize",
                    "accuracy",
                    "plotColor",
                    "labelColor",
                    "vLabelWrap",
                    "hLabelWrap",
                    "descAsVarName",
                    "titleText",
                    "subtitleText",
                    "captionText",
                    "titleFontFace",
                    "subtitleFontFace",
                    "captionFontFace",
                    "titleFontSize",
                    "subtitleFontSize",
                    "captionFontSize",
                    "titleAlign",
                    "subtitleAlign",
                    "captionAlign",
                    "legendText",
                    "legendFontSize",
                    "legendPosition",
                    "yAxisLabelFontSize",
                    "yAxisLabelRotation",
                    "xAxisLabelFontSize",
                    "xAxisLabelRotation")))}))

likertplotBase <- if (requireNamespace("jmvcore", quietly=TRUE)) R6::R6Class(
    "likertplotBase",
    inherit = jmvcore::Analysis,
    public = list(
        initialize = function(options, data=NULL, datasetId="", analysisId="", revision=0) {
            super$initialize(
                package = "vijPlots",
                name = "likertplot",
                version = c(1,0,0),
                options = options,
                results = likertplotResults$new(options=options),
                data = data,
                datasetId = datasetId,
                analysisId = analysisId,
                revision = revision,
                pause = NULL,
                completeWhenFilled = FALSE,
                requiresMissings = FALSE,
                weightsSupport = 'auto')
        }))

#' Likert Plot
#'
#' 
#' @param data .
#' @param liks .
#' @param group .
#' @param type .
#' @param sorting .
#' @param groupBy .
#' @param addLabels .
#' @param hideLabelsBelow .
#' @param addTotals .
#' @param addMedianLine .
#' @param reverseLikert .
#' @param toInteger .
#' @param tidyUp .
#' @param ignoreNA .
#' @param textSize .
#' @param labelSize .
#' @param groupSize .
#' @param accuracy .
#' @param vLabelWrap .
#' @param hLabelWrap .
#' @param plotColor .
#' @param labelColor .
#' @param frequencyTable .
#' @param showMedian .
#' @param showMean .
#' @param frequencies .
#' @param showMannU .
#' @param showKW .
#' @param showPostHoc .
#' @param postHoc .
#' @param pValue .
#' @param adjustMethod .
#' @param descAsVarName .
#' @param titleText .
#' @param titleFontFace .
#' @param titleFontSize .
#' @param titleAlign .
#' @param subtitleText .
#' @param subtitleFontFace .
#' @param subtitleFontSize .
#' @param subtitleAlign .
#' @param captionText .
#' @param captionFontFace .
#' @param captionFontSize .
#' @param captionAlign .
#' @param legendText .
#' @param legendFontSize .
#' @param legendPosition .
#' @param yAxisLabelFontSize .
#' @param yAxisLabelRotation .
#' @param xAxisLabelFontSize .
#' @param xAxisLabelRotation .
#' @return A results object containing:
#' \tabular{llllll}{
#'   \code{results$frequencies} \tab \tab \tab \tab \tab a table \cr
#'   \code{results$comp$uTestTable} \tab \tab \tab \tab \tab a table \cr
#'   \code{results$comp$kwTable} \tab \tab \tab \tab \tab a table \cr
#'   \code{results$comp$pwTable} \tab \tab \tab \tab \tab a table \cr
#'   \code{results$plot} \tab \tab \tab \tab \tab an image \cr
#' }
#'
#' Tables can be converted to data frames with \code{asDF} or \code{\link{as.data.frame}}. For example:
#'
#' \code{results$frequencies$asDF}
#'
#' \code{as.data.frame(results$frequencies)}
#'
#' @export
likertplot <- function(
    data,
    liks,
    group,
    type = "centered",
    sorting = "none",
    groupBy = "variable",
    addLabels = TRUE,
    hideLabelsBelow = FALSE,
    addTotals = TRUE,
    addMedianLine = TRUE,
    reverseLikert = FALSE,
    toInteger = FALSE,
    tidyUp = FALSE,
    ignoreNA = TRUE,
    textSize,
    labelSize = 11,
    groupSize = 12,
    accuracy = "1",
    vLabelWrap = "20",
    hLabelWrap = "30",
    plotColor = "BrBG",
    labelColor = "auto",
    frequencyTable = FALSE,
    showMedian = FALSE,
    showMean = FALSE,
    frequencies = "counts",
    showMannU = FALSE,
    showKW = FALSE,
    showPostHoc = FALSE,
    postHoc = "dunn",
    pValue = "none",
    adjustMethod = "holm",
    descAsVarName = FALSE,
    titleText,
    titleFontFace = "bold",
    titleFontSize = "14",
    titleAlign = "0.5",
    subtitleText,
    subtitleFontFace = "plain",
    subtitleFontSize = "12",
    subtitleAlign = "0.5",
    captionText,
    captionFontFace = "italic",
    captionFontSize = "10",
    captionAlign = "1",
    legendText,
    legendFontSize = "11",
    legendPosition = "bottom",
    yAxisLabelFontSize = 11,
    yAxisLabelRotation = 0,
    xAxisLabelFontSize = 11,
    xAxisLabelRotation = 0) {

    if ( ! requireNamespace("jmvcore", quietly=TRUE))
        stop("likertplot requires jmvcore to be installed (restart may be required)")

    if ( ! missing(liks)) liks <- jmvcore::resolveQuo(jmvcore::enquo(liks))
    if ( ! missing(group)) group <- jmvcore::resolveQuo(jmvcore::enquo(group))
    if (missing(data))
        data <- jmvcore::marshalData(
            parent.frame(),
            `if`( ! missing(liks), liks, NULL),
            `if`( ! missing(group), group, NULL))

    for (v in group) if (v %in% names(data)) data[[v]] <- as.factor(data[[v]])

    options <- likertplotOptions$new(
        liks = liks,
        group = group,
        type = type,
        sorting = sorting,
        groupBy = groupBy,
        addLabels = addLabels,
        hideLabelsBelow = hideLabelsBelow,
        addTotals = addTotals,
        addMedianLine = addMedianLine,
        reverseLikert = reverseLikert,
        toInteger = toInteger,
        tidyUp = tidyUp,
        ignoreNA = ignoreNA,
        textSize = textSize,
        labelSize = labelSize,
        groupSize = groupSize,
        accuracy = accuracy,
        vLabelWrap = vLabelWrap,
        hLabelWrap = hLabelWrap,
        plotColor = plotColor,
        labelColor = labelColor,
        frequencyTable = frequencyTable,
        showMedian = showMedian,
        showMean = showMean,
        frequencies = frequencies,
        showMannU = showMannU,
        showKW = showKW,
        showPostHoc = showPostHoc,
        postHoc = postHoc,
        pValue = pValue,
        adjustMethod = adjustMethod,
        descAsVarName = descAsVarName,
        titleText = titleText,
        titleFontFace = titleFontFace,
        titleFontSize = titleFontSize,
        titleAlign = titleAlign,
        subtitleText = subtitleText,
        subtitleFontFace = subtitleFontFace,
        subtitleFontSize = subtitleFontSize,
        subtitleAlign = subtitleAlign,
        captionText = captionText,
        captionFontFace = captionFontFace,
        captionFontSize = captionFontSize,
        captionAlign = captionAlign,
        legendText = legendText,
        legendFontSize = legendFontSize,
        legendPosition = legendPosition,
        yAxisLabelFontSize = yAxisLabelFontSize,
        yAxisLabelRotation = yAxisLabelRotation,
        xAxisLabelFontSize = xAxisLabelFontSize,
        xAxisLabelRotation = xAxisLabelRotation)

    analysis <- likertplotClass$new(
        options = options,
        data = data)

    analysis$run()

    analysis$results
}

