
# This file is automatically generated, you probably don't want to edit this

mosaicOptions <- if (requireNamespace("jmvcore", quietly=TRUE)) R6::R6Class(
    "mosaicOptions",
    inherit = jmvcore::Options,
    public = list(
        initialize = function(
            category = NULL,
            group = NULL,
            counts = NULL,
            facet = NULL,
            ignoreNA = TRUE,
            horizontal = FALSE,
            order = "none",
            reverseStack = FALSE,
            noPadding = FALSE,
            noAxes = FALSE,
            noPercent = FALSE,
            labelType = "none",
            accuracy = "0.1",
            colorPalette = "jmv",
            labelColor = "auto",
            labelFontSize = 12,
            facetBy = "column",
            facetNumber = 1,
            titleText = "",
            titleFontFace = "bold",
            titleFontSize = "14",
            titleAlign = "0.5",
            subtitleText = "",
            subtitleFontFace = "plain",
            subtitleFontSize = "12",
            subtitleAlign = "0.5",
            captionText = "",
            captionFontFace = "italic",
            captionFontSize = "10",
            captionAlign = "1",
            legendText = "",
            legendFontSize = "14",
            legendPosition = "right",
            xAxisText = "",
            xAxisFontSize = "16",
            xAxisPosition = "0.5",
            yAxisText = "",
            yAxisFontSize = "16",
            yAxisPosition = "0.5",
            yAxisLabelFontSize = 12,
            yAxisLabelRotation = 0,
            xAxisLabelFontSize = 12,
            xAxisLabelRotation = 0,
            xTicks = 0,
            yTicks = 0, ...) {

            super$initialize(
                package="vijPlots",
                name="mosaic",
                requiresData=TRUE,
                ...)

            private$..category <- jmvcore::OptionVariable$new(
                "category",
                category,
                suggested=list(
                    "nominal",
                    "ordinal"),
                permitted=list(
                    "factor"))
            private$..group <- jmvcore::OptionVariable$new(
                "group",
                group,
                suggested=list(
                    "nominal",
                    "ordinal"),
                permitted=list(
                    "factor"))
            private$..counts <- jmvcore::OptionVariable$new(
                "counts",
                counts,
                suggested=list(
                    "continuous"),
                permitted=list(
                    "numeric"))
            private$..facet <- jmvcore::OptionVariable$new(
                "facet",
                facet,
                suggested=list(
                    "nominal",
                    "ordinal"),
                permitted=list(
                    "factor"))
            private$..ignoreNA <- jmvcore::OptionBool$new(
                "ignoreNA",
                ignoreNA,
                default=TRUE)
            private$..horizontal <- jmvcore::OptionBool$new(
                "horizontal",
                horizontal,
                default=FALSE)
            private$..order <- jmvcore::OptionList$new(
                "order",
                order,
                options=list(
                    "decreasing",
                    "increasing",
                    "none"),
                default="none")
            private$..reverseStack <- jmvcore::OptionBool$new(
                "reverseStack",
                reverseStack,
                default=FALSE)
            private$..noPadding <- jmvcore::OptionBool$new(
                "noPadding",
                noPadding,
                default=FALSE)
            private$..noAxes <- jmvcore::OptionBool$new(
                "noAxes",
                noAxes,
                default=FALSE)
            private$..noPercent <- jmvcore::OptionBool$new(
                "noPercent",
                noPercent,
                default=FALSE)
            private$..labelType <- jmvcore::OptionList$new(
                "labelType",
                labelType,
                options=list(
                    "none",
                    "count",
                    "percent",
                    "residuals"),
                default="none")
            private$..accuracy <- jmvcore::OptionList$new(
                "accuracy",
                accuracy,
                options=list(
                    "1",
                    "0.1",
                    "0.01"),
                default="0.1")
            private$..colorPalette <- jmvcore::OptionList$new(
                "colorPalette",
                colorPalette,
                options=list(
                    "jmv",
                    "Set1",
                    "Set2",
                    "Set3",
                    "Pastel1",
                    "Pastel2",
                    "Accent",
                    "Paired",
                    "Dark2",
                    "Spectral",
                    "RdYlGn",
                    "RdYlBu",
                    "RdGy",
                    "RdBu",
                    "PuOr",
                    "PRGn",
                    "PiYG",
                    "BrBG",
                    "Blues",
                    "Greens",
                    "Greys",
                    "Oranges",
                    "Purples",
                    "Reds",
                    "BuGn",
                    "BuPu",
                    "GnBu",
                    "OrRd",
                    "PuBu",
                    "PuBuGn",
                    "PuRd",
                    "RdPu",
                    "YlGn",
                    "YlGnBu",
                    "YlOrBr",
                    "YlOrRd",
                    "viridis::viridis",
                    "viridis::magma",
                    "viridis::inferno",
                    "viridis::plasma",
                    "viridis::turbo",
                    "dichromat::Categorical.12",
                    "tidy::friendly",
                    "tidy::seaside",
                    "tidy::apple",
                    "tidy::ibm",
                    "tidy::candy",
                    "tidy::alger",
                    "tidy::rainbow",
                    "tidy::metro",
                    "custom::lemovice"),
                default="jmv")
            private$..labelColor <- jmvcore::OptionList$new(
                "labelColor",
                labelColor,
                options=list(
                    "black",
                    "white",
                    "auto"),
                default="auto")
            private$..labelFontSize <- jmvcore::OptionNumber$new(
                "labelFontSize",
                labelFontSize,
                min=8,
                max=24,
                default=12)
            private$..facetBy <- jmvcore::OptionList$new(
                "facetBy",
                facetBy,
                options=list(
                    "row",
                    "column"),
                default="column")
            private$..facetNumber <- jmvcore::OptionInteger$new(
                "facetNumber",
                facetNumber,
                min=1,
                max=10,
                default=1)
            private$..titleText <- jmvcore::OptionString$new(
                "titleText",
                titleText,
                default="")
            private$..titleFontFace <- jmvcore::OptionList$new(
                "titleFontFace",
                titleFontFace,
                options=list(
                    "plain",
                    "bold",
                    "italic",
                    "bold.italic"),
                default="bold")
            private$..titleFontSize <- jmvcore::OptionList$new(
                "titleFontSize",
                titleFontSize,
                options=list(
                    "12",
                    "14",
                    "16",
                    "18",
                    "20",
                    "22",
                    "24"),
                default="14")
            private$..titleAlign <- jmvcore::OptionList$new(
                "titleAlign",
                titleAlign,
                options=list(
                    "0",
                    "0.5",
                    "1"),
                default="0.5")
            private$..subtitleText <- jmvcore::OptionString$new(
                "subtitleText",
                subtitleText,
                default="")
            private$..subtitleFontFace <- jmvcore::OptionList$new(
                "subtitleFontFace",
                subtitleFontFace,
                options=list(
                    "plain",
                    "bold",
                    "italic",
                    "bold.italic"),
                default="plain")
            private$..subtitleFontSize <- jmvcore::OptionList$new(
                "subtitleFontSize",
                subtitleFontSize,
                options=list(
                    "10",
                    "12",
                    "14",
                    "16",
                    "18",
                    "20",
                    "22"),
                default="12")
            private$..subtitleAlign <- jmvcore::OptionList$new(
                "subtitleAlign",
                subtitleAlign,
                options=list(
                    "0",
                    "0.5",
                    "1"),
                default="0.5")
            private$..captionText <- jmvcore::OptionString$new(
                "captionText",
                captionText,
                default="")
            private$..captionFontFace <- jmvcore::OptionList$new(
                "captionFontFace",
                captionFontFace,
                options=list(
                    "plain",
                    "bold",
                    "italic",
                    "bold.italic"),
                default="italic")
            private$..captionFontSize <- jmvcore::OptionList$new(
                "captionFontSize",
                captionFontSize,
                options=list(
                    "8",
                    "10",
                    "12",
                    "14",
                    "16",
                    "18",
                    "20"),
                default="10")
            private$..captionAlign <- jmvcore::OptionList$new(
                "captionAlign",
                captionAlign,
                options=list(
                    "0",
                    "0.5",
                    "1"),
                default="1")
            private$..legendText <- jmvcore::OptionString$new(
                "legendText",
                legendText,
                default="")
            private$..legendFontSize <- jmvcore::OptionList$new(
                "legendFontSize",
                legendFontSize,
                options=list(
                    "10",
                    "12",
                    "14",
                    "16",
                    "18",
                    "20"),
                default="14")
            private$..legendPosition <- jmvcore::OptionList$new(
                "legendPosition",
                legendPosition,
                options=list(
                    "right",
                    "bottom",
                    "left",
                    "top"),
                default="right")
            private$..xAxisText <- jmvcore::OptionString$new(
                "xAxisText",
                xAxisText,
                default="")
            private$..xAxisFontSize <- jmvcore::OptionList$new(
                "xAxisFontSize",
                xAxisFontSize,
                options=list(
                    "10",
                    "12",
                    "14",
                    "16",
                    "18",
                    "20"),
                default="16")
            private$..xAxisPosition <- jmvcore::OptionList$new(
                "xAxisPosition",
                xAxisPosition,
                options=list(
                    "0",
                    "0.5",
                    "1"),
                default="0.5")
            private$..yAxisText <- jmvcore::OptionString$new(
                "yAxisText",
                yAxisText,
                default="")
            private$..yAxisFontSize <- jmvcore::OptionList$new(
                "yAxisFontSize",
                yAxisFontSize,
                options=list(
                    "10",
                    "12",
                    "14",
                    "16",
                    "18",
                    "20"),
                default="16")
            private$..yAxisPosition <- jmvcore::OptionList$new(
                "yAxisPosition",
                yAxisPosition,
                options=list(
                    "1",
                    "0.5",
                    "0"),
                default="0.5")
            private$..yAxisLabelFontSize <- jmvcore::OptionNumber$new(
                "yAxisLabelFontSize",
                yAxisLabelFontSize,
                default=12)
            private$..yAxisLabelRotation <- jmvcore::OptionNumber$new(
                "yAxisLabelRotation",
                yAxisLabelRotation,
                default=0,
                min=0,
                max=360)
            private$..xAxisLabelFontSize <- jmvcore::OptionNumber$new(
                "xAxisLabelFontSize",
                xAxisLabelFontSize,
                default=12)
            private$..xAxisLabelRotation <- jmvcore::OptionNumber$new(
                "xAxisLabelRotation",
                xAxisLabelRotation,
                default=0,
                min=0,
                max=360)
            private$..xTicks <- jmvcore::OptionInteger$new(
                "xTicks",
                xTicks,
                default=0,
                min=0,
                max=99)
            private$..yTicks <- jmvcore::OptionInteger$new(
                "yTicks",
                yTicks,
                default=0,
                min=0,
                max=99)

            self$.addOption(private$..category)
            self$.addOption(private$..group)
            self$.addOption(private$..counts)
            self$.addOption(private$..facet)
            self$.addOption(private$..ignoreNA)
            self$.addOption(private$..horizontal)
            self$.addOption(private$..order)
            self$.addOption(private$..reverseStack)
            self$.addOption(private$..noPadding)
            self$.addOption(private$..noAxes)
            self$.addOption(private$..noPercent)
            self$.addOption(private$..labelType)
            self$.addOption(private$..accuracy)
            self$.addOption(private$..colorPalette)
            self$.addOption(private$..labelColor)
            self$.addOption(private$..labelFontSize)
            self$.addOption(private$..facetBy)
            self$.addOption(private$..facetNumber)
            self$.addOption(private$..titleText)
            self$.addOption(private$..titleFontFace)
            self$.addOption(private$..titleFontSize)
            self$.addOption(private$..titleAlign)
            self$.addOption(private$..subtitleText)
            self$.addOption(private$..subtitleFontFace)
            self$.addOption(private$..subtitleFontSize)
            self$.addOption(private$..subtitleAlign)
            self$.addOption(private$..captionText)
            self$.addOption(private$..captionFontFace)
            self$.addOption(private$..captionFontSize)
            self$.addOption(private$..captionAlign)
            self$.addOption(private$..legendText)
            self$.addOption(private$..legendFontSize)
            self$.addOption(private$..legendPosition)
            self$.addOption(private$..xAxisText)
            self$.addOption(private$..xAxisFontSize)
            self$.addOption(private$..xAxisPosition)
            self$.addOption(private$..yAxisText)
            self$.addOption(private$..yAxisFontSize)
            self$.addOption(private$..yAxisPosition)
            self$.addOption(private$..yAxisLabelFontSize)
            self$.addOption(private$..yAxisLabelRotation)
            self$.addOption(private$..xAxisLabelFontSize)
            self$.addOption(private$..xAxisLabelRotation)
            self$.addOption(private$..xTicks)
            self$.addOption(private$..yTicks)
        }),
    active = list(
        category = function() private$..category$value,
        group = function() private$..group$value,
        counts = function() private$..counts$value,
        facet = function() private$..facet$value,
        ignoreNA = function() private$..ignoreNA$value,
        horizontal = function() private$..horizontal$value,
        order = function() private$..order$value,
        reverseStack = function() private$..reverseStack$value,
        noPadding = function() private$..noPadding$value,
        noAxes = function() private$..noAxes$value,
        noPercent = function() private$..noPercent$value,
        labelType = function() private$..labelType$value,
        accuracy = function() private$..accuracy$value,
        colorPalette = function() private$..colorPalette$value,
        labelColor = function() private$..labelColor$value,
        labelFontSize = function() private$..labelFontSize$value,
        facetBy = function() private$..facetBy$value,
        facetNumber = function() private$..facetNumber$value,
        titleText = function() private$..titleText$value,
        titleFontFace = function() private$..titleFontFace$value,
        titleFontSize = function() private$..titleFontSize$value,
        titleAlign = function() private$..titleAlign$value,
        subtitleText = function() private$..subtitleText$value,
        subtitleFontFace = function() private$..subtitleFontFace$value,
        subtitleFontSize = function() private$..subtitleFontSize$value,
        subtitleAlign = function() private$..subtitleAlign$value,
        captionText = function() private$..captionText$value,
        captionFontFace = function() private$..captionFontFace$value,
        captionFontSize = function() private$..captionFontSize$value,
        captionAlign = function() private$..captionAlign$value,
        legendText = function() private$..legendText$value,
        legendFontSize = function() private$..legendFontSize$value,
        legendPosition = function() private$..legendPosition$value,
        xAxisText = function() private$..xAxisText$value,
        xAxisFontSize = function() private$..xAxisFontSize$value,
        xAxisPosition = function() private$..xAxisPosition$value,
        yAxisText = function() private$..yAxisText$value,
        yAxisFontSize = function() private$..yAxisFontSize$value,
        yAxisPosition = function() private$..yAxisPosition$value,
        yAxisLabelFontSize = function() private$..yAxisLabelFontSize$value,
        yAxisLabelRotation = function() private$..yAxisLabelRotation$value,
        xAxisLabelFontSize = function() private$..xAxisLabelFontSize$value,
        xAxisLabelRotation = function() private$..xAxisLabelRotation$value,
        xTicks = function() private$..xTicks$value,
        yTicks = function() private$..yTicks$value),
    private = list(
        ..category = NA,
        ..group = NA,
        ..counts = NA,
        ..facet = NA,
        ..ignoreNA = NA,
        ..horizontal = NA,
        ..order = NA,
        ..reverseStack = NA,
        ..noPadding = NA,
        ..noAxes = NA,
        ..noPercent = NA,
        ..labelType = NA,
        ..accuracy = NA,
        ..colorPalette = NA,
        ..labelColor = NA,
        ..labelFontSize = NA,
        ..facetBy = NA,
        ..facetNumber = NA,
        ..titleText = NA,
        ..titleFontFace = NA,
        ..titleFontSize = NA,
        ..titleAlign = NA,
        ..subtitleText = NA,
        ..subtitleFontFace = NA,
        ..subtitleFontSize = NA,
        ..subtitleAlign = NA,
        ..captionText = NA,
        ..captionFontFace = NA,
        ..captionFontSize = NA,
        ..captionAlign = NA,
        ..legendText = NA,
        ..legendFontSize = NA,
        ..legendPosition = NA,
        ..xAxisText = NA,
        ..xAxisFontSize = NA,
        ..xAxisPosition = NA,
        ..yAxisText = NA,
        ..yAxisFontSize = NA,
        ..yAxisPosition = NA,
        ..yAxisLabelFontSize = NA,
        ..yAxisLabelRotation = NA,
        ..xAxisLabelFontSize = NA,
        ..xAxisLabelRotation = NA,
        ..xTicks = NA,
        ..yTicks = NA)
)

mosaicResults <- if (requireNamespace("jmvcore", quietly=TRUE)) R6::R6Class(
    "mosaicResults",
    inherit = jmvcore::Group,
    active = list(
        plot = function() private$.items[["plot"]]),
    private = list(),
    public=list(
        initialize=function(options) {
            super$initialize(
                options=options,
                name="",
                title="Mosaic Plot")
            self$add(jmvcore::Image$new(
                options=options,
                name="plot",
                title="",
                width=600,
                height=400,
                renderFun=".plot"))}))

mosaicBase <- if (requireNamespace("jmvcore", quietly=TRUE)) R6::R6Class(
    "mosaicBase",
    inherit = jmvcore::Analysis,
    public = list(
        initialize = function(options, data=NULL, datasetId="", analysisId="", revision=0) {
            super$initialize(
                package = "vijPlots",
                name = "mosaic",
                version = c(1,0,0),
                options = options,
                results = mosaicResults$new(options=options),
                data = data,
                datasetId = datasetId,
                analysisId = analysisId,
                revision = revision,
                pause = NULL,
                completeWhenFilled = FALSE,
                requiresMissings = FALSE,
                weightsSupport = 'full')
        }))

#' Mosaic Plot
#'
#' 
#' @param data .
#' @param category .
#' @param group .
#' @param counts .
#' @param facet .
#' @param ignoreNA .
#' @param horizontal .
#' @param order .
#' @param reverseStack .
#' @param noPadding .
#' @param noAxes .
#' @param noPercent .
#' @param labelType .
#' @param accuracy .
#' @param colorPalette .
#' @param labelColor .
#' @param labelFontSize .
#' @param facetBy .
#' @param facetNumber .
#' @param titleText .
#' @param titleFontFace .
#' @param titleFontSize .
#' @param titleAlign .
#' @param subtitleText .
#' @param subtitleFontFace .
#' @param subtitleFontSize .
#' @param subtitleAlign .
#' @param captionText .
#' @param captionFontFace .
#' @param captionFontSize .
#' @param captionAlign .
#' @param legendText .
#' @param legendFontSize .
#' @param legendPosition .
#' @param xAxisText .
#' @param xAxisFontSize .
#' @param xAxisPosition .
#' @param yAxisText .
#' @param yAxisFontSize .
#' @param yAxisPosition .
#' @param yAxisLabelFontSize .
#' @param yAxisLabelRotation .
#' @param xAxisLabelFontSize .
#' @param xAxisLabelRotation .
#' @param xTicks .
#' @param yTicks .
#' @return A results object containing:
#' \tabular{llllll}{
#'   \code{results$plot} \tab \tab \tab \tab \tab an image \cr
#' }
#'
#' @export
mosaic <- function(
    data,
    category,
    group,
    counts,
    facet,
    ignoreNA = TRUE,
    horizontal = FALSE,
    order = "none",
    reverseStack = FALSE,
    noPadding = FALSE,
    noAxes = FALSE,
    noPercent = FALSE,
    labelType = "none",
    accuracy = "0.1",
    colorPalette = "jmv",
    labelColor = "auto",
    labelFontSize = 12,
    facetBy = "column",
    facetNumber = 1,
    titleText = "",
    titleFontFace = "bold",
    titleFontSize = "14",
    titleAlign = "0.5",
    subtitleText = "",
    subtitleFontFace = "plain",
    subtitleFontSize = "12",
    subtitleAlign = "0.5",
    captionText = "",
    captionFontFace = "italic",
    captionFontSize = "10",
    captionAlign = "1",
    legendText = "",
    legendFontSize = "14",
    legendPosition = "right",
    xAxisText = "",
    xAxisFontSize = "16",
    xAxisPosition = "0.5",
    yAxisText = "",
    yAxisFontSize = "16",
    yAxisPosition = "0.5",
    yAxisLabelFontSize = 12,
    yAxisLabelRotation = 0,
    xAxisLabelFontSize = 12,
    xAxisLabelRotation = 0,
    xTicks = 0,
    yTicks = 0) {

    if ( ! requireNamespace("jmvcore", quietly=TRUE))
        stop("mosaic requires jmvcore to be installed (restart may be required)")

    if ( ! missing(category)) category <- jmvcore::resolveQuo(jmvcore::enquo(category))
    if ( ! missing(group)) group <- jmvcore::resolveQuo(jmvcore::enquo(group))
    if ( ! missing(counts)) counts <- jmvcore::resolveQuo(jmvcore::enquo(counts))
    if ( ! missing(facet)) facet <- jmvcore::resolveQuo(jmvcore::enquo(facet))
    if (missing(data))
        data <- jmvcore::marshalData(
            parent.frame(),
            `if`( ! missing(category), category, NULL),
            `if`( ! missing(group), group, NULL),
            `if`( ! missing(counts), counts, NULL),
            `if`( ! missing(facet), facet, NULL))

    for (v in category) if (v %in% names(data)) data[[v]] <- as.factor(data[[v]])
    for (v in group) if (v %in% names(data)) data[[v]] <- as.factor(data[[v]])
    for (v in facet) if (v %in% names(data)) data[[v]] <- as.factor(data[[v]])

    options <- mosaicOptions$new(
        category = category,
        group = group,
        counts = counts,
        facet = facet,
        ignoreNA = ignoreNA,
        horizontal = horizontal,
        order = order,
        reverseStack = reverseStack,
        noPadding = noPadding,
        noAxes = noAxes,
        noPercent = noPercent,
        labelType = labelType,
        accuracy = accuracy,
        colorPalette = colorPalette,
        labelColor = labelColor,
        labelFontSize = labelFontSize,
        facetBy = facetBy,
        facetNumber = facetNumber,
        titleText = titleText,
        titleFontFace = titleFontFace,
        titleFontSize = titleFontSize,
        titleAlign = titleAlign,
        subtitleText = subtitleText,
        subtitleFontFace = subtitleFontFace,
        subtitleFontSize = subtitleFontSize,
        subtitleAlign = subtitleAlign,
        captionText = captionText,
        captionFontFace = captionFontFace,
        captionFontSize = captionFontSize,
        captionAlign = captionAlign,
        legendText = legendText,
        legendFontSize = legendFontSize,
        legendPosition = legendPosition,
        xAxisText = xAxisText,
        xAxisFontSize = xAxisFontSize,
        xAxisPosition = xAxisPosition,
        yAxisText = yAxisText,
        yAxisFontSize = yAxisFontSize,
        yAxisPosition = yAxisPosition,
        yAxisLabelFontSize = yAxisLabelFontSize,
        yAxisLabelRotation = yAxisLabelRotation,
        xAxisLabelFontSize = xAxisLabelFontSize,
        xAxisLabelRotation = xAxisLabelRotation,
        xTicks = xTicks,
        yTicks = yTicks)

    analysis <- mosaicClass$new(
        options = options,
        data = data)

    analysis$run()

    analysis$results
}

