
# This file is automatically generated, you probably don't want to edit this

mrfrequenciesOptions <- if (requireNamespace("jmvcore", quietly=TRUE)) R6::R6Class(
    "mrfrequenciesOptions",
    inherit = jmvcore::Options,
    public = list(
        initialize = function(
            mode = NULL,
            repVar = NULL,
            separator = ";",
            emptyAsNA = TRUE,
            resps = NULL,
            endorsed = 1,
            optionname = "Options",
            order = "decreasing",
            showTotal = TRUE,
            showCounts = TRUE,
            labelPosition = "middle",
            showResponses = TRUE,
            showCases = TRUE,
            yaxis = "cases",
            horizontal = FALSE,
            showLabels = FALSE,
            accuracy = "0.1",
            labelFontSize = 12,
            colorPalette = "jmv",
            singleColor = TRUE,
            colorNo = 1,
            borderColor = "none",
            textColor = "auto",
            titleText = NULL,
            titleFontFace = "bold",
            titleFontSize = "14",
            titleAlign = "0.5",
            subtitleText = NULL,
            subtitleFontFace = "plain",
            subtitleFontSize = "12",
            subtitleAlign = "0.5",
            captionText = NULL,
            captionFontFace = "italic",
            captionFontSize = "10",
            captionAlign = "1",
            xAxisText = NULL,
            xAxisFontSize = "16",
            xAxisPosition = "0.5",
            yAxisText = NULL,
            yAxisFontSize = "16",
            yAxisPosition = "0.5",
            yAxisLabelFontSize = 12,
            yAxisLabelRotation = 0,
            yAxisRangeType = "auto",
            yAxisRangeMin = 0,
            yAxisRangeMax = 10,
            xAxisLabelFontSize = 12,
            xAxisLabelRotation = 0,
            xAxisRangeType = "auto",
            xAxisRangeMin = 0,
            xAxisRangeMax = 10, ...) {

            super$initialize(
                package="vijPlots",
                name="mrfrequencies",
                requiresData=TRUE,
                ...)

            private$..mode <- jmvcore::OptionList$new(
                "mode",
                mode,
                options=list(
                    "morevar",
                    "onevar"))
            private$..repVar <- jmvcore::OptionVariable$new(
                "repVar",
                repVar,
                suggested=list(
                    "nominal"),
                permitted=list(
                    "factor"))
            private$..separator <- jmvcore::OptionString$new(
                "separator",
                separator,
                default=";")
            private$..emptyAsNA <- jmvcore::OptionBool$new(
                "emptyAsNA",
                emptyAsNA,
                default=TRUE)
            private$..resps <- jmvcore::OptionVariables$new(
                "resps",
                resps,
                suggested=list(
                    "nominal"),
                permitted=list(
                    "factor"))
            private$..endorsed <- jmvcore::OptionInteger$new(
                "endorsed",
                endorsed,
                default=1)
            private$..optionname <- jmvcore::OptionString$new(
                "optionname",
                optionname,
                default="Options")
            private$..order <- jmvcore::OptionList$new(
                "order",
                order,
                options=list(
                    "decreasing",
                    "increasing",
                    "none"),
                default="decreasing")
            private$..showTotal <- jmvcore::OptionBool$new(
                "showTotal",
                showTotal,
                default=TRUE)
            private$..showCounts <- jmvcore::OptionBool$new(
                "showCounts",
                showCounts,
                default=TRUE)
            private$..labelPosition <- jmvcore::OptionList$new(
                "labelPosition",
                labelPosition,
                options=list(
                    "middle",
                    "top"),
                default="middle")
            private$..showResponses <- jmvcore::OptionBool$new(
                "showResponses",
                showResponses,
                default=TRUE)
            private$..showCases <- jmvcore::OptionBool$new(
                "showCases",
                showCases,
                default=TRUE)
            private$..yaxis <- jmvcore::OptionList$new(
                "yaxis",
                yaxis,
                options=list(
                    "counts",
                    "responses",
                    "cases"),
                default="cases")
            private$..horizontal <- jmvcore::OptionBool$new(
                "horizontal",
                horizontal,
                default=FALSE)
            private$..showLabels <- jmvcore::OptionBool$new(
                "showLabels",
                showLabels,
                default=FALSE)
            private$..accuracy <- jmvcore::OptionList$new(
                "accuracy",
                accuracy,
                options=list(
                    "1",
                    "0.1",
                    "0.01"),
                default="0.1")
            private$..labelFontSize <- jmvcore::OptionNumber$new(
                "labelFontSize",
                labelFontSize,
                min=8,
                max=24,
                default=12)
            private$..colorPalette <- jmvcore::OptionList$new(
                "colorPalette",
                colorPalette,
                options=list(
                    "jmv",
                    "Set1",
                    "Set2",
                    "Set3",
                    "Pastel1",
                    "Pastel2",
                    "Accent",
                    "Paired",
                    "Dark2",
                    "Spectral",
                    "RdYlGn",
                    "RdYlBu",
                    "RdGy",
                    "RdBu",
                    "PuOr",
                    "PRGn",
                    "PiYG",
                    "BrBG",
                    "Blues",
                    "Greens",
                    "Greys",
                    "Oranges",
                    "Purples",
                    "Reds",
                    "BuGn",
                    "BuPu",
                    "GnBu",
                    "OrRd",
                    "PuBu",
                    "PuBuGn",
                    "PuRd",
                    "RdPu",
                    "YlGn",
                    "YlGnBu",
                    "YlOrBr",
                    "YlOrRd",
                    "viridis::viridis",
                    "viridis::magma",
                    "viridis::inferno",
                    "viridis::plasma",
                    "viridis::turbo",
                    "dichromat::Categorical.12",
                    "tidy::friendly",
                    "tidy::seaside",
                    "tidy::apple",
                    "tidy::ibm",
                    "tidy::candy",
                    "tidy::alger",
                    "tidy::rainbow",
                    "tidy::metro",
                    "custom::lemovice"),
                default="jmv")
            private$..singleColor <- jmvcore::OptionBool$new(
                "singleColor",
                singleColor,
                default=TRUE)
            private$..colorNo <- jmvcore::OptionNumber$new(
                "colorNo",
                colorNo,
                min=1,
                max=255,
                default=1)
            private$..borderColor <- jmvcore::OptionList$new(
                "borderColor",
                borderColor,
                options=list(
                    "none",
                    "black",
                    "white",
                    "gray"),
                default="none")
            private$..textColor <- jmvcore::OptionList$new(
                "textColor",
                textColor,
                options=list(
                    "black",
                    "white",
                    "auto"),
                default="auto")
            private$..titleText <- jmvcore::OptionString$new(
                "titleText",
                titleText)
            private$..titleFontFace <- jmvcore::OptionList$new(
                "titleFontFace",
                titleFontFace,
                options=list(
                    "plain",
                    "bold",
                    "italic",
                    "bold.italic"),
                default="bold")
            private$..titleFontSize <- jmvcore::OptionList$new(
                "titleFontSize",
                titleFontSize,
                options=list(
                    "12",
                    "14",
                    "16",
                    "18",
                    "20",
                    "22",
                    "24"),
                default="14")
            private$..titleAlign <- jmvcore::OptionList$new(
                "titleAlign",
                titleAlign,
                options=list(
                    "0",
                    "0.5",
                    "1"),
                default="0.5")
            private$..subtitleText <- jmvcore::OptionString$new(
                "subtitleText",
                subtitleText)
            private$..subtitleFontFace <- jmvcore::OptionList$new(
                "subtitleFontFace",
                subtitleFontFace,
                options=list(
                    "plain",
                    "bold",
                    "italic",
                    "bold.italic"),
                default="plain")
            private$..subtitleFontSize <- jmvcore::OptionList$new(
                "subtitleFontSize",
                subtitleFontSize,
                options=list(
                    "10",
                    "12",
                    "14",
                    "16",
                    "18",
                    "20",
                    "22"),
                default="12")
            private$..subtitleAlign <- jmvcore::OptionList$new(
                "subtitleAlign",
                subtitleAlign,
                options=list(
                    "0",
                    "0.5",
                    "1"),
                default="0.5")
            private$..captionText <- jmvcore::OptionString$new(
                "captionText",
                captionText)
            private$..captionFontFace <- jmvcore::OptionList$new(
                "captionFontFace",
                captionFontFace,
                options=list(
                    "plain",
                    "bold",
                    "italic",
                    "bold.italic"),
                default="italic")
            private$..captionFontSize <- jmvcore::OptionList$new(
                "captionFontSize",
                captionFontSize,
                options=list(
                    "8",
                    "10",
                    "12",
                    "14",
                    "16",
                    "18",
                    "20"),
                default="10")
            private$..captionAlign <- jmvcore::OptionList$new(
                "captionAlign",
                captionAlign,
                options=list(
                    "0",
                    "0.5",
                    "1"),
                default="1")
            private$..xAxisText <- jmvcore::OptionString$new(
                "xAxisText",
                xAxisText)
            private$..xAxisFontSize <- jmvcore::OptionList$new(
                "xAxisFontSize",
                xAxisFontSize,
                options=list(
                    "10",
                    "12",
                    "14",
                    "16",
                    "18",
                    "20"),
                default="16")
            private$..xAxisPosition <- jmvcore::OptionList$new(
                "xAxisPosition",
                xAxisPosition,
                options=list(
                    "0",
                    "0.5",
                    "1"),
                default="0.5")
            private$..yAxisText <- jmvcore::OptionString$new(
                "yAxisText",
                yAxisText)
            private$..yAxisFontSize <- jmvcore::OptionList$new(
                "yAxisFontSize",
                yAxisFontSize,
                options=list(
                    "10",
                    "12",
                    "14",
                    "16",
                    "18",
                    "20"),
                default="16")
            private$..yAxisPosition <- jmvcore::OptionList$new(
                "yAxisPosition",
                yAxisPosition,
                options=list(
                    "1",
                    "0.5",
                    "0"),
                default="0.5")
            private$..yAxisLabelFontSize <- jmvcore::OptionNumber$new(
                "yAxisLabelFontSize",
                yAxisLabelFontSize,
                default=12)
            private$..yAxisLabelRotation <- jmvcore::OptionNumber$new(
                "yAxisLabelRotation",
                yAxisLabelRotation,
                default=0,
                min=0,
                max=360)
            private$..yAxisRangeType <- jmvcore::OptionList$new(
                "yAxisRangeType",
                yAxisRangeType,
                options=list(
                    "auto",
                    "manual"),
                default="auto")
            private$..yAxisRangeMin <- jmvcore::OptionNumber$new(
                "yAxisRangeMin",
                yAxisRangeMin,
                default=0)
            private$..yAxisRangeMax <- jmvcore::OptionNumber$new(
                "yAxisRangeMax",
                yAxisRangeMax,
                default=10)
            private$..xAxisLabelFontSize <- jmvcore::OptionNumber$new(
                "xAxisLabelFontSize",
                xAxisLabelFontSize,
                default=12)
            private$..xAxisLabelRotation <- jmvcore::OptionNumber$new(
                "xAxisLabelRotation",
                xAxisLabelRotation,
                default=0,
                min=0,
                max=360)
            private$..xAxisRangeType <- jmvcore::OptionList$new(
                "xAxisRangeType",
                xAxisRangeType,
                options=list(
                    "auto",
                    "manual"),
                default="auto")
            private$..xAxisRangeMin <- jmvcore::OptionNumber$new(
                "xAxisRangeMin",
                xAxisRangeMin,
                default=0)
            private$..xAxisRangeMax <- jmvcore::OptionNumber$new(
                "xAxisRangeMax",
                xAxisRangeMax,
                default=10)

            self$.addOption(private$..mode)
            self$.addOption(private$..repVar)
            self$.addOption(private$..separator)
            self$.addOption(private$..emptyAsNA)
            self$.addOption(private$..resps)
            self$.addOption(private$..endorsed)
            self$.addOption(private$..optionname)
            self$.addOption(private$..order)
            self$.addOption(private$..showTotal)
            self$.addOption(private$..showCounts)
            self$.addOption(private$..labelPosition)
            self$.addOption(private$..showResponses)
            self$.addOption(private$..showCases)
            self$.addOption(private$..yaxis)
            self$.addOption(private$..horizontal)
            self$.addOption(private$..showLabels)
            self$.addOption(private$..accuracy)
            self$.addOption(private$..labelFontSize)
            self$.addOption(private$..colorPalette)
            self$.addOption(private$..singleColor)
            self$.addOption(private$..colorNo)
            self$.addOption(private$..borderColor)
            self$.addOption(private$..textColor)
            self$.addOption(private$..titleText)
            self$.addOption(private$..titleFontFace)
            self$.addOption(private$..titleFontSize)
            self$.addOption(private$..titleAlign)
            self$.addOption(private$..subtitleText)
            self$.addOption(private$..subtitleFontFace)
            self$.addOption(private$..subtitleFontSize)
            self$.addOption(private$..subtitleAlign)
            self$.addOption(private$..captionText)
            self$.addOption(private$..captionFontFace)
            self$.addOption(private$..captionFontSize)
            self$.addOption(private$..captionAlign)
            self$.addOption(private$..xAxisText)
            self$.addOption(private$..xAxisFontSize)
            self$.addOption(private$..xAxisPosition)
            self$.addOption(private$..yAxisText)
            self$.addOption(private$..yAxisFontSize)
            self$.addOption(private$..yAxisPosition)
            self$.addOption(private$..yAxisLabelFontSize)
            self$.addOption(private$..yAxisLabelRotation)
            self$.addOption(private$..yAxisRangeType)
            self$.addOption(private$..yAxisRangeMin)
            self$.addOption(private$..yAxisRangeMax)
            self$.addOption(private$..xAxisLabelFontSize)
            self$.addOption(private$..xAxisLabelRotation)
            self$.addOption(private$..xAxisRangeType)
            self$.addOption(private$..xAxisRangeMin)
            self$.addOption(private$..xAxisRangeMax)
        }),
    active = list(
        mode = function() private$..mode$value,
        repVar = function() private$..repVar$value,
        separator = function() private$..separator$value,
        emptyAsNA = function() private$..emptyAsNA$value,
        resps = function() private$..resps$value,
        endorsed = function() private$..endorsed$value,
        optionname = function() private$..optionname$value,
        order = function() private$..order$value,
        showTotal = function() private$..showTotal$value,
        showCounts = function() private$..showCounts$value,
        labelPosition = function() private$..labelPosition$value,
        showResponses = function() private$..showResponses$value,
        showCases = function() private$..showCases$value,
        yaxis = function() private$..yaxis$value,
        horizontal = function() private$..horizontal$value,
        showLabels = function() private$..showLabels$value,
        accuracy = function() private$..accuracy$value,
        labelFontSize = function() private$..labelFontSize$value,
        colorPalette = function() private$..colorPalette$value,
        singleColor = function() private$..singleColor$value,
        colorNo = function() private$..colorNo$value,
        borderColor = function() private$..borderColor$value,
        textColor = function() private$..textColor$value,
        titleText = function() private$..titleText$value,
        titleFontFace = function() private$..titleFontFace$value,
        titleFontSize = function() private$..titleFontSize$value,
        titleAlign = function() private$..titleAlign$value,
        subtitleText = function() private$..subtitleText$value,
        subtitleFontFace = function() private$..subtitleFontFace$value,
        subtitleFontSize = function() private$..subtitleFontSize$value,
        subtitleAlign = function() private$..subtitleAlign$value,
        captionText = function() private$..captionText$value,
        captionFontFace = function() private$..captionFontFace$value,
        captionFontSize = function() private$..captionFontSize$value,
        captionAlign = function() private$..captionAlign$value,
        xAxisText = function() private$..xAxisText$value,
        xAxisFontSize = function() private$..xAxisFontSize$value,
        xAxisPosition = function() private$..xAxisPosition$value,
        yAxisText = function() private$..yAxisText$value,
        yAxisFontSize = function() private$..yAxisFontSize$value,
        yAxisPosition = function() private$..yAxisPosition$value,
        yAxisLabelFontSize = function() private$..yAxisLabelFontSize$value,
        yAxisLabelRotation = function() private$..yAxisLabelRotation$value,
        yAxisRangeType = function() private$..yAxisRangeType$value,
        yAxisRangeMin = function() private$..yAxisRangeMin$value,
        yAxisRangeMax = function() private$..yAxisRangeMax$value,
        xAxisLabelFontSize = function() private$..xAxisLabelFontSize$value,
        xAxisLabelRotation = function() private$..xAxisLabelRotation$value,
        xAxisRangeType = function() private$..xAxisRangeType$value,
        xAxisRangeMin = function() private$..xAxisRangeMin$value,
        xAxisRangeMax = function() private$..xAxisRangeMax$value),
    private = list(
        ..mode = NA,
        ..repVar = NA,
        ..separator = NA,
        ..emptyAsNA = NA,
        ..resps = NA,
        ..endorsed = NA,
        ..optionname = NA,
        ..order = NA,
        ..showTotal = NA,
        ..showCounts = NA,
        ..labelPosition = NA,
        ..showResponses = NA,
        ..showCases = NA,
        ..yaxis = NA,
        ..horizontal = NA,
        ..showLabels = NA,
        ..accuracy = NA,
        ..labelFontSize = NA,
        ..colorPalette = NA,
        ..singleColor = NA,
        ..colorNo = NA,
        ..borderColor = NA,
        ..textColor = NA,
        ..titleText = NA,
        ..titleFontFace = NA,
        ..titleFontSize = NA,
        ..titleAlign = NA,
        ..subtitleText = NA,
        ..subtitleFontFace = NA,
        ..subtitleFontSize = NA,
        ..subtitleAlign = NA,
        ..captionText = NA,
        ..captionFontFace = NA,
        ..captionFontSize = NA,
        ..captionAlign = NA,
        ..xAxisText = NA,
        ..xAxisFontSize = NA,
        ..xAxisPosition = NA,
        ..yAxisText = NA,
        ..yAxisFontSize = NA,
        ..yAxisPosition = NA,
        ..yAxisLabelFontSize = NA,
        ..yAxisLabelRotation = NA,
        ..yAxisRangeType = NA,
        ..yAxisRangeMin = NA,
        ..yAxisRangeMax = NA,
        ..xAxisLabelFontSize = NA,
        ..xAxisLabelRotation = NA,
        ..xAxisRangeType = NA,
        ..xAxisRangeMin = NA,
        ..xAxisRangeMax = NA)
)

mrfrequenciesResults <- if (requireNamespace("jmvcore", quietly=TRUE)) R6::R6Class(
    "mrfrequenciesResults",
    inherit = jmvcore::Group,
    active = list(
        responses = function() private$.items[["responses"]],
        plot = function() private$.items[["plot"]]),
    private = list(),
    public=list(
        initialize=function(options) {
            super$initialize(
                options=options,
                name="",
                title="Multiple Response Frequencies")
            self$add(jmvcore::Table$new(
                options=options,
                name="responses",
                title="Frequencies",
                notes=list(
                    `noc`=""),
                columns=list(
                    list(
                        `name`="var", 
                        `title`="Options", 
                        `type`="text"),
                    list(
                        `name`="freq", 
                        `title`="Counts", 
                        `type`="integer", 
                        `visible`="(showCounts)"),
                    list(
                        `name`="responsepercent", 
                        `title`="% of Responses", 
                        `type`="number", 
                        `format`="pc", 
                        `visible`="(showResponses)"),
                    list(
                        `name`="casepercent", 
                        `title`="% of Cases", 
                        `type`="number", 
                        `format`="pc", 
                        `visible`="(showCases)")),
                clearWith=list(
                    "mode",
                    "resps",
                    "repVar",
                    "separator",
                    "emptyAsNA",
                    "endorsed",
                    "order")))
            self$add(jmvcore::Image$new(
                options=options,
                name="plot",
                title="Frequency Plot",
                width=400,
                height=300,
                renderFun=".plot"))}))

mrfrequenciesBase <- if (requireNamespace("jmvcore", quietly=TRUE)) R6::R6Class(
    "mrfrequenciesBase",
    inherit = jmvcore::Analysis,
    public = list(
        initialize = function(options, data=NULL, datasetId="", analysisId="", revision=0) {
            super$initialize(
                package = "vijPlots",
                name = "mrfrequencies",
                version = c(1,0,0),
                options = options,
                results = mrfrequenciesResults$new(options=options),
                data = data,
                datasetId = datasetId,
                analysisId = analysisId,
                revision = revision,
                pause = NULL,
                completeWhenFilled = FALSE,
                requiresMissings = FALSE,
                weightsSupport = 'auto')
        }))

#' Frequencies
#'
#' 
#' @param data .
#' @param mode .
#' @param repVar .
#' @param separator .
#' @param emptyAsNA .
#' @param resps .
#' @param endorsed .
#' @param optionname .
#' @param order .
#' @param showTotal .
#' @param showCounts .
#' @param labelPosition .
#' @param showResponses .
#' @param showCases .
#' @param yaxis .
#' @param horizontal .
#' @param showLabels .
#' @param accuracy .
#' @param labelFontSize .
#' @param colorPalette .
#' @param singleColor .
#' @param colorNo .
#' @param borderColor .
#' @param textColor .
#' @param titleText .
#' @param titleFontFace .
#' @param titleFontSize .
#' @param titleAlign .
#' @param subtitleText .
#' @param subtitleFontFace .
#' @param subtitleFontSize .
#' @param subtitleAlign .
#' @param captionText .
#' @param captionFontFace .
#' @param captionFontSize .
#' @param captionAlign .
#' @param xAxisText .
#' @param xAxisFontSize .
#' @param xAxisPosition .
#' @param yAxisText .
#' @param yAxisFontSize .
#' @param yAxisPosition .
#' @param yAxisLabelFontSize .
#' @param yAxisLabelRotation .
#' @param yAxisRangeType .
#' @param yAxisRangeMin .
#' @param yAxisRangeMax .
#' @param xAxisLabelFontSize .
#' @param xAxisLabelRotation .
#' @param xAxisRangeType .
#' @param xAxisRangeMin .
#' @param xAxisRangeMax .
#' @return A results object containing:
#' \tabular{llllll}{
#'   \code{results$responses} \tab \tab \tab \tab \tab a table \cr
#'   \code{results$plot} \tab \tab \tab \tab \tab an image \cr
#' }
#'
#' Tables can be converted to data frames with \code{asDF} or \code{\link{as.data.frame}}. For example:
#'
#' \code{results$responses$asDF}
#'
#' \code{as.data.frame(results$responses)}
#'
#' @export
mrfrequencies <- function(
    data,
    mode,
    repVar,
    separator = ";",
    emptyAsNA = TRUE,
    resps,
    endorsed = 1,
    optionname = "Options",
    order = "decreasing",
    showTotal = TRUE,
    showCounts = TRUE,
    labelPosition = "middle",
    showResponses = TRUE,
    showCases = TRUE,
    yaxis = "cases",
    horizontal = FALSE,
    showLabels = FALSE,
    accuracy = "0.1",
    labelFontSize = 12,
    colorPalette = "jmv",
    singleColor = TRUE,
    colorNo = 1,
    borderColor = "none",
    textColor = "auto",
    titleText,
    titleFontFace = "bold",
    titleFontSize = "14",
    titleAlign = "0.5",
    subtitleText,
    subtitleFontFace = "plain",
    subtitleFontSize = "12",
    subtitleAlign = "0.5",
    captionText,
    captionFontFace = "italic",
    captionFontSize = "10",
    captionAlign = "1",
    xAxisText,
    xAxisFontSize = "16",
    xAxisPosition = "0.5",
    yAxisText,
    yAxisFontSize = "16",
    yAxisPosition = "0.5",
    yAxisLabelFontSize = 12,
    yAxisLabelRotation = 0,
    yAxisRangeType = "auto",
    yAxisRangeMin = 0,
    yAxisRangeMax = 10,
    xAxisLabelFontSize = 12,
    xAxisLabelRotation = 0,
    xAxisRangeType = "auto",
    xAxisRangeMin = 0,
    xAxisRangeMax = 10) {

    if ( ! requireNamespace("jmvcore", quietly=TRUE))
        stop("mrfrequencies requires jmvcore to be installed (restart may be required)")

    if ( ! missing(repVar)) repVar <- jmvcore::resolveQuo(jmvcore::enquo(repVar))
    if ( ! missing(resps)) resps <- jmvcore::resolveQuo(jmvcore::enquo(resps))
    if (missing(data))
        data <- jmvcore::marshalData(
            parent.frame(),
            `if`( ! missing(repVar), repVar, NULL),
            `if`( ! missing(resps), resps, NULL))

    for (v in repVar) if (v %in% names(data)) data[[v]] <- as.factor(data[[v]])
    for (v in resps) if (v %in% names(data)) data[[v]] <- as.factor(data[[v]])

    options <- mrfrequenciesOptions$new(
        mode = mode,
        repVar = repVar,
        separator = separator,
        emptyAsNA = emptyAsNA,
        resps = resps,
        endorsed = endorsed,
        optionname = optionname,
        order = order,
        showTotal = showTotal,
        showCounts = showCounts,
        labelPosition = labelPosition,
        showResponses = showResponses,
        showCases = showCases,
        yaxis = yaxis,
        horizontal = horizontal,
        showLabels = showLabels,
        accuracy = accuracy,
        labelFontSize = labelFontSize,
        colorPalette = colorPalette,
        singleColor = singleColor,
        colorNo = colorNo,
        borderColor = borderColor,
        textColor = textColor,
        titleText = titleText,
        titleFontFace = titleFontFace,
        titleFontSize = titleFontSize,
        titleAlign = titleAlign,
        subtitleText = subtitleText,
        subtitleFontFace = subtitleFontFace,
        subtitleFontSize = subtitleFontSize,
        subtitleAlign = subtitleAlign,
        captionText = captionText,
        captionFontFace = captionFontFace,
        captionFontSize = captionFontSize,
        captionAlign = captionAlign,
        xAxisText = xAxisText,
        xAxisFontSize = xAxisFontSize,
        xAxisPosition = xAxisPosition,
        yAxisText = yAxisText,
        yAxisFontSize = yAxisFontSize,
        yAxisPosition = yAxisPosition,
        yAxisLabelFontSize = yAxisLabelFontSize,
        yAxisLabelRotation = yAxisLabelRotation,
        yAxisRangeType = yAxisRangeType,
        yAxisRangeMin = yAxisRangeMin,
        yAxisRangeMax = yAxisRangeMax,
        xAxisLabelFontSize = xAxisLabelFontSize,
        xAxisLabelRotation = xAxisLabelRotation,
        xAxisRangeType = xAxisRangeType,
        xAxisRangeMin = xAxisRangeMin,
        xAxisRangeMax = xAxisRangeMax)

    analysis <- mrfrequenciesClass$new(
        options = options,
        data = data)

    analysis$run()

    analysis$results
}

