
# This file is automatically generated, you probably don't want to edit this

multcorrespOptions <- if (requireNamespace("jmvcore", quietly=TRUE)) R6::R6Class(
    "multcorrespOptions",
    inherit = jmvcore::Options,
    public = list(
        initialize = function(
            vars = NULL,
            supplVars = NULL,
            labelVar = NULL,
            method = "Indicator",
            BenzecriAdj = FALSE,
            GreenacreAdj = FALSE,
            dimNum = 2,
            xaxis = 1,
            yaxis = 2,
            normalization = "principal",
            showSummary = TRUE,
            showDiscriminations = FALSE,
            showCategories = TRUE,
            showObservations = FALSE,
            showDiscriminationPlot = FALSE,
            showCategoryPlot = TRUE,
            showObservationPlot = FALSE,
            showBiPlot = FALSE,
            discrimTitleText = "default",
            catTitleText = "default",
            obsTitleText = "default",
            biplotTitleText = "default",
            titleAlign = "0.5",
            titleFontSize = 16,
            titleFontFace = "plain",
            discrimSubtitleText = "",
            catSubtitleText = "default",
            obsSubtitleText = "default",
            biplotSubtitleText = "default",
            subtitleAlign = "0.5",
            subtitleFontSize = 12,
            subtitleFontFace = "plain",
            discrimCaptionText = "",
            catCaptionText = "",
            obsCaptionText = "",
            biplotCaptionText = "",
            captionAlign = "1",
            captionFontSize = 12,
            captionFontFace = "plain",
            obsColor = "black",
            colorPalette = "jmv",
            labelSize = 12,
            connectOrdinalCat = FALSE,
            propPoint = FALSE,
            ggrepel = FALSE,
            boldCat = FALSE,
            descAsVarName = FALSE,
            legendText = "",
            legendFontSize = "14",
            legendPosition = "right",
            xAxisText = "",
            xAxisFontSize = "16",
            xAxisPosition = "0.5",
            yAxisText = "",
            yAxisFontSize = "16",
            yAxisPosition = "0.5", ...) {

            super$initialize(
                package="vijPlots",
                name="multcorresp",
                requiresData=TRUE,
                ...)

            private$..vars <- jmvcore::OptionVariables$new(
                "vars",
                vars,
                suggested=list(
                    "nominal",
                    "ordinal"),
                permitted=list(
                    "factor"))
            private$..supplVars <- jmvcore::OptionVariables$new(
                "supplVars",
                supplVars,
                suggested=list(
                    "nominal",
                    "ordinal"),
                permitted=list(
                    "factor"))
            private$..labelVar <- jmvcore::OptionVariable$new(
                "labelVar",
                labelVar,
                suggested=list(
                    "nominal",
                    "id"),
                permitted=list(
                    "id",
                    "factor"))
            private$..method <- jmvcore::OptionList$new(
                "method",
                method,
                options=list(
                    "Indicator",
                    "Burt"),
                default="Indicator")
            private$..BenzecriAdj <- jmvcore::OptionBool$new(
                "BenzecriAdj",
                BenzecriAdj,
                default=FALSE)
            private$..GreenacreAdj <- jmvcore::OptionBool$new(
                "GreenacreAdj",
                GreenacreAdj,
                default=FALSE)
            private$..dimNum <- jmvcore::OptionNumber$new(
                "dimNum",
                dimNum,
                min=2,
                default=2)
            private$..xaxis <- jmvcore::OptionNumber$new(
                "xaxis",
                xaxis,
                min=1,
                default=1)
            private$..yaxis <- jmvcore::OptionNumber$new(
                "yaxis",
                yaxis,
                min=1,
                default=2)
            private$..normalization <- jmvcore::OptionList$new(
                "normalization",
                normalization,
                options=list(
                    "principal",
                    "catprincipal",
                    "obsprincipal",
                    "standard"),
                default="principal")
            private$..showSummary <- jmvcore::OptionBool$new(
                "showSummary",
                showSummary,
                default=TRUE)
            private$..showDiscriminations <- jmvcore::OptionBool$new(
                "showDiscriminations",
                showDiscriminations,
                default=FALSE)
            private$..showCategories <- jmvcore::OptionBool$new(
                "showCategories",
                showCategories,
                default=TRUE)
            private$..showObservations <- jmvcore::OptionBool$new(
                "showObservations",
                showObservations,
                default=FALSE)
            private$..showDiscriminationPlot <- jmvcore::OptionBool$new(
                "showDiscriminationPlot",
                showDiscriminationPlot,
                default=FALSE)
            private$..showCategoryPlot <- jmvcore::OptionBool$new(
                "showCategoryPlot",
                showCategoryPlot,
                default=TRUE)
            private$..showObservationPlot <- jmvcore::OptionBool$new(
                "showObservationPlot",
                showObservationPlot,
                default=FALSE)
            private$..showBiPlot <- jmvcore::OptionBool$new(
                "showBiPlot",
                showBiPlot,
                default=FALSE)
            private$..discrimTitleText <- jmvcore::OptionString$new(
                "discrimTitleText",
                discrimTitleText,
                default="default")
            private$..catTitleText <- jmvcore::OptionString$new(
                "catTitleText",
                catTitleText,
                default="default")
            private$..obsTitleText <- jmvcore::OptionString$new(
                "obsTitleText",
                obsTitleText,
                default="default")
            private$..biplotTitleText <- jmvcore::OptionString$new(
                "biplotTitleText",
                biplotTitleText,
                default="default")
            private$..titleAlign <- jmvcore::OptionList$new(
                "titleAlign",
                titleAlign,
                options=list(
                    "0",
                    "0.5",
                    "1"),
                default="0.5")
            private$..titleFontSize <- jmvcore::OptionNumber$new(
                "titleFontSize",
                titleFontSize,
                default=16,
                min=8,
                max=24)
            private$..titleFontFace <- jmvcore::OptionList$new(
                "titleFontFace",
                titleFontFace,
                options=list(
                    "plain",
                    "bold",
                    "italic",
                    "bold.italic"),
                default="plain")
            private$..discrimSubtitleText <- jmvcore::OptionString$new(
                "discrimSubtitleText",
                discrimSubtitleText,
                default="")
            private$..catSubtitleText <- jmvcore::OptionString$new(
                "catSubtitleText",
                catSubtitleText,
                default="default")
            private$..obsSubtitleText <- jmvcore::OptionString$new(
                "obsSubtitleText",
                obsSubtitleText,
                default="default")
            private$..biplotSubtitleText <- jmvcore::OptionString$new(
                "biplotSubtitleText",
                biplotSubtitleText,
                default="default")
            private$..subtitleAlign <- jmvcore::OptionList$new(
                "subtitleAlign",
                subtitleAlign,
                options=list(
                    "0",
                    "0.5",
                    "1"),
                default="0.5")
            private$..subtitleFontSize <- jmvcore::OptionNumber$new(
                "subtitleFontSize",
                subtitleFontSize,
                default=12,
                min=8,
                max=24)
            private$..subtitleFontFace <- jmvcore::OptionList$new(
                "subtitleFontFace",
                subtitleFontFace,
                options=list(
                    "plain",
                    "bold",
                    "italic",
                    "bold.italic"),
                default="plain")
            private$..discrimCaptionText <- jmvcore::OptionString$new(
                "discrimCaptionText",
                discrimCaptionText,
                default="")
            private$..catCaptionText <- jmvcore::OptionString$new(
                "catCaptionText",
                catCaptionText,
                default="")
            private$..obsCaptionText <- jmvcore::OptionString$new(
                "obsCaptionText",
                obsCaptionText,
                default="")
            private$..biplotCaptionText <- jmvcore::OptionString$new(
                "biplotCaptionText",
                biplotCaptionText,
                default="")
            private$..captionAlign <- jmvcore::OptionList$new(
                "captionAlign",
                captionAlign,
                options=list(
                    "0",
                    "0.5",
                    "1"),
                default="1")
            private$..captionFontSize <- jmvcore::OptionNumber$new(
                "captionFontSize",
                captionFontSize,
                default=12,
                min=8,
                max=24)
            private$..captionFontFace <- jmvcore::OptionList$new(
                "captionFontFace",
                captionFontFace,
                options=list(
                    "plain",
                    "bold",
                    "italic",
                    "bold.italic"),
                default="plain")
            private$..obsColor <- jmvcore::OptionList$new(
                "obsColor",
                obsColor,
                options=list(
                    "black",
                    "gray",
                    "darkgray",
                    "lightgray",
                    "blue",
                    "red"),
                default="black")
            private$..colorPalette <- jmvcore::OptionList$new(
                "colorPalette",
                colorPalette,
                options=list(
                    "jmv",
                    "Set1",
                    "Set2",
                    "Set3",
                    "Pastel1",
                    "Pastel2",
                    "Accent",
                    "Paired",
                    "Dark2",
                    "Spectral",
                    "RdYlGn",
                    "RdYlBu",
                    "RdGy",
                    "RdBu",
                    "PuOr",
                    "PRGn",
                    "PiYG",
                    "BrBG",
                    "Blues",
                    "Greens",
                    "Greys",
                    "Oranges",
                    "Purples",
                    "Reds",
                    "BuGn",
                    "BuPu",
                    "GnBu",
                    "OrRd",
                    "PuBu",
                    "PuBuGn",
                    "PuRd",
                    "RdPu",
                    "YlGn",
                    "YlGnBu",
                    "YlOrBr",
                    "YlOrRd",
                    "viridis::viridis",
                    "viridis::magma",
                    "viridis::inferno",
                    "viridis::plasma",
                    "viridis::turbo",
                    "dichromat::Categorical.12",
                    "tidy::friendly",
                    "tidy::seaside",
                    "tidy::apple",
                    "tidy::ibm",
                    "tidy::candy",
                    "tidy::alger",
                    "tidy::rainbow",
                    "tidy::metro",
                    "custom::carbon_dark",
                    "custom::carbon_light",
                    "custom::lemovice"),
                default="jmv")
            private$..labelSize <- jmvcore::OptionNumber$new(
                "labelSize",
                labelSize,
                default=12,
                min=8,
                max=24)
            private$..connectOrdinalCat <- jmvcore::OptionBool$new(
                "connectOrdinalCat",
                connectOrdinalCat,
                default=FALSE)
            private$..propPoint <- jmvcore::OptionBool$new(
                "propPoint",
                propPoint,
                default=FALSE)
            private$..ggrepel <- jmvcore::OptionBool$new(
                "ggrepel",
                ggrepel,
                default=FALSE)
            private$..boldCat <- jmvcore::OptionBool$new(
                "boldCat",
                boldCat,
                default=FALSE)
            private$..obsCoordOV <- jmvcore::OptionOutput$new(
                "obsCoordOV")
            private$..descAsVarName <- jmvcore::OptionBool$new(
                "descAsVarName",
                descAsVarName,
                default=FALSE)
            private$..legendText <- jmvcore::OptionString$new(
                "legendText",
                legendText,
                default="")
            private$..legendFontSize <- jmvcore::OptionList$new(
                "legendFontSize",
                legendFontSize,
                options=list(
                    "10",
                    "12",
                    "14",
                    "16",
                    "18",
                    "20"),
                default="14")
            private$..legendPosition <- jmvcore::OptionList$new(
                "legendPosition",
                legendPosition,
                options=list(
                    "right",
                    "bottom",
                    "left",
                    "top"),
                default="right")
            private$..xAxisText <- jmvcore::OptionString$new(
                "xAxisText",
                xAxisText,
                default="")
            private$..xAxisFontSize <- jmvcore::OptionList$new(
                "xAxisFontSize",
                xAxisFontSize,
                options=list(
                    "10",
                    "12",
                    "14",
                    "16",
                    "18",
                    "20"),
                default="16")
            private$..xAxisPosition <- jmvcore::OptionList$new(
                "xAxisPosition",
                xAxisPosition,
                options=list(
                    "0",
                    "0.5",
                    "1"),
                default="0.5")
            private$..yAxisText <- jmvcore::OptionString$new(
                "yAxisText",
                yAxisText,
                default="")
            private$..yAxisFontSize <- jmvcore::OptionList$new(
                "yAxisFontSize",
                yAxisFontSize,
                options=list(
                    "10",
                    "12",
                    "14",
                    "16",
                    "18",
                    "20"),
                default="16")
            private$..yAxisPosition <- jmvcore::OptionList$new(
                "yAxisPosition",
                yAxisPosition,
                options=list(
                    "1",
                    "0.5",
                    "0"),
                default="0.5")

            self$.addOption(private$..vars)
            self$.addOption(private$..supplVars)
            self$.addOption(private$..labelVar)
            self$.addOption(private$..method)
            self$.addOption(private$..BenzecriAdj)
            self$.addOption(private$..GreenacreAdj)
            self$.addOption(private$..dimNum)
            self$.addOption(private$..xaxis)
            self$.addOption(private$..yaxis)
            self$.addOption(private$..normalization)
            self$.addOption(private$..showSummary)
            self$.addOption(private$..showDiscriminations)
            self$.addOption(private$..showCategories)
            self$.addOption(private$..showObservations)
            self$.addOption(private$..showDiscriminationPlot)
            self$.addOption(private$..showCategoryPlot)
            self$.addOption(private$..showObservationPlot)
            self$.addOption(private$..showBiPlot)
            self$.addOption(private$..discrimTitleText)
            self$.addOption(private$..catTitleText)
            self$.addOption(private$..obsTitleText)
            self$.addOption(private$..biplotTitleText)
            self$.addOption(private$..titleAlign)
            self$.addOption(private$..titleFontSize)
            self$.addOption(private$..titleFontFace)
            self$.addOption(private$..discrimSubtitleText)
            self$.addOption(private$..catSubtitleText)
            self$.addOption(private$..obsSubtitleText)
            self$.addOption(private$..biplotSubtitleText)
            self$.addOption(private$..subtitleAlign)
            self$.addOption(private$..subtitleFontSize)
            self$.addOption(private$..subtitleFontFace)
            self$.addOption(private$..discrimCaptionText)
            self$.addOption(private$..catCaptionText)
            self$.addOption(private$..obsCaptionText)
            self$.addOption(private$..biplotCaptionText)
            self$.addOption(private$..captionAlign)
            self$.addOption(private$..captionFontSize)
            self$.addOption(private$..captionFontFace)
            self$.addOption(private$..obsColor)
            self$.addOption(private$..colorPalette)
            self$.addOption(private$..labelSize)
            self$.addOption(private$..connectOrdinalCat)
            self$.addOption(private$..propPoint)
            self$.addOption(private$..ggrepel)
            self$.addOption(private$..boldCat)
            self$.addOption(private$..obsCoordOV)
            self$.addOption(private$..descAsVarName)
            self$.addOption(private$..legendText)
            self$.addOption(private$..legendFontSize)
            self$.addOption(private$..legendPosition)
            self$.addOption(private$..xAxisText)
            self$.addOption(private$..xAxisFontSize)
            self$.addOption(private$..xAxisPosition)
            self$.addOption(private$..yAxisText)
            self$.addOption(private$..yAxisFontSize)
            self$.addOption(private$..yAxisPosition)
        }),
    active = list(
        vars = function() private$..vars$value,
        supplVars = function() private$..supplVars$value,
        labelVar = function() private$..labelVar$value,
        method = function() private$..method$value,
        BenzecriAdj = function() private$..BenzecriAdj$value,
        GreenacreAdj = function() private$..GreenacreAdj$value,
        dimNum = function() private$..dimNum$value,
        xaxis = function() private$..xaxis$value,
        yaxis = function() private$..yaxis$value,
        normalization = function() private$..normalization$value,
        showSummary = function() private$..showSummary$value,
        showDiscriminations = function() private$..showDiscriminations$value,
        showCategories = function() private$..showCategories$value,
        showObservations = function() private$..showObservations$value,
        showDiscriminationPlot = function() private$..showDiscriminationPlot$value,
        showCategoryPlot = function() private$..showCategoryPlot$value,
        showObservationPlot = function() private$..showObservationPlot$value,
        showBiPlot = function() private$..showBiPlot$value,
        discrimTitleText = function() private$..discrimTitleText$value,
        catTitleText = function() private$..catTitleText$value,
        obsTitleText = function() private$..obsTitleText$value,
        biplotTitleText = function() private$..biplotTitleText$value,
        titleAlign = function() private$..titleAlign$value,
        titleFontSize = function() private$..titleFontSize$value,
        titleFontFace = function() private$..titleFontFace$value,
        discrimSubtitleText = function() private$..discrimSubtitleText$value,
        catSubtitleText = function() private$..catSubtitleText$value,
        obsSubtitleText = function() private$..obsSubtitleText$value,
        biplotSubtitleText = function() private$..biplotSubtitleText$value,
        subtitleAlign = function() private$..subtitleAlign$value,
        subtitleFontSize = function() private$..subtitleFontSize$value,
        subtitleFontFace = function() private$..subtitleFontFace$value,
        discrimCaptionText = function() private$..discrimCaptionText$value,
        catCaptionText = function() private$..catCaptionText$value,
        obsCaptionText = function() private$..obsCaptionText$value,
        biplotCaptionText = function() private$..biplotCaptionText$value,
        captionAlign = function() private$..captionAlign$value,
        captionFontSize = function() private$..captionFontSize$value,
        captionFontFace = function() private$..captionFontFace$value,
        obsColor = function() private$..obsColor$value,
        colorPalette = function() private$..colorPalette$value,
        labelSize = function() private$..labelSize$value,
        connectOrdinalCat = function() private$..connectOrdinalCat$value,
        propPoint = function() private$..propPoint$value,
        ggrepel = function() private$..ggrepel$value,
        boldCat = function() private$..boldCat$value,
        obsCoordOV = function() private$..obsCoordOV$value,
        descAsVarName = function() private$..descAsVarName$value,
        legendText = function() private$..legendText$value,
        legendFontSize = function() private$..legendFontSize$value,
        legendPosition = function() private$..legendPosition$value,
        xAxisText = function() private$..xAxisText$value,
        xAxisFontSize = function() private$..xAxisFontSize$value,
        xAxisPosition = function() private$..xAxisPosition$value,
        yAxisText = function() private$..yAxisText$value,
        yAxisFontSize = function() private$..yAxisFontSize$value,
        yAxisPosition = function() private$..yAxisPosition$value),
    private = list(
        ..vars = NA,
        ..supplVars = NA,
        ..labelVar = NA,
        ..method = NA,
        ..BenzecriAdj = NA,
        ..GreenacreAdj = NA,
        ..dimNum = NA,
        ..xaxis = NA,
        ..yaxis = NA,
        ..normalization = NA,
        ..showSummary = NA,
        ..showDiscriminations = NA,
        ..showCategories = NA,
        ..showObservations = NA,
        ..showDiscriminationPlot = NA,
        ..showCategoryPlot = NA,
        ..showObservationPlot = NA,
        ..showBiPlot = NA,
        ..discrimTitleText = NA,
        ..catTitleText = NA,
        ..obsTitleText = NA,
        ..biplotTitleText = NA,
        ..titleAlign = NA,
        ..titleFontSize = NA,
        ..titleFontFace = NA,
        ..discrimSubtitleText = NA,
        ..catSubtitleText = NA,
        ..obsSubtitleText = NA,
        ..biplotSubtitleText = NA,
        ..subtitleAlign = NA,
        ..subtitleFontSize = NA,
        ..subtitleFontFace = NA,
        ..discrimCaptionText = NA,
        ..catCaptionText = NA,
        ..obsCaptionText = NA,
        ..biplotCaptionText = NA,
        ..captionAlign = NA,
        ..captionFontSize = NA,
        ..captionFontFace = NA,
        ..obsColor = NA,
        ..colorPalette = NA,
        ..labelSize = NA,
        ..connectOrdinalCat = NA,
        ..propPoint = NA,
        ..ggrepel = NA,
        ..boldCat = NA,
        ..obsCoordOV = NA,
        ..descAsVarName = NA,
        ..legendText = NA,
        ..legendFontSize = NA,
        ..legendPosition = NA,
        ..xAxisText = NA,
        ..xAxisFontSize = NA,
        ..xAxisPosition = NA,
        ..yAxisText = NA,
        ..yAxisFontSize = NA,
        ..yAxisPosition = NA)
)

multcorrespResults <- if (requireNamespace("jmvcore", quietly=TRUE)) R6::R6Class(
    "multcorrespResults",
    inherit = jmvcore::Group,
    active = list(
        eigenvalues = function() private$.items[["eigenvalues"]],
        discrim = function() private$.items[["discrim"]],
        categories = function() private$.items[["categories"]],
        observations = function() private$.items[["observations"]],
        discrimplot = function() private$.items[["discrimplot"]],
        categoryplot = function() private$.items[["categoryplot"]],
        obsplot = function() private$.items[["obsplot"]],
        biplot = function() private$.items[["biplot"]],
        obsCoordOV = function() private$.items[["obsCoordOV"]]),
    private = list(),
    public=list(
        initialize=function(options) {
            super$initialize(
                options=options,
                name="",
                title="Multiple Correspondence Analysis",
                refs=list(
                    "factominer"))
            self$add(jmvcore::Table$new(
                options=options,
                name="eigenvalues",
                title="Summary",
                visible="(showSummary)",
                rows=0,
                columns=list(
                    list(
                        `name`="dim", 
                        `title`="Dimension", 
                        `type`="number"),
                    list(
                        `name`="inertia", 
                        `title`="Inertia", 
                        `superTitle`="Original Eigenvalues", 
                        `type`="number", 
                        `format`="zto"),
                    list(
                        `name`="proportion", 
                        `title`="% of Inertia", 
                        `superTitle`="Original Eigenvalues", 
                        `type`="integer", 
                        `format`="pc"),
                    list(
                        `name`="cumulative", 
                        `title`="Cumulative %", 
                        `superTitle`="Original Eigenvalues", 
                        `type`="number", 
                        `format`="pc")),
                clearWith=list(
                    "dimNum",
                    "vars",
                    "supplVars",
                    "method",
                    "BenzecriAdj",
                    "GreenacreAdj")))
            self$add(jmvcore::Table$new(
                options=options,
                name="discrim",
                title="Variable Discriminations",
                visible="(showDiscriminations)",
                columns=list(
                    list(
                        `name`="var", 
                        `title`="Variable", 
                        `type`="text")),
                clearWith=list(
                    "vars",
                    "supplVars",
                    "method",
                    "dimNum",
                    "descAsVarName")))
            self$add(jmvcore::Table$new(
                options=options,
                name="categories",
                title="Category Summary",
                visible="(showCategories)",
                rows=0,
                columns=list(
                    list(
                        `name`="factor", 
                        `title`="Factor", 
                        `type`="text", 
                        `combineBelow`=TRUE),
                    list(
                        `name`="level", 
                        `title`="Level", 
                        `type`="text"),
                    list(
                        `name`="mass", 
                        `title`="Mass", 
                        `type`="number", 
                        `format`="zto"),
                    list(
                        `name`="inertia", 
                        `title`="% Inertia", 
                        `type`="number", 
                        `format`="zto"),
                    list(
                        `name`="qlt", 
                        `title`="QLT", 
                        `type`="number", 
                        `format`="zto")),
                clearWith=list(
                    "vars",
                    "supplVars",
                    "method",
                    "normalization",
                    "dimNum",
                    "descAsVarName")))
            self$add(jmvcore::Table$new(
                options=options,
                name="observations",
                title="Observation Summary",
                visible="(showObservations)",
                rows=0,
                columns=list(
                    list(
                        `name`="name", 
                        `title`="Name", 
                        `type`="text"),
                    list(
                        `name`="mass", 
                        `title`="Mass", 
                        `type`="number", 
                        `format`="zto")),
                clearWith=list(
                    "vars",
                    "supplVars",
                    "method",
                    "normalization",
                    "dimNum")))
            self$add(jmvcore::Image$new(
                options=options,
                name="discrimplot",
                title="Discrimination Plot",
                visible="(showDiscriminationPlot)",
                width=600,
                height=600,
                renderFun=".discrimplot",
                clearWith=list(
                    "dimNum",
                    "vars",
                    "supplVars",
                    "method",
                    "normalization",
                    "xaxis",
                    "yaxis",
                    "discrimTitleText",
                    "titleFontFace",
                    "titleFontSize",
                    "titleAlign",
                    "discrimSubtitleText",
                    "subtitleFontFace",
                    "subtitleFontSize",
                    "subtitleAlign",
                    "discrimCaptionText",
                    "captionFontFace",
                    "captionFontSize",
                    "captionAlign",
                    "xAxisText",
                    "xAxisFontSize",
                    "xAxisPosition",
                    "yAxisText",
                    "yAxisFontSize",
                    "yAxisPosition",
                    "labelSize",
                    "descAsVarName")))
            self$add(jmvcore::Image$new(
                options=options,
                name="categoryplot",
                title="Category Plot",
                visible="(showCategoryPlot)",
                width=650,
                height=600,
                renderFun=".categoryplot",
                clearWith=list(
                    "dimNum",
                    "vars",
                    "supplVars",
                    "method",
                    "normalization",
                    "xaxis",
                    "yaxis",
                    "catTitleText",
                    "titleFontFace",
                    "titleFontSize",
                    "titleAlign",
                    "catSubtitleText",
                    "subtitleFontFace",
                    "subtitleFontSize",
                    "subtitleAlign",
                    "catCaptionText",
                    "captionFontFace",
                    "captionFontSize",
                    "captionAlign",
                    "xAxisText",
                    "xAxisFontSize",
                    "xAxisPosition",
                    "yAxisText",
                    "yAxisFontSize",
                    "yAxisPosition",
                    "legendText",
                    "legendFontSize",
                    "legendPosition",
                    "colorPalette",
                    "labelSize",
                    "connectOrdinalCat",
                    "descAsVarName",
                    "boldCat")))
            self$add(jmvcore::Image$new(
                options=options,
                name="obsplot",
                title="Observation Plot",
                visible="(showObservationPlot)",
                width=600,
                height=600,
                renderFun=".obsplot",
                clearWith=list(
                    "dimNum",
                    "vars",
                    "supplVars",
                    "labelVar",
                    "method",
                    "normalization",
                    "xaxis",
                    "yaxis",
                    "obsTitleText",
                    "titleFontFace",
                    "titleFontSize",
                    "titleAlign",
                    "obsSubtitleText",
                    "subtitleFontFace",
                    "subtitleFontSize",
                    "subtitleAlign",
                    "obsCaptionText",
                    "captionFontFace",
                    "captionFontSize",
                    "captionAlign",
                    "xAxisText",
                    "xAxisFontSize",
                    "xAxisPosition",
                    "yAxisText",
                    "yAxisFontSize",
                    "yAxisPosition",
                    "legendText",
                    "legendFontSize",
                    "legendPosition",
                    "obsColor",
                    "labelSize",
                    "propPoint",
                    "ggrepel")))
            self$add(jmvcore::Image$new(
                options=options,
                name="biplot",
                title="Biplot",
                visible="(showBiPlot)",
                width=650,
                height=600,
                renderFun=".biplot",
                clearWith=list(
                    "dimNum",
                    "vars",
                    "supplVars",
                    "labelVar",
                    "method",
                    "normalization",
                    "xaxis",
                    "yaxis",
                    "biplotTitleText",
                    "titleFontFace",
                    "titleFontSize",
                    "titleAlign",
                    "biplotSubtitleText",
                    "subtitleFontFace",
                    "subtitleFontSize",
                    "subtitleAlign",
                    "biplotCaptionText",
                    "captionFontFace",
                    "captionFontSize",
                    "captionAlign",
                    "xAxisText",
                    "xAxisFontSize",
                    "xAxisPosition",
                    "yAxisText",
                    "yAxisFontSize",
                    "yAxisPosition",
                    "legendText",
                    "legendFontSize",
                    "legendPosition",
                    "obsColor",
                    "colorPalette",
                    "labelSize",
                    "connectOrdinalCat",
                    "propPoint",
                    "descAsVarName",
                    "ggrepel",
                    "boldCat")))
            self$add(jmvcore::Output$new(
                options=options,
                name="obsCoordOV",
                title="Observation Coordinates",
                initInRun=TRUE,
                clearWith=list(
                    "vars",
                    "supplVars",
                    "method",
                    "normalization",
                    "dimNum")))}))

multcorrespBase <- if (requireNamespace("jmvcore", quietly=TRUE)) R6::R6Class(
    "multcorrespBase",
    inherit = jmvcore::Analysis,
    public = list(
        initialize = function(options, data=NULL, datasetId="", analysisId="", revision=0) {
            super$initialize(
                package = "vijPlots",
                name = "multcorresp",
                version = c(1,0,0),
                options = options,
                results = multcorrespResults$new(options=options),
                data = data,
                datasetId = datasetId,
                analysisId = analysisId,
                revision = revision,
                pause = NULL,
                completeWhenFilled = FALSE,
                requiresMissings = FALSE,
                weightsSupport = 'none')
        }))

#' Multiple Correspondence Analysis
#'
#' 
#' @param data .
#' @param vars .
#' @param supplVars .
#' @param labelVar .
#' @param method .
#' @param BenzecriAdj .
#' @param GreenacreAdj .
#' @param dimNum .
#' @param xaxis .
#' @param yaxis .
#' @param normalization .
#' @param showSummary .
#' @param showDiscriminations .
#' @param showCategories .
#' @param showObservations .
#' @param showDiscriminationPlot .
#' @param showCategoryPlot .
#' @param showObservationPlot .
#' @param showBiPlot .
#' @param discrimTitleText .
#' @param catTitleText .
#' @param obsTitleText .
#' @param biplotTitleText .
#' @param titleAlign .
#' @param titleFontSize .
#' @param titleFontFace .
#' @param discrimSubtitleText .
#' @param catSubtitleText .
#' @param obsSubtitleText .
#' @param biplotSubtitleText .
#' @param subtitleAlign .
#' @param subtitleFontSize .
#' @param subtitleFontFace .
#' @param discrimCaptionText .
#' @param catCaptionText .
#' @param obsCaptionText .
#' @param biplotCaptionText .
#' @param captionAlign .
#' @param captionFontSize .
#' @param captionFontFace .
#' @param obsColor .
#' @param colorPalette .
#' @param labelSize .
#' @param connectOrdinalCat .
#' @param propPoint .
#' @param ggrepel .
#' @param boldCat .
#' @param descAsVarName .
#' @param legendText .
#' @param legendFontSize .
#' @param legendPosition .
#' @param xAxisText .
#' @param xAxisFontSize .
#' @param xAxisPosition .
#' @param yAxisText .
#' @param yAxisFontSize .
#' @param yAxisPosition .
#' @return A results object containing:
#' \tabular{llllll}{
#'   \code{results$eigenvalues} \tab \tab \tab \tab \tab a table \cr
#'   \code{results$discrim} \tab \tab \tab \tab \tab a table \cr
#'   \code{results$categories} \tab \tab \tab \tab \tab a table \cr
#'   \code{results$observations} \tab \tab \tab \tab \tab a table \cr
#'   \code{results$discrimplot} \tab \tab \tab \tab \tab an image \cr
#'   \code{results$categoryplot} \tab \tab \tab \tab \tab an image \cr
#'   \code{results$obsplot} \tab \tab \tab \tab \tab an image \cr
#'   \code{results$biplot} \tab \tab \tab \tab \tab an image \cr
#'   \code{results$obsCoordOV} \tab \tab \tab \tab \tab an output \cr
#' }
#'
#' Tables can be converted to data frames with \code{asDF} or \code{\link{as.data.frame}}. For example:
#'
#' \code{results$eigenvalues$asDF}
#'
#' \code{as.data.frame(results$eigenvalues)}
#'
#' @export
multcorresp <- function(
    data,
    vars,
    supplVars,
    labelVar,
    method = "Indicator",
    BenzecriAdj = FALSE,
    GreenacreAdj = FALSE,
    dimNum = 2,
    xaxis = 1,
    yaxis = 2,
    normalization = "principal",
    showSummary = TRUE,
    showDiscriminations = FALSE,
    showCategories = TRUE,
    showObservations = FALSE,
    showDiscriminationPlot = FALSE,
    showCategoryPlot = TRUE,
    showObservationPlot = FALSE,
    showBiPlot = FALSE,
    discrimTitleText = "default",
    catTitleText = "default",
    obsTitleText = "default",
    biplotTitleText = "default",
    titleAlign = "0.5",
    titleFontSize = 16,
    titleFontFace = "plain",
    discrimSubtitleText = "",
    catSubtitleText = "default",
    obsSubtitleText = "default",
    biplotSubtitleText = "default",
    subtitleAlign = "0.5",
    subtitleFontSize = 12,
    subtitleFontFace = "plain",
    discrimCaptionText = "",
    catCaptionText = "",
    obsCaptionText = "",
    biplotCaptionText = "",
    captionAlign = "1",
    captionFontSize = 12,
    captionFontFace = "plain",
    obsColor = "black",
    colorPalette = "jmv",
    labelSize = 12,
    connectOrdinalCat = FALSE,
    propPoint = FALSE,
    ggrepel = FALSE,
    boldCat = FALSE,
    descAsVarName = FALSE,
    legendText = "",
    legendFontSize = "14",
    legendPosition = "right",
    xAxisText = "",
    xAxisFontSize = "16",
    xAxisPosition = "0.5",
    yAxisText = "",
    yAxisFontSize = "16",
    yAxisPosition = "0.5") {

    if ( ! requireNamespace("jmvcore", quietly=TRUE))
        stop("multcorresp requires jmvcore to be installed (restart may be required)")

    if ( ! missing(vars)) vars <- jmvcore::resolveQuo(jmvcore::enquo(vars))
    if ( ! missing(supplVars)) supplVars <- jmvcore::resolveQuo(jmvcore::enquo(supplVars))
    if ( ! missing(labelVar)) labelVar <- jmvcore::resolveQuo(jmvcore::enquo(labelVar))
    if (missing(data))
        data <- jmvcore::marshalData(
            parent.frame(),
            `if`( ! missing(vars), vars, NULL),
            `if`( ! missing(supplVars), supplVars, NULL),
            `if`( ! missing(labelVar), labelVar, NULL))

    for (v in vars) if (v %in% names(data)) data[[v]] <- as.factor(data[[v]])
    for (v in supplVars) if (v %in% names(data)) data[[v]] <- as.factor(data[[v]])

    options <- multcorrespOptions$new(
        vars = vars,
        supplVars = supplVars,
        labelVar = labelVar,
        method = method,
        BenzecriAdj = BenzecriAdj,
        GreenacreAdj = GreenacreAdj,
        dimNum = dimNum,
        xaxis = xaxis,
        yaxis = yaxis,
        normalization = normalization,
        showSummary = showSummary,
        showDiscriminations = showDiscriminations,
        showCategories = showCategories,
        showObservations = showObservations,
        showDiscriminationPlot = showDiscriminationPlot,
        showCategoryPlot = showCategoryPlot,
        showObservationPlot = showObservationPlot,
        showBiPlot = showBiPlot,
        discrimTitleText = discrimTitleText,
        catTitleText = catTitleText,
        obsTitleText = obsTitleText,
        biplotTitleText = biplotTitleText,
        titleAlign = titleAlign,
        titleFontSize = titleFontSize,
        titleFontFace = titleFontFace,
        discrimSubtitleText = discrimSubtitleText,
        catSubtitleText = catSubtitleText,
        obsSubtitleText = obsSubtitleText,
        biplotSubtitleText = biplotSubtitleText,
        subtitleAlign = subtitleAlign,
        subtitleFontSize = subtitleFontSize,
        subtitleFontFace = subtitleFontFace,
        discrimCaptionText = discrimCaptionText,
        catCaptionText = catCaptionText,
        obsCaptionText = obsCaptionText,
        biplotCaptionText = biplotCaptionText,
        captionAlign = captionAlign,
        captionFontSize = captionFontSize,
        captionFontFace = captionFontFace,
        obsColor = obsColor,
        colorPalette = colorPalette,
        labelSize = labelSize,
        connectOrdinalCat = connectOrdinalCat,
        propPoint = propPoint,
        ggrepel = ggrepel,
        boldCat = boldCat,
        descAsVarName = descAsVarName,
        legendText = legendText,
        legendFontSize = legendFontSize,
        legendPosition = legendPosition,
        xAxisText = xAxisText,
        xAxisFontSize = xAxisFontSize,
        xAxisPosition = xAxisPosition,
        yAxisText = yAxisText,
        yAxisFontSize = yAxisFontSize,
        yAxisPosition = yAxisPosition)

    analysis <- multcorrespClass$new(
        options = options,
        data = data)

    analysis$run()

    analysis$results
}

