
# This file is automatically generated, you probably don't want to edit this

principalOptions <- if (requireNamespace("jmvcore", quietly=TRUE)) R6::R6Class(
    "principalOptions",
    inherit = jmvcore::Options,
    public = list(
        initialize = function(
            vars = NULL,
            labelVar = NULL,
            groupVar = NULL,
            rotation = "none",
            dimNum = 2,
            xaxis = 1,
            yaxis = 2,
            stdVariables = TRUE,
            showSummary = TRUE,
            showKMO = FALSE,
            showLoadings = FALSE,
            showObservations = FALSE,
            showScreePlot = TRUE,
            showVarPlot = TRUE,
            showObsPlot = TRUE,
            showBiplot = FALSE,
            biplotType = "formPlot",
            biplotLines = FALSE,
            biplotStretch = FALSE,
            biplotStretchFactor = 1,
            obsLabelSize = 10,
            varLabelSize = 12,
            pointSize = 3,
            varColor = "#377EB8",
            labelColor = "none",
            obsColor = "#E41A1C",
            colorPalette = "jmv",
            screeTitleText = "default",
            varTitleText = "default",
            obsTitleText = "default",
            biplotTitleText = "default",
            titleAlign = "0.5",
            titleFontSize = 16,
            titleFontFace = "plain",
            screeSubtitleText = NULL,
            varSubtitleText = "default",
            obsSubtitleText = "default",
            biplotSubtitleText = "default",
            subtitleAlign = "0.5",
            subtitleFontSize = 12,
            subtitleFontFace = "plain",
            screeCaptionText = NULL,
            varCaptionText = "default",
            obsCaptionText = "default",
            biplotCaptionText = NULL,
            captionAlign = "1",
            captionFontSize = 12,
            captionFontFace = "plain",
            kaiser = FALSE,
            descAsVarName = FALSE,
            stdScores = FALSE,
            stdLoadings = FALSE,
            stataRotation = FALSE,
            legendText = NULL,
            legendFontSize = "14",
            legendPosition = "right",
            xAxisText = NULL,
            xAxisFontSize = "16",
            xAxisPosition = "0.5",
            yAxisText = NULL,
            yAxisFontSize = "16",
            yAxisPosition = "0.5", ...) {

            super$initialize(
                package="vijPlots",
                name="principal",
                requiresData=TRUE,
                ...)

            private$..vars <- jmvcore::OptionVariables$new(
                "vars",
                vars,
                suggested=list(
                    "ordinal",
                    "continuous"),
                permitted=list(
                    "numeric"))
            private$..labelVar <- jmvcore::OptionVariable$new(
                "labelVar",
                labelVar,
                suggested=list(
                    "nominal",
                    "id"),
                permitted=list(
                    "id",
                    "factor"))
            private$..groupVar <- jmvcore::OptionVariable$new(
                "groupVar",
                groupVar,
                suggested=list(
                    "nominal",
                    "ordinal"),
                permitted=list(
                    "factor"))
            private$..rotation <- jmvcore::OptionList$new(
                "rotation",
                rotation,
                options=list(
                    "none",
                    "Varimax",
                    "quartimax",
                    "equamax",
                    "parsimax",
                    "entropy",
                    "bentlerT"),
                default="none")
            private$..dimNum <- jmvcore::OptionNumber$new(
                "dimNum",
                dimNum,
                min=2,
                max=99,
                default=2)
            private$..xaxis <- jmvcore::OptionNumber$new(
                "xaxis",
                xaxis,
                min=1,
                max=99,
                default=1)
            private$..yaxis <- jmvcore::OptionNumber$new(
                "yaxis",
                yaxis,
                min=1,
                max=99,
                default=2)
            private$..stdVariables <- jmvcore::OptionBool$new(
                "stdVariables",
                stdVariables,
                default=TRUE)
            private$..showSummary <- jmvcore::OptionBool$new(
                "showSummary",
                showSummary,
                default=TRUE)
            private$..showKMO <- jmvcore::OptionBool$new(
                "showKMO",
                showKMO,
                default=FALSE)
            private$..showLoadings <- jmvcore::OptionBool$new(
                "showLoadings",
                showLoadings,
                default=FALSE)
            private$..showObservations <- jmvcore::OptionBool$new(
                "showObservations",
                showObservations,
                default=FALSE)
            private$..showScreePlot <- jmvcore::OptionBool$new(
                "showScreePlot",
                showScreePlot,
                default=TRUE)
            private$..showVarPlot <- jmvcore::OptionBool$new(
                "showVarPlot",
                showVarPlot,
                default=TRUE)
            private$..showObsPlot <- jmvcore::OptionBool$new(
                "showObsPlot",
                showObsPlot,
                default=TRUE)
            private$..showBiplot <- jmvcore::OptionBool$new(
                "showBiplot",
                showBiplot,
                default=FALSE)
            private$..biplotType <- jmvcore::OptionList$new(
                "biplotType",
                biplotType,
                options=list(
                    "formPlot",
                    "covPlot"),
                default="formPlot")
            private$..biplotLines <- jmvcore::OptionBool$new(
                "biplotLines",
                biplotLines,
                default=FALSE)
            private$..biplotStretch <- jmvcore::OptionBool$new(
                "biplotStretch",
                biplotStretch,
                default=FALSE)
            private$..biplotStretchFactor <- jmvcore::OptionNumber$new(
                "biplotStretchFactor",
                biplotStretchFactor,
                default=1,
                min=0.1,
                max=10)
            private$..obsLabelSize <- jmvcore::OptionNumber$new(
                "obsLabelSize",
                obsLabelSize,
                min=4,
                max=24,
                default=10)
            private$..varLabelSize <- jmvcore::OptionNumber$new(
                "varLabelSize",
                varLabelSize,
                min=4,
                max=24,
                default=12)
            private$..pointSize <- jmvcore::OptionNumber$new(
                "pointSize",
                pointSize,
                min=1,
                max=10,
                default=3)
            private$..varColor <- jmvcore::OptionList$new(
                "varColor",
                varColor,
                options=list(
                    "black",
                    "#A6C4F1",
                    "#C5C5C5",
                    "#F0CD8C",
                    "#88C38B",
                    "#E18A8A",
                    "#E41A1C",
                    "#377EB8",
                    "#4DAF4A",
                    "#984EA3",
                    "#FF7F00",
                    "#FFFF33",
                    "#A65628",
                    "#F781BF",
                    "#999999",
                    "#FBB4AE",
                    "#B3CDE3",
                    "#CCEBC5",
                    "#DECBE4",
                    "#FED9A6",
                    "#FFFFCC",
                    "#E5D8BD",
                    "#FDDAEC",
                    "#F2F2F2"),
                default="#377EB8")
            private$..labelColor <- jmvcore::OptionList$new(
                "labelColor",
                labelColor,
                options=list(
                    "black",
                    "none"),
                default="none")
            private$..obsColor <- jmvcore::OptionList$new(
                "obsColor",
                obsColor,
                options=list(
                    "black",
                    "#A6C4F1",
                    "#C5C5C5",
                    "#F0CD8C",
                    "#88C38B",
                    "#E18A8A",
                    "#E41A1C",
                    "#377EB8",
                    "#4DAF4A",
                    "#984EA3",
                    "#FF7F00",
                    "#FFFF33",
                    "#A65628",
                    "#F781BF",
                    "#999999",
                    "#FBB4AE",
                    "#B3CDE3",
                    "#CCEBC5",
                    "#DECBE4",
                    "#FED9A6",
                    "#FFFFCC",
                    "#E5D8BD",
                    "#FDDAEC",
                    "#F2F2F2"),
                default="#E41A1C")
            private$..colorPalette <- jmvcore::OptionList$new(
                "colorPalette",
                colorPalette,
                options=list(
                    "jmv",
                    "Set1",
                    "Set2",
                    "Set3",
                    "Pastel1",
                    "Pastel2",
                    "Accent",
                    "Paired",
                    "Dark2",
                    "Spectral",
                    "RdYlGn",
                    "RdYlBu",
                    "RdGy",
                    "RdBu",
                    "PuOr",
                    "PRGn",
                    "PiYG",
                    "BrBG",
                    "Blues",
                    "Greens",
                    "Greys",
                    "Oranges",
                    "Purples",
                    "Reds",
                    "BuGn",
                    "BuPu",
                    "GnBu",
                    "OrRd",
                    "PuBu",
                    "PuBuGn",
                    "PuRd",
                    "RdPu",
                    "YlGn",
                    "YlGnBu",
                    "YlOrBr",
                    "YlOrRd",
                    "viridis::viridis",
                    "viridis::magma",
                    "viridis::inferno",
                    "viridis::plasma",
                    "viridis::turbo",
                    "dichromat::Categorical.12",
                    "tidy::friendly",
                    "tidy::seaside",
                    "tidy::apple",
                    "tidy::ibm",
                    "tidy::candy",
                    "tidy::alger",
                    "tidy::rainbow",
                    "tidy::metro",
                    "custom::lemovice"),
                default="jmv")
            private$..screeTitleText <- jmvcore::OptionString$new(
                "screeTitleText",
                screeTitleText,
                default="default")
            private$..varTitleText <- jmvcore::OptionString$new(
                "varTitleText",
                varTitleText,
                default="default")
            private$..obsTitleText <- jmvcore::OptionString$new(
                "obsTitleText",
                obsTitleText,
                default="default")
            private$..biplotTitleText <- jmvcore::OptionString$new(
                "biplotTitleText",
                biplotTitleText,
                default="default")
            private$..titleAlign <- jmvcore::OptionList$new(
                "titleAlign",
                titleAlign,
                options=list(
                    "0",
                    "0.5",
                    "1"),
                default="0.5")
            private$..titleFontSize <- jmvcore::OptionNumber$new(
                "titleFontSize",
                titleFontSize,
                default=16)
            private$..titleFontFace <- jmvcore::OptionList$new(
                "titleFontFace",
                titleFontFace,
                options=list(
                    "plain",
                    "bold",
                    "italic",
                    "bold.italic"),
                default="plain")
            private$..screeSubtitleText <- jmvcore::OptionString$new(
                "screeSubtitleText",
                screeSubtitleText)
            private$..varSubtitleText <- jmvcore::OptionString$new(
                "varSubtitleText",
                varSubtitleText,
                default="default")
            private$..obsSubtitleText <- jmvcore::OptionString$new(
                "obsSubtitleText",
                obsSubtitleText,
                default="default")
            private$..biplotSubtitleText <- jmvcore::OptionString$new(
                "biplotSubtitleText",
                biplotSubtitleText,
                default="default")
            private$..subtitleAlign <- jmvcore::OptionList$new(
                "subtitleAlign",
                subtitleAlign,
                options=list(
                    "0",
                    "0.5",
                    "1"),
                default="0.5")
            private$..subtitleFontSize <- jmvcore::OptionNumber$new(
                "subtitleFontSize",
                subtitleFontSize,
                default=12)
            private$..subtitleFontFace <- jmvcore::OptionList$new(
                "subtitleFontFace",
                subtitleFontFace,
                options=list(
                    "plain",
                    "bold",
                    "italic",
                    "bold.italic"),
                default="plain")
            private$..screeCaptionText <- jmvcore::OptionString$new(
                "screeCaptionText",
                screeCaptionText)
            private$..varCaptionText <- jmvcore::OptionString$new(
                "varCaptionText",
                varCaptionText,
                default="default")
            private$..obsCaptionText <- jmvcore::OptionString$new(
                "obsCaptionText",
                obsCaptionText,
                default="default")
            private$..biplotCaptionText <- jmvcore::OptionString$new(
                "biplotCaptionText",
                biplotCaptionText)
            private$..captionAlign <- jmvcore::OptionList$new(
                "captionAlign",
                captionAlign,
                options=list(
                    "0",
                    "0.5",
                    "1"),
                default="1")
            private$..captionFontSize <- jmvcore::OptionNumber$new(
                "captionFontSize",
                captionFontSize,
                default=12,
                min=8,
                max=24)
            private$..captionFontFace <- jmvcore::OptionList$new(
                "captionFontFace",
                captionFontFace,
                options=list(
                    "plain",
                    "bold",
                    "italic",
                    "bold.italic"),
                default="plain")
            private$..kaiser <- jmvcore::OptionBool$new(
                "kaiser",
                kaiser,
                default=FALSE)
            private$..descAsVarName <- jmvcore::OptionBool$new(
                "descAsVarName",
                descAsVarName,
                default=FALSE)
            private$..stdScores <- jmvcore::OptionBool$new(
                "stdScores",
                stdScores,
                default=FALSE)
            private$..stdLoadings <- jmvcore::OptionBool$new(
                "stdLoadings",
                stdLoadings,
                default=FALSE)
            private$..stataRotation <- jmvcore::OptionBool$new(
                "stataRotation",
                stataRotation,
                default=FALSE)
            private$..obsCoordOV <- jmvcore::OptionOutput$new(
                "obsCoordOV")
            private$..legendText <- jmvcore::OptionString$new(
                "legendText",
                legendText)
            private$..legendFontSize <- jmvcore::OptionList$new(
                "legendFontSize",
                legendFontSize,
                options=list(
                    "10",
                    "12",
                    "14",
                    "16",
                    "18",
                    "20"),
                default="14")
            private$..legendPosition <- jmvcore::OptionList$new(
                "legendPosition",
                legendPosition,
                options=list(
                    "right",
                    "bottom",
                    "left",
                    "top"),
                default="right")
            private$..xAxisText <- jmvcore::OptionString$new(
                "xAxisText",
                xAxisText)
            private$..xAxisFontSize <- jmvcore::OptionList$new(
                "xAxisFontSize",
                xAxisFontSize,
                options=list(
                    "10",
                    "12",
                    "14",
                    "16",
                    "18",
                    "20"),
                default="16")
            private$..xAxisPosition <- jmvcore::OptionList$new(
                "xAxisPosition",
                xAxisPosition,
                options=list(
                    "0",
                    "0.5",
                    "1"),
                default="0.5")
            private$..yAxisText <- jmvcore::OptionString$new(
                "yAxisText",
                yAxisText)
            private$..yAxisFontSize <- jmvcore::OptionList$new(
                "yAxisFontSize",
                yAxisFontSize,
                options=list(
                    "10",
                    "12",
                    "14",
                    "16",
                    "18",
                    "20"),
                default="16")
            private$..yAxisPosition <- jmvcore::OptionList$new(
                "yAxisPosition",
                yAxisPosition,
                options=list(
                    "1",
                    "0.5",
                    "0"),
                default="0.5")

            self$.addOption(private$..vars)
            self$.addOption(private$..labelVar)
            self$.addOption(private$..groupVar)
            self$.addOption(private$..rotation)
            self$.addOption(private$..dimNum)
            self$.addOption(private$..xaxis)
            self$.addOption(private$..yaxis)
            self$.addOption(private$..stdVariables)
            self$.addOption(private$..showSummary)
            self$.addOption(private$..showKMO)
            self$.addOption(private$..showLoadings)
            self$.addOption(private$..showObservations)
            self$.addOption(private$..showScreePlot)
            self$.addOption(private$..showVarPlot)
            self$.addOption(private$..showObsPlot)
            self$.addOption(private$..showBiplot)
            self$.addOption(private$..biplotType)
            self$.addOption(private$..biplotLines)
            self$.addOption(private$..biplotStretch)
            self$.addOption(private$..biplotStretchFactor)
            self$.addOption(private$..obsLabelSize)
            self$.addOption(private$..varLabelSize)
            self$.addOption(private$..pointSize)
            self$.addOption(private$..varColor)
            self$.addOption(private$..labelColor)
            self$.addOption(private$..obsColor)
            self$.addOption(private$..colorPalette)
            self$.addOption(private$..screeTitleText)
            self$.addOption(private$..varTitleText)
            self$.addOption(private$..obsTitleText)
            self$.addOption(private$..biplotTitleText)
            self$.addOption(private$..titleAlign)
            self$.addOption(private$..titleFontSize)
            self$.addOption(private$..titleFontFace)
            self$.addOption(private$..screeSubtitleText)
            self$.addOption(private$..varSubtitleText)
            self$.addOption(private$..obsSubtitleText)
            self$.addOption(private$..biplotSubtitleText)
            self$.addOption(private$..subtitleAlign)
            self$.addOption(private$..subtitleFontSize)
            self$.addOption(private$..subtitleFontFace)
            self$.addOption(private$..screeCaptionText)
            self$.addOption(private$..varCaptionText)
            self$.addOption(private$..obsCaptionText)
            self$.addOption(private$..biplotCaptionText)
            self$.addOption(private$..captionAlign)
            self$.addOption(private$..captionFontSize)
            self$.addOption(private$..captionFontFace)
            self$.addOption(private$..kaiser)
            self$.addOption(private$..descAsVarName)
            self$.addOption(private$..stdScores)
            self$.addOption(private$..stdLoadings)
            self$.addOption(private$..stataRotation)
            self$.addOption(private$..obsCoordOV)
            self$.addOption(private$..legendText)
            self$.addOption(private$..legendFontSize)
            self$.addOption(private$..legendPosition)
            self$.addOption(private$..xAxisText)
            self$.addOption(private$..xAxisFontSize)
            self$.addOption(private$..xAxisPosition)
            self$.addOption(private$..yAxisText)
            self$.addOption(private$..yAxisFontSize)
            self$.addOption(private$..yAxisPosition)
        }),
    active = list(
        vars = function() private$..vars$value,
        labelVar = function() private$..labelVar$value,
        groupVar = function() private$..groupVar$value,
        rotation = function() private$..rotation$value,
        dimNum = function() private$..dimNum$value,
        xaxis = function() private$..xaxis$value,
        yaxis = function() private$..yaxis$value,
        stdVariables = function() private$..stdVariables$value,
        showSummary = function() private$..showSummary$value,
        showKMO = function() private$..showKMO$value,
        showLoadings = function() private$..showLoadings$value,
        showObservations = function() private$..showObservations$value,
        showScreePlot = function() private$..showScreePlot$value,
        showVarPlot = function() private$..showVarPlot$value,
        showObsPlot = function() private$..showObsPlot$value,
        showBiplot = function() private$..showBiplot$value,
        biplotType = function() private$..biplotType$value,
        biplotLines = function() private$..biplotLines$value,
        biplotStretch = function() private$..biplotStretch$value,
        biplotStretchFactor = function() private$..biplotStretchFactor$value,
        obsLabelSize = function() private$..obsLabelSize$value,
        varLabelSize = function() private$..varLabelSize$value,
        pointSize = function() private$..pointSize$value,
        varColor = function() private$..varColor$value,
        labelColor = function() private$..labelColor$value,
        obsColor = function() private$..obsColor$value,
        colorPalette = function() private$..colorPalette$value,
        screeTitleText = function() private$..screeTitleText$value,
        varTitleText = function() private$..varTitleText$value,
        obsTitleText = function() private$..obsTitleText$value,
        biplotTitleText = function() private$..biplotTitleText$value,
        titleAlign = function() private$..titleAlign$value,
        titleFontSize = function() private$..titleFontSize$value,
        titleFontFace = function() private$..titleFontFace$value,
        screeSubtitleText = function() private$..screeSubtitleText$value,
        varSubtitleText = function() private$..varSubtitleText$value,
        obsSubtitleText = function() private$..obsSubtitleText$value,
        biplotSubtitleText = function() private$..biplotSubtitleText$value,
        subtitleAlign = function() private$..subtitleAlign$value,
        subtitleFontSize = function() private$..subtitleFontSize$value,
        subtitleFontFace = function() private$..subtitleFontFace$value,
        screeCaptionText = function() private$..screeCaptionText$value,
        varCaptionText = function() private$..varCaptionText$value,
        obsCaptionText = function() private$..obsCaptionText$value,
        biplotCaptionText = function() private$..biplotCaptionText$value,
        captionAlign = function() private$..captionAlign$value,
        captionFontSize = function() private$..captionFontSize$value,
        captionFontFace = function() private$..captionFontFace$value,
        kaiser = function() private$..kaiser$value,
        descAsVarName = function() private$..descAsVarName$value,
        stdScores = function() private$..stdScores$value,
        stdLoadings = function() private$..stdLoadings$value,
        stataRotation = function() private$..stataRotation$value,
        obsCoordOV = function() private$..obsCoordOV$value,
        legendText = function() private$..legendText$value,
        legendFontSize = function() private$..legendFontSize$value,
        legendPosition = function() private$..legendPosition$value,
        xAxisText = function() private$..xAxisText$value,
        xAxisFontSize = function() private$..xAxisFontSize$value,
        xAxisPosition = function() private$..xAxisPosition$value,
        yAxisText = function() private$..yAxisText$value,
        yAxisFontSize = function() private$..yAxisFontSize$value,
        yAxisPosition = function() private$..yAxisPosition$value),
    private = list(
        ..vars = NA,
        ..labelVar = NA,
        ..groupVar = NA,
        ..rotation = NA,
        ..dimNum = NA,
        ..xaxis = NA,
        ..yaxis = NA,
        ..stdVariables = NA,
        ..showSummary = NA,
        ..showKMO = NA,
        ..showLoadings = NA,
        ..showObservations = NA,
        ..showScreePlot = NA,
        ..showVarPlot = NA,
        ..showObsPlot = NA,
        ..showBiplot = NA,
        ..biplotType = NA,
        ..biplotLines = NA,
        ..biplotStretch = NA,
        ..biplotStretchFactor = NA,
        ..obsLabelSize = NA,
        ..varLabelSize = NA,
        ..pointSize = NA,
        ..varColor = NA,
        ..labelColor = NA,
        ..obsColor = NA,
        ..colorPalette = NA,
        ..screeTitleText = NA,
        ..varTitleText = NA,
        ..obsTitleText = NA,
        ..biplotTitleText = NA,
        ..titleAlign = NA,
        ..titleFontSize = NA,
        ..titleFontFace = NA,
        ..screeSubtitleText = NA,
        ..varSubtitleText = NA,
        ..obsSubtitleText = NA,
        ..biplotSubtitleText = NA,
        ..subtitleAlign = NA,
        ..subtitleFontSize = NA,
        ..subtitleFontFace = NA,
        ..screeCaptionText = NA,
        ..varCaptionText = NA,
        ..obsCaptionText = NA,
        ..biplotCaptionText = NA,
        ..captionAlign = NA,
        ..captionFontSize = NA,
        ..captionFontFace = NA,
        ..kaiser = NA,
        ..descAsVarName = NA,
        ..stdScores = NA,
        ..stdLoadings = NA,
        ..stataRotation = NA,
        ..obsCoordOV = NA,
        ..legendText = NA,
        ..legendFontSize = NA,
        ..legendPosition = NA,
        ..xAxisText = NA,
        ..xAxisFontSize = NA,
        ..xAxisPosition = NA,
        ..yAxisText = NA,
        ..yAxisFontSize = NA,
        ..yAxisPosition = NA)
)

principalResults <- if (requireNamespace("jmvcore", quietly=TRUE)) R6::R6Class(
    "principalResults",
    inherit = jmvcore::Group,
    active = list(
        summaryTable = function() private$.items[["summaryTable"]],
        kmoTable = function() private$.items[["kmoTable"]],
        loadingTable = function() private$.items[["loadingTable"]],
        obsTable = function() private$.items[["obsTable"]],
        screePlot = function() private$.items[["screePlot"]],
        varPlot = function() private$.items[["varPlot"]],
        obsPlot = function() private$.items[["obsPlot"]],
        biPlot = function() private$.items[["biPlot"]],
        obsCoordOV = function() private$.items[["obsCoordOV"]]),
    private = list(),
    public=list(
        initialize=function(options) {
            super$initialize(
                options=options,
                name="",
                title="Principal Component Analysis",
                refs=list(
                    "greenacre",
                    "gpa",
                    "psych"))
            self$add(jmvcore::Table$new(
                options=options,
                name="summaryTable",
                title="Summary",
                visible="(showSummary)",
                clearWith=list(
                    "vars",
                    "dimNum",
                    "rotation",
                    "stdVariables",
                    "kaiser",
                    "stataRotation"),
                columns=list(
                    list(
                        `name`="comp", 
                        `title`="Component", 
                        `type`="text"),
                    list(
                        `name`="eigenvalue", 
                        `title`="Eigenvalue", 
                        `superTitle`="Initial Eigenvalues", 
                        `type`="number", 
                        `format`="zto"),
                    list(
                        `name`="initVarProp", 
                        `title`="% of Variance", 
                        `superTitle`="Initial Eigenvalues", 
                        `type`="number", 
                        `format`="pc"),
                    list(
                        `name`="initVarCum", 
                        `title`="Cumulative %", 
                        `superTitle`="Initial Eigenvalues", 
                        `type`="number", 
                        `format`="pc"),
                    list(
                        `name`="loadings", 
                        `title`="SS Loadings", 
                        `superTitle`="Extraction Sums of Squared Loadings", 
                        `type`="number", 
                        `format`="zto"),
                    list(
                        `name`="varProp", 
                        `title`="% of Variance", 
                        `superTitle`="Extraction Sums of Squared Loadings", 
                        `type`="number", 
                        `format`="pc"),
                    list(
                        `name`="varCum", 
                        `title`="Cumulative %", 
                        `superTitle`="Extraction Sums of Squared Loadings", 
                        `type`="number", 
                        `format`="pc"))))
            self$add(jmvcore::Table$new(
                options=options,
                name="kmoTable",
                title="KMO & Bartlett's Test",
                visible="(showKMO)",
                columns=list(
                    list(
                        `name`="test", 
                        `title`="", 
                        `type`="text"),
                    list(
                        `name`="statistic", 
                        `title`="Statistic", 
                        `type`="number"),
                    list(
                        `name`="df", 
                        `title`="df", 
                        `type`="integer"),
                    list(
                        `name`="p", 
                        `title`="p", 
                        `type`="number", 
                        `format`="zto")),
                rows=2,
                clearWith=list(
                    "vars")))
            self$add(jmvcore::Table$new(
                options=options,
                name="loadingTable",
                title="Variables",
                visible="(showLoadings)",
                rows="(vars)",
                clearWith=list(
                    "vars",
                    "descAsVarName",
                    "rotation",
                    "dimNum",
                    "stdVariables",
                    "kaiser",
                    "stdLoadings",
                    "stataRotation"),
                columns=list(
                    list(
                        `name`="var", 
                        `title`="", 
                        `type`="text", 
                        `content`="($key)")),
                notes=list(
                    `norm`="Principal coordinates")))
            self$add(jmvcore::Table$new(
                options=options,
                name="obsTable",
                title="Observations",
                visible="(showObservations)",
                clearWith=list(
                    "vars",
                    "labelVar",
                    "descAsVarName",
                    "rotation",
                    "dimNum",
                    "stdVariables",
                    "kaiser",
                    "stdScores",
                    "stataRotation"),
                columns=list(),
                notes=list(
                    `norm`="Principal coordinates")))
            self$add(jmvcore::Image$new(
                options=options,
                name="screePlot",
                title="Scree Plot",
                width=500,
                height=300,
                visible="(showScreePlot)",
                renderFun=".screeplot",
                clearWith=list(
                    "vars",
                    "stdVariables",
                    "screeTitleText",
                    "titleFontFace",
                    "titleFontSize",
                    "titleAlign",
                    "screeSubtitleText",
                    "subtitleFontFace",
                    "subtitleFontSize",
                    "subtitleAlign",
                    "screeCaptionText",
                    "captionFontFace",
                    "captionFontSize",
                    "captionAlign",
                    "xAxisText",
                    "xAxisFontSize",
                    "xAxisPosition",
                    "yAxisText",
                    "yAxisFontSize",
                    "yAxisPosition")))
            self$add(jmvcore::Image$new(
                options=options,
                name="varPlot",
                title="Variable Plot",
                width=600,
                height=600,
                visible="(showVarPlot)",
                renderFun=".varplot",
                clearWith=list(
                    "vars",
                    "descAsVarName",
                    "rotation",
                    "dimNum",
                    "xaxis",
                    "yaxis",
                    "stdVariables",
                    "kaiser",
                    "obsColor",
                    "varColor",
                    "colorPalette",
                    "labelColor",
                    "obsLabelSize",
                    "varLabelSize",
                    "pointSize",
                    "varTitleText",
                    "titleFontFace",
                    "titleFontSize",
                    "titleAlign",
                    "varCaptionText",
                    "captionFontFace",
                    "captionFontSize",
                    "captionAlign",
                    "varSubtitleText",
                    "subtitleFontFace",
                    "subtitleFontSize",
                    "subtitleAlign",
                    "stdLoadings",
                    "stataRotation",
                    "xAxisText",
                    "xAxisFontSize",
                    "xAxisPosition",
                    "yAxisText",
                    "yAxisFontSize",
                    "yAxisPosition")))
            self$add(jmvcore::Image$new(
                options=options,
                name="obsPlot",
                title="Observation Plot",
                width=600,
                height=600,
                visible="(showObsPlot)",
                renderFun=".obsplot",
                clearWith=list(
                    "vars",
                    "labelVar",
                    "descAsVarName",
                    "rotation",
                    "dimNum",
                    "xaxis",
                    "yaxis",
                    "groupVar",
                    "stdVariables",
                    "kaiser",
                    "obsColor",
                    "varColor",
                    "colorPalette",
                    "labelColor",
                    "obsLabelSize",
                    "varLabelSize",
                    "pointSize",
                    "obsTitleText",
                    "titleFontFace",
                    "titleFontSize",
                    "titleAlign",
                    "obsSubtitleText",
                    "subtitleFontFace",
                    "subtitleFontSize",
                    "subtitleAlign",
                    "obsCaptionText",
                    "captionFontFace",
                    "captionFontSize",
                    "captionAlign",
                    "stdScores",
                    "stataRotation",
                    "xAxisText",
                    "xAxisFontSize",
                    "xAxisPosition",
                    "yAxisText",
                    "yAxisFontSize",
                    "yAxisPosition",
                    "legendText",
                    "legendFontSize",
                    "legendPosition")))
            self$add(jmvcore::Image$new(
                options=options,
                name="biPlot",
                title="Biplot",
                width=600,
                height=600,
                visible="(showBiplot)",
                renderFun=".biplot",
                clearWith=list(
                    "vars",
                    "labelVar",
                    "descAsVarName",
                    "rotation",
                    "dimNum",
                    "xaxis",
                    "yaxis",
                    "groupVar",
                    "stdVariables",
                    "biplotType",
                    "biplotLines",
                    "biplotStretch",
                    "biplotStretchFactor",
                    "obsColor",
                    "varColor",
                    "colorPalette",
                    "labelColor",
                    "obsLabelSize",
                    "varLabelSize",
                    "pointSize",
                    "biplotTitleText",
                    "titleFontFace",
                    "titleFontSize",
                    "titleAlign",
                    "biplotSubtitleText",
                    "subtitleFontFace",
                    "subtitleFontSize",
                    "subtitleAlign",
                    "biplotCaptionText",
                    "captionFontFace",
                    "captionFontSize",
                    "captionAlign",
                    "stataRotation",
                    "xAxisText",
                    "xAxisFontSize",
                    "xAxisPosition",
                    "yAxisText",
                    "yAxisFontSize",
                    "yAxisPosition",
                    "legendText",
                    "legendFontSize",
                    "legendPosition")))
            self$add(jmvcore::Output$new(
                options=options,
                name="obsCoordOV",
                title="Observation Coordinates",
                initInRun=TRUE,
                clearWith=list(
                    "vars",
                    "rotation",
                    "dimNum",
                    "stdVariables",
                    "kaiser",
                    "stdScores",
                    "stataRotation")))}))

principalBase <- if (requireNamespace("jmvcore", quietly=TRUE)) R6::R6Class(
    "principalBase",
    inherit = jmvcore::Analysis,
    public = list(
        initialize = function(options, data=NULL, datasetId="", analysisId="", revision=0) {
            super$initialize(
                package = "vijPlots",
                name = "principal",
                version = c(1,0,0),
                options = options,
                results = principalResults$new(options=options),
                data = data,
                datasetId = datasetId,
                analysisId = analysisId,
                revision = revision,
                pause = NULL,
                completeWhenFilled = FALSE,
                requiresMissings = FALSE,
                weightsSupport = 'none')
        }))

#' Principal Component Analysis
#'
#' 
#' @param data .
#' @param vars .
#' @param labelVar .
#' @param groupVar .
#' @param rotation .
#' @param dimNum .
#' @param xaxis .
#' @param yaxis .
#' @param stdVariables .
#' @param showSummary .
#' @param showKMO .
#' @param showLoadings .
#' @param showObservations .
#' @param showScreePlot .
#' @param showVarPlot .
#' @param showObsPlot .
#' @param showBiplot .
#' @param biplotType .
#' @param biplotLines .
#' @param biplotStretch .
#' @param biplotStretchFactor .
#' @param obsLabelSize .
#' @param varLabelSize .
#' @param pointSize .
#' @param varColor .
#' @param labelColor .
#' @param obsColor .
#' @param colorPalette .
#' @param screeTitleText .
#' @param varTitleText .
#' @param obsTitleText .
#' @param biplotTitleText .
#' @param titleAlign .
#' @param titleFontSize .
#' @param titleFontFace .
#' @param screeSubtitleText .
#' @param varSubtitleText .
#' @param obsSubtitleText .
#' @param biplotSubtitleText .
#' @param subtitleAlign .
#' @param subtitleFontSize .
#' @param subtitleFontFace .
#' @param screeCaptionText .
#' @param varCaptionText .
#' @param obsCaptionText .
#' @param biplotCaptionText .
#' @param captionAlign .
#' @param captionFontSize .
#' @param captionFontFace .
#' @param kaiser .
#' @param descAsVarName .
#' @param stdScores .
#' @param stdLoadings .
#' @param stataRotation .
#' @param legendText .
#' @param legendFontSize .
#' @param legendPosition .
#' @param xAxisText .
#' @param xAxisFontSize .
#' @param xAxisPosition .
#' @param yAxisText .
#' @param yAxisFontSize .
#' @param yAxisPosition .
#' @return A results object containing:
#' \tabular{llllll}{
#'   \code{results$summaryTable} \tab \tab \tab \tab \tab a table \cr
#'   \code{results$kmoTable} \tab \tab \tab \tab \tab a table \cr
#'   \code{results$loadingTable} \tab \tab \tab \tab \tab a table \cr
#'   \code{results$obsTable} \tab \tab \tab \tab \tab a table \cr
#'   \code{results$screePlot} \tab \tab \tab \tab \tab an image \cr
#'   \code{results$varPlot} \tab \tab \tab \tab \tab an image \cr
#'   \code{results$obsPlot} \tab \tab \tab \tab \tab an image \cr
#'   \code{results$biPlot} \tab \tab \tab \tab \tab an image \cr
#'   \code{results$obsCoordOV} \tab \tab \tab \tab \tab an output \cr
#' }
#'
#' Tables can be converted to data frames with \code{asDF} or \code{\link{as.data.frame}}. For example:
#'
#' \code{results$summaryTable$asDF}
#'
#' \code{as.data.frame(results$summaryTable)}
#'
#' @export
principal <- function(
    data,
    vars,
    labelVar,
    groupVar,
    rotation = "none",
    dimNum = 2,
    xaxis = 1,
    yaxis = 2,
    stdVariables = TRUE,
    showSummary = TRUE,
    showKMO = FALSE,
    showLoadings = FALSE,
    showObservations = FALSE,
    showScreePlot = TRUE,
    showVarPlot = TRUE,
    showObsPlot = TRUE,
    showBiplot = FALSE,
    biplotType = "formPlot",
    biplotLines = FALSE,
    biplotStretch = FALSE,
    biplotStretchFactor = 1,
    obsLabelSize = 10,
    varLabelSize = 12,
    pointSize = 3,
    varColor = "#377EB8",
    labelColor = "none",
    obsColor = "#E41A1C",
    colorPalette = "jmv",
    screeTitleText = "default",
    varTitleText = "default",
    obsTitleText = "default",
    biplotTitleText = "default",
    titleAlign = "0.5",
    titleFontSize = 16,
    titleFontFace = "plain",
    screeSubtitleText,
    varSubtitleText = "default",
    obsSubtitleText = "default",
    biplotSubtitleText = "default",
    subtitleAlign = "0.5",
    subtitleFontSize = 12,
    subtitleFontFace = "plain",
    screeCaptionText,
    varCaptionText = "default",
    obsCaptionText = "default",
    biplotCaptionText,
    captionAlign = "1",
    captionFontSize = 12,
    captionFontFace = "plain",
    kaiser = FALSE,
    descAsVarName = FALSE,
    stdScores = FALSE,
    stdLoadings = FALSE,
    stataRotation = FALSE,
    legendText,
    legendFontSize = "14",
    legendPosition = "right",
    xAxisText,
    xAxisFontSize = "16",
    xAxisPosition = "0.5",
    yAxisText,
    yAxisFontSize = "16",
    yAxisPosition = "0.5") {

    if ( ! requireNamespace("jmvcore", quietly=TRUE))
        stop("principal requires jmvcore to be installed (restart may be required)")

    if ( ! missing(vars)) vars <- jmvcore::resolveQuo(jmvcore::enquo(vars))
    if ( ! missing(labelVar)) labelVar <- jmvcore::resolveQuo(jmvcore::enquo(labelVar))
    if ( ! missing(groupVar)) groupVar <- jmvcore::resolveQuo(jmvcore::enquo(groupVar))
    if (missing(data))
        data <- jmvcore::marshalData(
            parent.frame(),
            `if`( ! missing(vars), vars, NULL),
            `if`( ! missing(labelVar), labelVar, NULL),
            `if`( ! missing(groupVar), groupVar, NULL))

    for (v in groupVar) if (v %in% names(data)) data[[v]] <- as.factor(data[[v]])

    options <- principalOptions$new(
        vars = vars,
        labelVar = labelVar,
        groupVar = groupVar,
        rotation = rotation,
        dimNum = dimNum,
        xaxis = xaxis,
        yaxis = yaxis,
        stdVariables = stdVariables,
        showSummary = showSummary,
        showKMO = showKMO,
        showLoadings = showLoadings,
        showObservations = showObservations,
        showScreePlot = showScreePlot,
        showVarPlot = showVarPlot,
        showObsPlot = showObsPlot,
        showBiplot = showBiplot,
        biplotType = biplotType,
        biplotLines = biplotLines,
        biplotStretch = biplotStretch,
        biplotStretchFactor = biplotStretchFactor,
        obsLabelSize = obsLabelSize,
        varLabelSize = varLabelSize,
        pointSize = pointSize,
        varColor = varColor,
        labelColor = labelColor,
        obsColor = obsColor,
        colorPalette = colorPalette,
        screeTitleText = screeTitleText,
        varTitleText = varTitleText,
        obsTitleText = obsTitleText,
        biplotTitleText = biplotTitleText,
        titleAlign = titleAlign,
        titleFontSize = titleFontSize,
        titleFontFace = titleFontFace,
        screeSubtitleText = screeSubtitleText,
        varSubtitleText = varSubtitleText,
        obsSubtitleText = obsSubtitleText,
        biplotSubtitleText = biplotSubtitleText,
        subtitleAlign = subtitleAlign,
        subtitleFontSize = subtitleFontSize,
        subtitleFontFace = subtitleFontFace,
        screeCaptionText = screeCaptionText,
        varCaptionText = varCaptionText,
        obsCaptionText = obsCaptionText,
        biplotCaptionText = biplotCaptionText,
        captionAlign = captionAlign,
        captionFontSize = captionFontSize,
        captionFontFace = captionFontFace,
        kaiser = kaiser,
        descAsVarName = descAsVarName,
        stdScores = stdScores,
        stdLoadings = stdLoadings,
        stataRotation = stataRotation,
        legendText = legendText,
        legendFontSize = legendFontSize,
        legendPosition = legendPosition,
        xAxisText = xAxisText,
        xAxisFontSize = xAxisFontSize,
        xAxisPosition = xAxisPosition,
        yAxisText = yAxisText,
        yAxisFontSize = yAxisFontSize,
        yAxisPosition = yAxisPosition)

    analysis <- principalClass$new(
        options = options,
        data = data)

    analysis$run()

    analysis$results
}

