
# This file is automatically generated, you probably don't want to edit this

qqplotOptions <- if (requireNamespace("jmvcore", quietly=TRUE)) R6::R6Class(
    "qqplotOptions",
    inherit = jmvcore::Options,
    public = list(
        initialize = function(
            dep = NULL,
            group = NULL,
            distrib = "norm",
            transLog = FALSE,
            standardize = FALSE,
            refLine = TRUE,
            band = FALSE,
            methodQQ = "pointwise",
            methodPP = "ell",
            detrend = FALSE,
            type = "QQ",
            refType = "identity",
            paramMethod = "paraEstimate",
            paramEstMethod = "mle",
            param1 = 0,
            param2 = 1,
            colorPalette = "jmv",
            titleText = "default",
            titleFontFace = "bold",
            titleFontSize = "14",
            titleAlign = "0.5",
            subtitleText = NULL,
            subtitleFontFace = "plain",
            subtitleFontSize = "12",
            subtitleAlign = "0.5",
            captionText = NULL,
            captionFontFace = "italic",
            captionFontSize = "10",
            captionAlign = "1",
            legendText = NULL,
            legendFontSize = "14",
            legendPosition = "right",
            xAxisText = NULL,
            xAxisFontSize = "16",
            xAxisPosition = "0.5",
            yAxisText = NULL,
            yAxisFontSize = "16",
            yAxisPosition = "0.5",
            yAxisLabelFontSize = 12,
            yAxisLabelRotation = 0,
            yAxisRangeType = "auto",
            yAxisRangeMin = 0,
            yAxisRangeMax = 10,
            xAxisLabelFontSize = 12,
            xAxisLabelRotation = 0,
            xAxisRangeType = "auto",
            xAxisRangeMin = 0,
            xAxisRangeMax = 10,
            xTicks = 0,
            yTicks = 0, ...) {

            super$initialize(
                package="vijPlots",
                name="qqplot",
                requiresData=TRUE,
                ...)

            private$..dep <- jmvcore::OptionVariable$new(
                "dep",
                dep,
                suggested=list(
                    "continuous"),
                permitted=list(
                    "numeric"))
            private$..group <- jmvcore::OptionVariable$new(
                "group",
                group,
                suggested=list(
                    "nominal",
                    "ordinal"),
                permitted=list(
                    "factor"))
            private$..distrib <- jmvcore::OptionList$new(
                "distrib",
                distrib,
                options=list(
                    "norm",
                    "lnorm",
                    "beta",
                    "cauchy",
                    "chisq",
                    "exp",
                    "f",
                    "gamma",
                    "logis",
                    "t",
                    "unif",
                    "weibull"),
                default="norm")
            private$..transLog <- jmvcore::OptionBool$new(
                "transLog",
                transLog,
                default=FALSE)
            private$..standardize <- jmvcore::OptionBool$new(
                "standardize",
                standardize,
                default=FALSE)
            private$..refLine <- jmvcore::OptionBool$new(
                "refLine",
                refLine,
                default=TRUE)
            private$..band <- jmvcore::OptionBool$new(
                "band",
                band,
                default=FALSE)
            private$..methodQQ <- jmvcore::OptionList$new(
                "methodQQ",
                methodQQ,
                options=list(
                    "ell",
                    "pointwise",
                    "boot",
                    "ks",
                    "ts"),
                default="pointwise")
            private$..methodPP <- jmvcore::OptionList$new(
                "methodPP",
                methodPP,
                options=list(
                    "ell",
                    "boot"),
                default="ell")
            private$..detrend <- jmvcore::OptionBool$new(
                "detrend",
                detrend,
                default=FALSE)
            private$..type <- jmvcore::OptionList$new(
                "type",
                type,
                options=list(
                    "QQ",
                    "PP"),
                default="QQ")
            private$..refType <- jmvcore::OptionList$new(
                "refType",
                refType,
                options=list(
                    "qqline",
                    "identity"),
                default="identity")
            private$..paramMethod <- jmvcore::OptionList$new(
                "paramMethod",
                paramMethod,
                options=list(
                    "paraEstimate",
                    "paraValue"),
                default="paraEstimate")
            private$..paramEstMethod <- jmvcore::OptionList$new(
                "paramEstMethod",
                paramEstMethod,
                options=list(
                    "mle",
                    "mme"),
                default="mle")
            private$..param1 <- jmvcore::OptionNumber$new(
                "param1",
                param1,
                default=0)
            private$..param2 <- jmvcore::OptionNumber$new(
                "param2",
                param2,
                default=1)
            private$..colorPalette <- jmvcore::OptionList$new(
                "colorPalette",
                colorPalette,
                options=list(
                    "jmv",
                    "Set1",
                    "Set2",
                    "Set3",
                    "Pastel1",
                    "Pastel2",
                    "Accent",
                    "Paired",
                    "Dark2",
                    "Spectral",
                    "RdYlGn",
                    "RdYlBu",
                    "RdGy",
                    "RdBu",
                    "PuOr",
                    "PRGn",
                    "PiYG",
                    "BrBG",
                    "Blues",
                    "Greens",
                    "Greys",
                    "Oranges",
                    "Purples",
                    "Reds",
                    "BuGn",
                    "BuPu",
                    "GnBu",
                    "OrRd",
                    "PuBu",
                    "PuBuGn",
                    "PuRd",
                    "RdPu",
                    "YlGn",
                    "YlGnBu",
                    "YlOrBr",
                    "YlOrRd",
                    "viridis::viridis",
                    "viridis::magma",
                    "viridis::inferno",
                    "viridis::plasma",
                    "viridis::turbo",
                    "dichromat::Categorical.12",
                    "tidy::friendly",
                    "tidy::seaside",
                    "tidy::apple",
                    "tidy::ibm",
                    "tidy::candy",
                    "tidy::alger",
                    "tidy::rainbow",
                    "tidy::metro",
                    "custom::lemovice"),
                default="jmv")
            private$..titleText <- jmvcore::OptionString$new(
                "titleText",
                titleText,
                default="default")
            private$..titleFontFace <- jmvcore::OptionList$new(
                "titleFontFace",
                titleFontFace,
                options=list(
                    "plain",
                    "bold",
                    "italic",
                    "bold.italic"),
                default="bold")
            private$..titleFontSize <- jmvcore::OptionList$new(
                "titleFontSize",
                titleFontSize,
                options=list(
                    "12",
                    "14",
                    "16",
                    "18",
                    "20",
                    "22",
                    "24"),
                default="14")
            private$..titleAlign <- jmvcore::OptionList$new(
                "titleAlign",
                titleAlign,
                options=list(
                    "0",
                    "0.5",
                    "1"),
                default="0.5")
            private$..subtitleText <- jmvcore::OptionString$new(
                "subtitleText",
                subtitleText)
            private$..subtitleFontFace <- jmvcore::OptionList$new(
                "subtitleFontFace",
                subtitleFontFace,
                options=list(
                    "plain",
                    "bold",
                    "italic",
                    "bold.italic"),
                default="plain")
            private$..subtitleFontSize <- jmvcore::OptionList$new(
                "subtitleFontSize",
                subtitleFontSize,
                options=list(
                    "10",
                    "12",
                    "14",
                    "16",
                    "18",
                    "20",
                    "22"),
                default="12")
            private$..subtitleAlign <- jmvcore::OptionList$new(
                "subtitleAlign",
                subtitleAlign,
                options=list(
                    "0",
                    "0.5",
                    "1"),
                default="0.5")
            private$..captionText <- jmvcore::OptionString$new(
                "captionText",
                captionText)
            private$..captionFontFace <- jmvcore::OptionList$new(
                "captionFontFace",
                captionFontFace,
                options=list(
                    "plain",
                    "bold",
                    "italic",
                    "bold.italic"),
                default="italic")
            private$..captionFontSize <- jmvcore::OptionList$new(
                "captionFontSize",
                captionFontSize,
                options=list(
                    "8",
                    "10",
                    "12",
                    "14",
                    "16",
                    "18",
                    "20"),
                default="10")
            private$..captionAlign <- jmvcore::OptionList$new(
                "captionAlign",
                captionAlign,
                options=list(
                    "0",
                    "0.5",
                    "1"),
                default="1")
            private$..legendText <- jmvcore::OptionString$new(
                "legendText",
                legendText)
            private$..legendFontSize <- jmvcore::OptionList$new(
                "legendFontSize",
                legendFontSize,
                options=list(
                    "10",
                    "12",
                    "14",
                    "16",
                    "18",
                    "20"),
                default="14")
            private$..legendPosition <- jmvcore::OptionList$new(
                "legendPosition",
                legendPosition,
                options=list(
                    "right",
                    "bottom",
                    "left",
                    "top"),
                default="right")
            private$..xAxisText <- jmvcore::OptionString$new(
                "xAxisText",
                xAxisText)
            private$..xAxisFontSize <- jmvcore::OptionList$new(
                "xAxisFontSize",
                xAxisFontSize,
                options=list(
                    "10",
                    "12",
                    "14",
                    "16",
                    "18",
                    "20"),
                default="16")
            private$..xAxisPosition <- jmvcore::OptionList$new(
                "xAxisPosition",
                xAxisPosition,
                options=list(
                    "0",
                    "0.5",
                    "1"),
                default="0.5")
            private$..yAxisText <- jmvcore::OptionString$new(
                "yAxisText",
                yAxisText)
            private$..yAxisFontSize <- jmvcore::OptionList$new(
                "yAxisFontSize",
                yAxisFontSize,
                options=list(
                    "10",
                    "12",
                    "14",
                    "16",
                    "18",
                    "20"),
                default="16")
            private$..yAxisPosition <- jmvcore::OptionList$new(
                "yAxisPosition",
                yAxisPosition,
                options=list(
                    "1",
                    "0.5",
                    "0"),
                default="0.5")
            private$..yAxisLabelFontSize <- jmvcore::OptionNumber$new(
                "yAxisLabelFontSize",
                yAxisLabelFontSize,
                default=12)
            private$..yAxisLabelRotation <- jmvcore::OptionNumber$new(
                "yAxisLabelRotation",
                yAxisLabelRotation,
                default=0,
                min=0,
                max=360)
            private$..yAxisRangeType <- jmvcore::OptionList$new(
                "yAxisRangeType",
                yAxisRangeType,
                options=list(
                    "auto",
                    "manual"),
                default="auto")
            private$..yAxisRangeMin <- jmvcore::OptionNumber$new(
                "yAxisRangeMin",
                yAxisRangeMin,
                default=0)
            private$..yAxisRangeMax <- jmvcore::OptionNumber$new(
                "yAxisRangeMax",
                yAxisRangeMax,
                default=10)
            private$..xAxisLabelFontSize <- jmvcore::OptionNumber$new(
                "xAxisLabelFontSize",
                xAxisLabelFontSize,
                default=12)
            private$..xAxisLabelRotation <- jmvcore::OptionNumber$new(
                "xAxisLabelRotation",
                xAxisLabelRotation,
                default=0,
                min=0,
                max=360)
            private$..xAxisRangeType <- jmvcore::OptionList$new(
                "xAxisRangeType",
                xAxisRangeType,
                options=list(
                    "auto",
                    "manual"),
                default="auto")
            private$..xAxisRangeMin <- jmvcore::OptionNumber$new(
                "xAxisRangeMin",
                xAxisRangeMin,
                default=0)
            private$..xAxisRangeMax <- jmvcore::OptionNumber$new(
                "xAxisRangeMax",
                xAxisRangeMax,
                default=10)
            private$..xTicks <- jmvcore::OptionInteger$new(
                "xTicks",
                xTicks,
                default=0,
                min=0,
                max=99)
            private$..yTicks <- jmvcore::OptionInteger$new(
                "yTicks",
                yTicks,
                default=0,
                min=0,
                max=99)

            self$.addOption(private$..dep)
            self$.addOption(private$..group)
            self$.addOption(private$..distrib)
            self$.addOption(private$..transLog)
            self$.addOption(private$..standardize)
            self$.addOption(private$..refLine)
            self$.addOption(private$..band)
            self$.addOption(private$..methodQQ)
            self$.addOption(private$..methodPP)
            self$.addOption(private$..detrend)
            self$.addOption(private$..type)
            self$.addOption(private$..refType)
            self$.addOption(private$..paramMethod)
            self$.addOption(private$..paramEstMethod)
            self$.addOption(private$..param1)
            self$.addOption(private$..param2)
            self$.addOption(private$..colorPalette)
            self$.addOption(private$..titleText)
            self$.addOption(private$..titleFontFace)
            self$.addOption(private$..titleFontSize)
            self$.addOption(private$..titleAlign)
            self$.addOption(private$..subtitleText)
            self$.addOption(private$..subtitleFontFace)
            self$.addOption(private$..subtitleFontSize)
            self$.addOption(private$..subtitleAlign)
            self$.addOption(private$..captionText)
            self$.addOption(private$..captionFontFace)
            self$.addOption(private$..captionFontSize)
            self$.addOption(private$..captionAlign)
            self$.addOption(private$..legendText)
            self$.addOption(private$..legendFontSize)
            self$.addOption(private$..legendPosition)
            self$.addOption(private$..xAxisText)
            self$.addOption(private$..xAxisFontSize)
            self$.addOption(private$..xAxisPosition)
            self$.addOption(private$..yAxisText)
            self$.addOption(private$..yAxisFontSize)
            self$.addOption(private$..yAxisPosition)
            self$.addOption(private$..yAxisLabelFontSize)
            self$.addOption(private$..yAxisLabelRotation)
            self$.addOption(private$..yAxisRangeType)
            self$.addOption(private$..yAxisRangeMin)
            self$.addOption(private$..yAxisRangeMax)
            self$.addOption(private$..xAxisLabelFontSize)
            self$.addOption(private$..xAxisLabelRotation)
            self$.addOption(private$..xAxisRangeType)
            self$.addOption(private$..xAxisRangeMin)
            self$.addOption(private$..xAxisRangeMax)
            self$.addOption(private$..xTicks)
            self$.addOption(private$..yTicks)
        }),
    active = list(
        dep = function() private$..dep$value,
        group = function() private$..group$value,
        distrib = function() private$..distrib$value,
        transLog = function() private$..transLog$value,
        standardize = function() private$..standardize$value,
        refLine = function() private$..refLine$value,
        band = function() private$..band$value,
        methodQQ = function() private$..methodQQ$value,
        methodPP = function() private$..methodPP$value,
        detrend = function() private$..detrend$value,
        type = function() private$..type$value,
        refType = function() private$..refType$value,
        paramMethod = function() private$..paramMethod$value,
        paramEstMethod = function() private$..paramEstMethod$value,
        param1 = function() private$..param1$value,
        param2 = function() private$..param2$value,
        colorPalette = function() private$..colorPalette$value,
        titleText = function() private$..titleText$value,
        titleFontFace = function() private$..titleFontFace$value,
        titleFontSize = function() private$..titleFontSize$value,
        titleAlign = function() private$..titleAlign$value,
        subtitleText = function() private$..subtitleText$value,
        subtitleFontFace = function() private$..subtitleFontFace$value,
        subtitleFontSize = function() private$..subtitleFontSize$value,
        subtitleAlign = function() private$..subtitleAlign$value,
        captionText = function() private$..captionText$value,
        captionFontFace = function() private$..captionFontFace$value,
        captionFontSize = function() private$..captionFontSize$value,
        captionAlign = function() private$..captionAlign$value,
        legendText = function() private$..legendText$value,
        legendFontSize = function() private$..legendFontSize$value,
        legendPosition = function() private$..legendPosition$value,
        xAxisText = function() private$..xAxisText$value,
        xAxisFontSize = function() private$..xAxisFontSize$value,
        xAxisPosition = function() private$..xAxisPosition$value,
        yAxisText = function() private$..yAxisText$value,
        yAxisFontSize = function() private$..yAxisFontSize$value,
        yAxisPosition = function() private$..yAxisPosition$value,
        yAxisLabelFontSize = function() private$..yAxisLabelFontSize$value,
        yAxisLabelRotation = function() private$..yAxisLabelRotation$value,
        yAxisRangeType = function() private$..yAxisRangeType$value,
        yAxisRangeMin = function() private$..yAxisRangeMin$value,
        yAxisRangeMax = function() private$..yAxisRangeMax$value,
        xAxisLabelFontSize = function() private$..xAxisLabelFontSize$value,
        xAxisLabelRotation = function() private$..xAxisLabelRotation$value,
        xAxisRangeType = function() private$..xAxisRangeType$value,
        xAxisRangeMin = function() private$..xAxisRangeMin$value,
        xAxisRangeMax = function() private$..xAxisRangeMax$value,
        xTicks = function() private$..xTicks$value,
        yTicks = function() private$..yTicks$value),
    private = list(
        ..dep = NA,
        ..group = NA,
        ..distrib = NA,
        ..transLog = NA,
        ..standardize = NA,
        ..refLine = NA,
        ..band = NA,
        ..methodQQ = NA,
        ..methodPP = NA,
        ..detrend = NA,
        ..type = NA,
        ..refType = NA,
        ..paramMethod = NA,
        ..paramEstMethod = NA,
        ..param1 = NA,
        ..param2 = NA,
        ..colorPalette = NA,
        ..titleText = NA,
        ..titleFontFace = NA,
        ..titleFontSize = NA,
        ..titleAlign = NA,
        ..subtitleText = NA,
        ..subtitleFontFace = NA,
        ..subtitleFontSize = NA,
        ..subtitleAlign = NA,
        ..captionText = NA,
        ..captionFontFace = NA,
        ..captionFontSize = NA,
        ..captionAlign = NA,
        ..legendText = NA,
        ..legendFontSize = NA,
        ..legendPosition = NA,
        ..xAxisText = NA,
        ..xAxisFontSize = NA,
        ..xAxisPosition = NA,
        ..yAxisText = NA,
        ..yAxisFontSize = NA,
        ..yAxisPosition = NA,
        ..yAxisLabelFontSize = NA,
        ..yAxisLabelRotation = NA,
        ..yAxisRangeType = NA,
        ..yAxisRangeMin = NA,
        ..yAxisRangeMax = NA,
        ..xAxisLabelFontSize = NA,
        ..xAxisLabelRotation = NA,
        ..xAxisRangeType = NA,
        ..xAxisRangeMin = NA,
        ..xAxisRangeMax = NA,
        ..xTicks = NA,
        ..yTicks = NA)
)

qqplotResults <- if (requireNamespace("jmvcore", quietly=TRUE)) R6::R6Class(
    "qqplotResults",
    inherit = jmvcore::Group,
    active = list(
        plot = function() private$.items[["plot"]],
        paramTable = function() private$.items[["paramTable"]]),
    private = list(),
    public=list(
        initialize=function(options) {
            super$initialize(
                options=options,
                name="",
                title="Q-Q & P-P Plots",
                refs=list(
                    "qqplotr"))
            self$add(jmvcore::Image$new(
                options=options,
                name="plot",
                title="",
                width=400,
                height=400,
                renderFun=".plot"))
            self$add(jmvcore::Table$new(
                options=options,
                name="paramTable",
                title="Parameter Estimates",
                rows=1,
                columns=list(
                    list(
                        `name`="var", 
                        `title`="", 
                        `type`="text"))))}))

qqplotBase <- if (requireNamespace("jmvcore", quietly=TRUE)) R6::R6Class(
    "qqplotBase",
    inherit = jmvcore::Analysis,
    public = list(
        initialize = function(options, data=NULL, datasetId="", analysisId="", revision=0) {
            super$initialize(
                package = "vijPlots",
                name = "qqplot",
                version = c(1,0,0),
                options = options,
                results = qqplotResults$new(options=options),
                data = data,
                datasetId = datasetId,
                analysisId = analysisId,
                revision = revision,
                pause = NULL,
                completeWhenFilled = FALSE,
                requiresMissings = FALSE,
                weightsSupport = 'auto')
        }))

#' Q-Q & P-P Plots
#'
#' 
#' @param data .
#' @param dep .
#' @param group .
#' @param distrib .
#' @param transLog .
#' @param standardize .
#' @param refLine .
#' @param band .
#' @param methodQQ .
#' @param methodPP .
#' @param detrend .
#' @param type .
#' @param refType .
#' @param paramMethod .
#' @param paramEstMethod .
#' @param param1 .
#' @param param2 .
#' @param colorPalette .
#' @param titleText .
#' @param titleFontFace .
#' @param titleFontSize .
#' @param titleAlign .
#' @param subtitleText .
#' @param subtitleFontFace .
#' @param subtitleFontSize .
#' @param subtitleAlign .
#' @param captionText .
#' @param captionFontFace .
#' @param captionFontSize .
#' @param captionAlign .
#' @param legendText .
#' @param legendFontSize .
#' @param legendPosition .
#' @param xAxisText .
#' @param xAxisFontSize .
#' @param xAxisPosition .
#' @param yAxisText .
#' @param yAxisFontSize .
#' @param yAxisPosition .
#' @param yAxisLabelFontSize .
#' @param yAxisLabelRotation .
#' @param yAxisRangeType .
#' @param yAxisRangeMin .
#' @param yAxisRangeMax .
#' @param xAxisLabelFontSize .
#' @param xAxisLabelRotation .
#' @param xAxisRangeType .
#' @param xAxisRangeMin .
#' @param xAxisRangeMax .
#' @param xTicks .
#' @param yTicks .
#' @return A results object containing:
#' \tabular{llllll}{
#'   \code{results$plot} \tab \tab \tab \tab \tab an image \cr
#'   \code{results$paramTable} \tab \tab \tab \tab \tab a table \cr
#' }
#'
#' Tables can be converted to data frames with \code{asDF} or \code{\link{as.data.frame}}. For example:
#'
#' \code{results$paramTable$asDF}
#'
#' \code{as.data.frame(results$paramTable)}
#'
#' @export
qqplot <- function(
    data,
    dep,
    group,
    distrib = "norm",
    transLog = FALSE,
    standardize = FALSE,
    refLine = TRUE,
    band = FALSE,
    methodQQ = "pointwise",
    methodPP = "ell",
    detrend = FALSE,
    type = "QQ",
    refType = "identity",
    paramMethod = "paraEstimate",
    paramEstMethod = "mle",
    param1 = 0,
    param2 = 1,
    colorPalette = "jmv",
    titleText = "default",
    titleFontFace = "bold",
    titleFontSize = "14",
    titleAlign = "0.5",
    subtitleText,
    subtitleFontFace = "plain",
    subtitleFontSize = "12",
    subtitleAlign = "0.5",
    captionText,
    captionFontFace = "italic",
    captionFontSize = "10",
    captionAlign = "1",
    legendText,
    legendFontSize = "14",
    legendPosition = "right",
    xAxisText,
    xAxisFontSize = "16",
    xAxisPosition = "0.5",
    yAxisText,
    yAxisFontSize = "16",
    yAxisPosition = "0.5",
    yAxisLabelFontSize = 12,
    yAxisLabelRotation = 0,
    yAxisRangeType = "auto",
    yAxisRangeMin = 0,
    yAxisRangeMax = 10,
    xAxisLabelFontSize = 12,
    xAxisLabelRotation = 0,
    xAxisRangeType = "auto",
    xAxisRangeMin = 0,
    xAxisRangeMax = 10,
    xTicks = 0,
    yTicks = 0) {

    if ( ! requireNamespace("jmvcore", quietly=TRUE))
        stop("qqplot requires jmvcore to be installed (restart may be required)")

    if ( ! missing(dep)) dep <- jmvcore::resolveQuo(jmvcore::enquo(dep))
    if ( ! missing(group)) group <- jmvcore::resolveQuo(jmvcore::enquo(group))
    if (missing(data))
        data <- jmvcore::marshalData(
            parent.frame(),
            `if`( ! missing(dep), dep, NULL),
            `if`( ! missing(group), group, NULL))

    for (v in group) if (v %in% names(data)) data[[v]] <- as.factor(data[[v]])

    options <- qqplotOptions$new(
        dep = dep,
        group = group,
        distrib = distrib,
        transLog = transLog,
        standardize = standardize,
        refLine = refLine,
        band = band,
        methodQQ = methodQQ,
        methodPP = methodPP,
        detrend = detrend,
        type = type,
        refType = refType,
        paramMethod = paramMethod,
        paramEstMethod = paramEstMethod,
        param1 = param1,
        param2 = param2,
        colorPalette = colorPalette,
        titleText = titleText,
        titleFontFace = titleFontFace,
        titleFontSize = titleFontSize,
        titleAlign = titleAlign,
        subtitleText = subtitleText,
        subtitleFontFace = subtitleFontFace,
        subtitleFontSize = subtitleFontSize,
        subtitleAlign = subtitleAlign,
        captionText = captionText,
        captionFontFace = captionFontFace,
        captionFontSize = captionFontSize,
        captionAlign = captionAlign,
        legendText = legendText,
        legendFontSize = legendFontSize,
        legendPosition = legendPosition,
        xAxisText = xAxisText,
        xAxisFontSize = xAxisFontSize,
        xAxisPosition = xAxisPosition,
        yAxisText = yAxisText,
        yAxisFontSize = yAxisFontSize,
        yAxisPosition = yAxisPosition,
        yAxisLabelFontSize = yAxisLabelFontSize,
        yAxisLabelRotation = yAxisLabelRotation,
        yAxisRangeType = yAxisRangeType,
        yAxisRangeMin = yAxisRangeMin,
        yAxisRangeMax = yAxisRangeMax,
        xAxisLabelFontSize = xAxisLabelFontSize,
        xAxisLabelRotation = xAxisLabelRotation,
        xAxisRangeType = xAxisRangeType,
        xAxisRangeMin = xAxisRangeMin,
        xAxisRangeMax = xAxisRangeMax,
        xTicks = xTicks,
        yTicks = yTicks)

    analysis <- qqplotClass$new(
        options = options,
        data = data)

    analysis$run()

    analysis$results
}

