
# This file is automatically generated, you probably don't want to edit this

scatterplotOptions <- if (requireNamespace("jmvcore", quietly=TRUE)) R6::R6Class(
    "scatterplotOptions",
    inherit = jmvcore::Options,
    public = list(
        initialize = function(
            xaxis = NULL,
            yaxis = NULL,
            group = NULL,
            labelVar = NULL,
            ptSize = NULL,
            facet = NULL,
            keepNA = FALSE,
            overlap = FALSE,
            plotBorder = FALSE,
            hline = FALSE,
            yinter = 0,
            vline = FALSE,
            xinter = 0,
            facetBy = "column",
            facetNumber = 1,
            pointSize = 3,
            lineSize = 1,
            regLine = FALSE,
            lineMethod = "lm",
            lineSE = TRUE,
            singleColor = "#999999",
            colorPalette = "jmv",
            titleText = NULL,
            titleFontFace = "bold",
            titleFontSize = "14",
            titleAlign = "0.5",
            subtitleText = NULL,
            subtitleFontFace = "plain",
            subtitleFontSize = "12",
            subtitleAlign = "0.5",
            captionText = NULL,
            captionFontFace = "italic",
            captionFontSize = "10",
            captionAlign = "1",
            legendText = NULL,
            legendFontSize = "14",
            legendPosition = "right",
            xAxisText = NULL,
            xAxisFontSize = "16",
            xAxisPosition = "0.5",
            yAxisText = NULL,
            yAxisFontSize = "16",
            yAxisPosition = "0.5",
            yAxisLabelFontSize = 12,
            yAxisLabelRotation = 0,
            yAxisRangeType = "auto",
            yAxisRangeMin = 0,
            yAxisRangeMax = 10,
            xAxisLabelFontSize = 12,
            xAxisLabelRotation = 0,
            xAxisRangeType = "auto",
            xAxisRangeMin = 0,
            xAxisRangeMax = 10, ...) {

            super$initialize(
                package="vijPlots",
                name="scatterplot",
                requiresData=TRUE,
                ...)

            private$..xaxis <- jmvcore::OptionVariable$new(
                "xaxis",
                xaxis,
                suggested=list(
                    "continuous"),
                permitted=list(
                    "numeric"))
            private$..yaxis <- jmvcore::OptionVariable$new(
                "yaxis",
                yaxis,
                suggested=list(
                    "continuous"),
                permitted=list(
                    "numeric"))
            private$..group <- jmvcore::OptionVariable$new(
                "group",
                group,
                suggested=list(
                    "nominal",
                    "ordinal"),
                permitted=list(
                    "factor"))
            private$..labelVar <- jmvcore::OptionVariable$new(
                "labelVar",
                labelVar,
                suggested=list(
                    "nominal",
                    "id"),
                permitted=list(
                    "id",
                    "factor"))
            private$..ptSize <- jmvcore::OptionVariable$new(
                "ptSize",
                ptSize,
                suggested=list(
                    "continuous"),
                permitted=list(
                    "numeric"))
            private$..facet <- jmvcore::OptionVariable$new(
                "facet",
                facet,
                suggested=list(
                    "nominal",
                    "ordinal"),
                permitted=list(
                    "factor"))
            private$..keepNA <- jmvcore::OptionBool$new(
                "keepNA",
                keepNA,
                default=FALSE)
            private$..overlap <- jmvcore::OptionBool$new(
                "overlap",
                overlap,
                default=FALSE)
            private$..plotBorder <- jmvcore::OptionBool$new(
                "plotBorder",
                plotBorder,
                default=FALSE)
            private$..hline <- jmvcore::OptionBool$new(
                "hline",
                hline,
                default=FALSE)
            private$..yinter <- jmvcore::OptionNumber$new(
                "yinter",
                yinter,
                default=0)
            private$..vline <- jmvcore::OptionBool$new(
                "vline",
                vline,
                default=FALSE)
            private$..xinter <- jmvcore::OptionNumber$new(
                "xinter",
                xinter,
                default=0)
            private$..facetBy <- jmvcore::OptionList$new(
                "facetBy",
                facetBy,
                options=list(
                    "row",
                    "column"),
                default="column")
            private$..facetNumber <- jmvcore::OptionNumber$new(
                "facetNumber",
                facetNumber,
                min=1,
                max=10,
                default=1)
            private$..pointSize <- jmvcore::OptionNumber$new(
                "pointSize",
                pointSize,
                default=3,
                min=0.1,
                max=10)
            private$..lineSize <- jmvcore::OptionNumber$new(
                "lineSize",
                lineSize,
                default=1,
                min=0.1,
                max=5)
            private$..regLine <- jmvcore::OptionBool$new(
                "regLine",
                regLine,
                default=FALSE)
            private$..lineMethod <- jmvcore::OptionList$new(
                "lineMethod",
                lineMethod,
                options=list(
                    "lm",
                    "loess"),
                default="lm")
            private$..lineSE <- jmvcore::OptionBool$new(
                "lineSE",
                lineSE,
                default=TRUE)
            private$..singleColor <- jmvcore::OptionList$new(
                "singleColor",
                singleColor,
                options=list(
                    "none",
                    "white",
                    "black",
                    "#999999",
                    "#A6C4F1",
                    "#C5C5C5",
                    "#F0CD8C",
                    "#88C38B",
                    "#E18A8A",
                    "#E41A1C",
                    "#377EB8",
                    "#4DAF4A",
                    "#984EA3",
                    "#FF7F00",
                    "#FFFF33",
                    "#A65628",
                    "#F781BF"),
                default="#999999")
            private$..colorPalette <- jmvcore::OptionList$new(
                "colorPalette",
                colorPalette,
                options=list(
                    "jmv",
                    "Set1",
                    "Set2",
                    "Set3",
                    "Pastel1",
                    "Pastel2",
                    "Accent",
                    "Paired",
                    "Dark2",
                    "Spectral",
                    "RdYlGn",
                    "RdYlBu",
                    "RdGy",
                    "RdBu",
                    "PuOr",
                    "PRGn",
                    "PiYG",
                    "BrBG",
                    "Blues",
                    "Greens",
                    "Greys",
                    "Oranges",
                    "Purples",
                    "Reds",
                    "BuGn",
                    "BuPu",
                    "GnBu",
                    "OrRd",
                    "PuBu",
                    "PuBuGn",
                    "PuRd",
                    "RdPu",
                    "YlGn",
                    "YlGnBu",
                    "YlOrBr",
                    "YlOrRd",
                    "viridis::viridis",
                    "viridis::magma",
                    "viridis::inferno",
                    "viridis::plasma",
                    "viridis::turbo",
                    "dichromat::Categorical.12",
                    "tidy::friendly",
                    "tidy::seaside",
                    "tidy::apple",
                    "tidy::ibm",
                    "tidy::candy",
                    "tidy::alger",
                    "tidy::rainbow",
                    "tidy::metro",
                    "custom::lemovice"),
                default="jmv")
            private$..titleText <- jmvcore::OptionString$new(
                "titleText",
                titleText)
            private$..titleFontFace <- jmvcore::OptionList$new(
                "titleFontFace",
                titleFontFace,
                options=list(
                    "plain",
                    "bold",
                    "italic",
                    "bold.italic"),
                default="bold")
            private$..titleFontSize <- jmvcore::OptionList$new(
                "titleFontSize",
                titleFontSize,
                options=list(
                    "12",
                    "14",
                    "16",
                    "18",
                    "20",
                    "22",
                    "24"),
                default="14")
            private$..titleAlign <- jmvcore::OptionList$new(
                "titleAlign",
                titleAlign,
                options=list(
                    "0",
                    "0.5",
                    "1"),
                default="0.5")
            private$..subtitleText <- jmvcore::OptionString$new(
                "subtitleText",
                subtitleText)
            private$..subtitleFontFace <- jmvcore::OptionList$new(
                "subtitleFontFace",
                subtitleFontFace,
                options=list(
                    "plain",
                    "bold",
                    "italic",
                    "bold.italic"),
                default="plain")
            private$..subtitleFontSize <- jmvcore::OptionList$new(
                "subtitleFontSize",
                subtitleFontSize,
                options=list(
                    "10",
                    "12",
                    "14",
                    "16",
                    "18",
                    "20",
                    "22"),
                default="12")
            private$..subtitleAlign <- jmvcore::OptionList$new(
                "subtitleAlign",
                subtitleAlign,
                options=list(
                    "0",
                    "0.5",
                    "1"),
                default="0.5")
            private$..captionText <- jmvcore::OptionString$new(
                "captionText",
                captionText)
            private$..captionFontFace <- jmvcore::OptionList$new(
                "captionFontFace",
                captionFontFace,
                options=list(
                    "plain",
                    "bold",
                    "italic",
                    "bold.italic"),
                default="italic")
            private$..captionFontSize <- jmvcore::OptionList$new(
                "captionFontSize",
                captionFontSize,
                options=list(
                    "8",
                    "10",
                    "12",
                    "14",
                    "16",
                    "18",
                    "20"),
                default="10")
            private$..captionAlign <- jmvcore::OptionList$new(
                "captionAlign",
                captionAlign,
                options=list(
                    "0",
                    "0.5",
                    "1"),
                default="1")
            private$..legendText <- jmvcore::OptionString$new(
                "legendText",
                legendText)
            private$..legendFontSize <- jmvcore::OptionList$new(
                "legendFontSize",
                legendFontSize,
                options=list(
                    "10",
                    "12",
                    "14",
                    "16",
                    "18",
                    "20"),
                default="14")
            private$..legendPosition <- jmvcore::OptionList$new(
                "legendPosition",
                legendPosition,
                options=list(
                    "right",
                    "bottom",
                    "left",
                    "top"),
                default="right")
            private$..xAxisText <- jmvcore::OptionString$new(
                "xAxisText",
                xAxisText)
            private$..xAxisFontSize <- jmvcore::OptionList$new(
                "xAxisFontSize",
                xAxisFontSize,
                options=list(
                    "10",
                    "12",
                    "14",
                    "16",
                    "18",
                    "20"),
                default="16")
            private$..xAxisPosition <- jmvcore::OptionList$new(
                "xAxisPosition",
                xAxisPosition,
                options=list(
                    "0",
                    "0.5",
                    "1"),
                default="0.5")
            private$..yAxisText <- jmvcore::OptionString$new(
                "yAxisText",
                yAxisText)
            private$..yAxisFontSize <- jmvcore::OptionList$new(
                "yAxisFontSize",
                yAxisFontSize,
                options=list(
                    "10",
                    "12",
                    "14",
                    "16",
                    "18",
                    "20"),
                default="16")
            private$..yAxisPosition <- jmvcore::OptionList$new(
                "yAxisPosition",
                yAxisPosition,
                options=list(
                    "1",
                    "0.5",
                    "0"),
                default="0.5")
            private$..yAxisLabelFontSize <- jmvcore::OptionNumber$new(
                "yAxisLabelFontSize",
                yAxisLabelFontSize,
                default=12)
            private$..yAxisLabelRotation <- jmvcore::OptionNumber$new(
                "yAxisLabelRotation",
                yAxisLabelRotation,
                default=0,
                min=0,
                max=360)
            private$..yAxisRangeType <- jmvcore::OptionList$new(
                "yAxisRangeType",
                yAxisRangeType,
                options=list(
                    "auto",
                    "manual"),
                default="auto")
            private$..yAxisRangeMin <- jmvcore::OptionNumber$new(
                "yAxisRangeMin",
                yAxisRangeMin,
                default=0)
            private$..yAxisRangeMax <- jmvcore::OptionNumber$new(
                "yAxisRangeMax",
                yAxisRangeMax,
                default=10)
            private$..xAxisLabelFontSize <- jmvcore::OptionNumber$new(
                "xAxisLabelFontSize",
                xAxisLabelFontSize,
                default=12)
            private$..xAxisLabelRotation <- jmvcore::OptionNumber$new(
                "xAxisLabelRotation",
                xAxisLabelRotation,
                default=0,
                min=0,
                max=360)
            private$..xAxisRangeType <- jmvcore::OptionList$new(
                "xAxisRangeType",
                xAxisRangeType,
                options=list(
                    "auto",
                    "manual"),
                default="auto")
            private$..xAxisRangeMin <- jmvcore::OptionNumber$new(
                "xAxisRangeMin",
                xAxisRangeMin,
                default=0)
            private$..xAxisRangeMax <- jmvcore::OptionNumber$new(
                "xAxisRangeMax",
                xAxisRangeMax,
                default=10)

            self$.addOption(private$..xaxis)
            self$.addOption(private$..yaxis)
            self$.addOption(private$..group)
            self$.addOption(private$..labelVar)
            self$.addOption(private$..ptSize)
            self$.addOption(private$..facet)
            self$.addOption(private$..keepNA)
            self$.addOption(private$..overlap)
            self$.addOption(private$..plotBorder)
            self$.addOption(private$..hline)
            self$.addOption(private$..yinter)
            self$.addOption(private$..vline)
            self$.addOption(private$..xinter)
            self$.addOption(private$..facetBy)
            self$.addOption(private$..facetNumber)
            self$.addOption(private$..pointSize)
            self$.addOption(private$..lineSize)
            self$.addOption(private$..regLine)
            self$.addOption(private$..lineMethod)
            self$.addOption(private$..lineSE)
            self$.addOption(private$..singleColor)
            self$.addOption(private$..colorPalette)
            self$.addOption(private$..titleText)
            self$.addOption(private$..titleFontFace)
            self$.addOption(private$..titleFontSize)
            self$.addOption(private$..titleAlign)
            self$.addOption(private$..subtitleText)
            self$.addOption(private$..subtitleFontFace)
            self$.addOption(private$..subtitleFontSize)
            self$.addOption(private$..subtitleAlign)
            self$.addOption(private$..captionText)
            self$.addOption(private$..captionFontFace)
            self$.addOption(private$..captionFontSize)
            self$.addOption(private$..captionAlign)
            self$.addOption(private$..legendText)
            self$.addOption(private$..legendFontSize)
            self$.addOption(private$..legendPosition)
            self$.addOption(private$..xAxisText)
            self$.addOption(private$..xAxisFontSize)
            self$.addOption(private$..xAxisPosition)
            self$.addOption(private$..yAxisText)
            self$.addOption(private$..yAxisFontSize)
            self$.addOption(private$..yAxisPosition)
            self$.addOption(private$..yAxisLabelFontSize)
            self$.addOption(private$..yAxisLabelRotation)
            self$.addOption(private$..yAxisRangeType)
            self$.addOption(private$..yAxisRangeMin)
            self$.addOption(private$..yAxisRangeMax)
            self$.addOption(private$..xAxisLabelFontSize)
            self$.addOption(private$..xAxisLabelRotation)
            self$.addOption(private$..xAxisRangeType)
            self$.addOption(private$..xAxisRangeMin)
            self$.addOption(private$..xAxisRangeMax)
        }),
    active = list(
        xaxis = function() private$..xaxis$value,
        yaxis = function() private$..yaxis$value,
        group = function() private$..group$value,
        labelVar = function() private$..labelVar$value,
        ptSize = function() private$..ptSize$value,
        facet = function() private$..facet$value,
        keepNA = function() private$..keepNA$value,
        overlap = function() private$..overlap$value,
        plotBorder = function() private$..plotBorder$value,
        hline = function() private$..hline$value,
        yinter = function() private$..yinter$value,
        vline = function() private$..vline$value,
        xinter = function() private$..xinter$value,
        facetBy = function() private$..facetBy$value,
        facetNumber = function() private$..facetNumber$value,
        pointSize = function() private$..pointSize$value,
        lineSize = function() private$..lineSize$value,
        regLine = function() private$..regLine$value,
        lineMethod = function() private$..lineMethod$value,
        lineSE = function() private$..lineSE$value,
        singleColor = function() private$..singleColor$value,
        colorPalette = function() private$..colorPalette$value,
        titleText = function() private$..titleText$value,
        titleFontFace = function() private$..titleFontFace$value,
        titleFontSize = function() private$..titleFontSize$value,
        titleAlign = function() private$..titleAlign$value,
        subtitleText = function() private$..subtitleText$value,
        subtitleFontFace = function() private$..subtitleFontFace$value,
        subtitleFontSize = function() private$..subtitleFontSize$value,
        subtitleAlign = function() private$..subtitleAlign$value,
        captionText = function() private$..captionText$value,
        captionFontFace = function() private$..captionFontFace$value,
        captionFontSize = function() private$..captionFontSize$value,
        captionAlign = function() private$..captionAlign$value,
        legendText = function() private$..legendText$value,
        legendFontSize = function() private$..legendFontSize$value,
        legendPosition = function() private$..legendPosition$value,
        xAxisText = function() private$..xAxisText$value,
        xAxisFontSize = function() private$..xAxisFontSize$value,
        xAxisPosition = function() private$..xAxisPosition$value,
        yAxisText = function() private$..yAxisText$value,
        yAxisFontSize = function() private$..yAxisFontSize$value,
        yAxisPosition = function() private$..yAxisPosition$value,
        yAxisLabelFontSize = function() private$..yAxisLabelFontSize$value,
        yAxisLabelRotation = function() private$..yAxisLabelRotation$value,
        yAxisRangeType = function() private$..yAxisRangeType$value,
        yAxisRangeMin = function() private$..yAxisRangeMin$value,
        yAxisRangeMax = function() private$..yAxisRangeMax$value,
        xAxisLabelFontSize = function() private$..xAxisLabelFontSize$value,
        xAxisLabelRotation = function() private$..xAxisLabelRotation$value,
        xAxisRangeType = function() private$..xAxisRangeType$value,
        xAxisRangeMin = function() private$..xAxisRangeMin$value,
        xAxisRangeMax = function() private$..xAxisRangeMax$value),
    private = list(
        ..xaxis = NA,
        ..yaxis = NA,
        ..group = NA,
        ..labelVar = NA,
        ..ptSize = NA,
        ..facet = NA,
        ..keepNA = NA,
        ..overlap = NA,
        ..plotBorder = NA,
        ..hline = NA,
        ..yinter = NA,
        ..vline = NA,
        ..xinter = NA,
        ..facetBy = NA,
        ..facetNumber = NA,
        ..pointSize = NA,
        ..lineSize = NA,
        ..regLine = NA,
        ..lineMethod = NA,
        ..lineSE = NA,
        ..singleColor = NA,
        ..colorPalette = NA,
        ..titleText = NA,
        ..titleFontFace = NA,
        ..titleFontSize = NA,
        ..titleAlign = NA,
        ..subtitleText = NA,
        ..subtitleFontFace = NA,
        ..subtitleFontSize = NA,
        ..subtitleAlign = NA,
        ..captionText = NA,
        ..captionFontFace = NA,
        ..captionFontSize = NA,
        ..captionAlign = NA,
        ..legendText = NA,
        ..legendFontSize = NA,
        ..legendPosition = NA,
        ..xAxisText = NA,
        ..xAxisFontSize = NA,
        ..xAxisPosition = NA,
        ..yAxisText = NA,
        ..yAxisFontSize = NA,
        ..yAxisPosition = NA,
        ..yAxisLabelFontSize = NA,
        ..yAxisLabelRotation = NA,
        ..yAxisRangeType = NA,
        ..yAxisRangeMin = NA,
        ..yAxisRangeMax = NA,
        ..xAxisLabelFontSize = NA,
        ..xAxisLabelRotation = NA,
        ..xAxisRangeType = NA,
        ..xAxisRangeMin = NA,
        ..xAxisRangeMax = NA)
)

scatterplotResults <- if (requireNamespace("jmvcore", quietly=TRUE)) R6::R6Class(
    "scatterplotResults",
    inherit = jmvcore::Group,
    active = list(
        plot = function() private$.items[["plot"]]),
    private = list(),
    public=list(
        initialize=function(options) {
            super$initialize(
                options=options,
                name="",
                title="Scatter Plot")
            self$add(jmvcore::Image$new(
                options=options,
                name="plot",
                title="",
                width=600,
                height=600,
                renderFun=".plot"))}))

scatterplotBase <- if (requireNamespace("jmvcore", quietly=TRUE)) R6::R6Class(
    "scatterplotBase",
    inherit = jmvcore::Analysis,
    public = list(
        initialize = function(options, data=NULL, datasetId="", analysisId="", revision=0) {
            super$initialize(
                package = "vijPlots",
                name = "scatterplot",
                version = c(1,0,0),
                options = options,
                results = scatterplotResults$new(options=options),
                data = data,
                datasetId = datasetId,
                analysisId = analysisId,
                revision = revision,
                pause = NULL,
                completeWhenFilled = FALSE,
                requiresMissings = FALSE,
                weightsSupport = 'auto')
        }))

#' Scatter Plot
#'
#' 
#' @param data .
#' @param xaxis .
#' @param yaxis .
#' @param group .
#' @param labelVar .
#' @param ptSize .
#' @param facet .
#' @param keepNA .
#' @param overlap .
#' @param plotBorder .
#' @param hline .
#' @param yinter .
#' @param vline .
#' @param xinter .
#' @param facetBy .
#' @param facetNumber .
#' @param pointSize .
#' @param lineSize .
#' @param regLine .
#' @param lineMethod .
#' @param lineSE .
#' @param singleColor .
#' @param colorPalette .
#' @param titleText .
#' @param titleFontFace .
#' @param titleFontSize .
#' @param titleAlign .
#' @param subtitleText .
#' @param subtitleFontFace .
#' @param subtitleFontSize .
#' @param subtitleAlign .
#' @param captionText .
#' @param captionFontFace .
#' @param captionFontSize .
#' @param captionAlign .
#' @param legendText .
#' @param legendFontSize .
#' @param legendPosition .
#' @param xAxisText .
#' @param xAxisFontSize .
#' @param xAxisPosition .
#' @param yAxisText .
#' @param yAxisFontSize .
#' @param yAxisPosition .
#' @param yAxisLabelFontSize .
#' @param yAxisLabelRotation .
#' @param yAxisRangeType .
#' @param yAxisRangeMin .
#' @param yAxisRangeMax .
#' @param xAxisLabelFontSize .
#' @param xAxisLabelRotation .
#' @param xAxisRangeType .
#' @param xAxisRangeMin .
#' @param xAxisRangeMax .
#' @return A results object containing:
#' \tabular{llllll}{
#'   \code{results$plot} \tab \tab \tab \tab \tab an image \cr
#' }
#'
#' @export
scatterplot <- function(
    data,
    xaxis,
    yaxis,
    group,
    labelVar,
    ptSize,
    facet,
    keepNA = FALSE,
    overlap = FALSE,
    plotBorder = FALSE,
    hline = FALSE,
    yinter = 0,
    vline = FALSE,
    xinter = 0,
    facetBy = "column",
    facetNumber = 1,
    pointSize = 3,
    lineSize = 1,
    regLine = FALSE,
    lineMethod = "lm",
    lineSE = TRUE,
    singleColor = "#999999",
    colorPalette = "jmv",
    titleText,
    titleFontFace = "bold",
    titleFontSize = "14",
    titleAlign = "0.5",
    subtitleText,
    subtitleFontFace = "plain",
    subtitleFontSize = "12",
    subtitleAlign = "0.5",
    captionText,
    captionFontFace = "italic",
    captionFontSize = "10",
    captionAlign = "1",
    legendText,
    legendFontSize = "14",
    legendPosition = "right",
    xAxisText,
    xAxisFontSize = "16",
    xAxisPosition = "0.5",
    yAxisText,
    yAxisFontSize = "16",
    yAxisPosition = "0.5",
    yAxisLabelFontSize = 12,
    yAxisLabelRotation = 0,
    yAxisRangeType = "auto",
    yAxisRangeMin = 0,
    yAxisRangeMax = 10,
    xAxisLabelFontSize = 12,
    xAxisLabelRotation = 0,
    xAxisRangeType = "auto",
    xAxisRangeMin = 0,
    xAxisRangeMax = 10) {

    if ( ! requireNamespace("jmvcore", quietly=TRUE))
        stop("scatterplot requires jmvcore to be installed (restart may be required)")

    if ( ! missing(xaxis)) xaxis <- jmvcore::resolveQuo(jmvcore::enquo(xaxis))
    if ( ! missing(yaxis)) yaxis <- jmvcore::resolveQuo(jmvcore::enquo(yaxis))
    if ( ! missing(group)) group <- jmvcore::resolveQuo(jmvcore::enquo(group))
    if ( ! missing(labelVar)) labelVar <- jmvcore::resolveQuo(jmvcore::enquo(labelVar))
    if ( ! missing(ptSize)) ptSize <- jmvcore::resolveQuo(jmvcore::enquo(ptSize))
    if ( ! missing(facet)) facet <- jmvcore::resolveQuo(jmvcore::enquo(facet))
    if (missing(data))
        data <- jmvcore::marshalData(
            parent.frame(),
            `if`( ! missing(xaxis), xaxis, NULL),
            `if`( ! missing(yaxis), yaxis, NULL),
            `if`( ! missing(group), group, NULL),
            `if`( ! missing(labelVar), labelVar, NULL),
            `if`( ! missing(ptSize), ptSize, NULL),
            `if`( ! missing(facet), facet, NULL))

    for (v in group) if (v %in% names(data)) data[[v]] <- as.factor(data[[v]])
    for (v in facet) if (v %in% names(data)) data[[v]] <- as.factor(data[[v]])

    options <- scatterplotOptions$new(
        xaxis = xaxis,
        yaxis = yaxis,
        group = group,
        labelVar = labelVar,
        ptSize = ptSize,
        facet = facet,
        keepNA = keepNA,
        overlap = overlap,
        plotBorder = plotBorder,
        hline = hline,
        yinter = yinter,
        vline = vline,
        xinter = xinter,
        facetBy = facetBy,
        facetNumber = facetNumber,
        pointSize = pointSize,
        lineSize = lineSize,
        regLine = regLine,
        lineMethod = lineMethod,
        lineSE = lineSE,
        singleColor = singleColor,
        colorPalette = colorPalette,
        titleText = titleText,
        titleFontFace = titleFontFace,
        titleFontSize = titleFontSize,
        titleAlign = titleAlign,
        subtitleText = subtitleText,
        subtitleFontFace = subtitleFontFace,
        subtitleFontSize = subtitleFontSize,
        subtitleAlign = subtitleAlign,
        captionText = captionText,
        captionFontFace = captionFontFace,
        captionFontSize = captionFontSize,
        captionAlign = captionAlign,
        legendText = legendText,
        legendFontSize = legendFontSize,
        legendPosition = legendPosition,
        xAxisText = xAxisText,
        xAxisFontSize = xAxisFontSize,
        xAxisPosition = xAxisPosition,
        yAxisText = yAxisText,
        yAxisFontSize = yAxisFontSize,
        yAxisPosition = yAxisPosition,
        yAxisLabelFontSize = yAxisLabelFontSize,
        yAxisLabelRotation = yAxisLabelRotation,
        yAxisRangeType = yAxisRangeType,
        yAxisRangeMin = yAxisRangeMin,
        yAxisRangeMax = yAxisRangeMax,
        xAxisLabelFontSize = xAxisLabelFontSize,
        xAxisLabelRotation = xAxisLabelRotation,
        xAxisRangeType = xAxisRangeType,
        xAxisRangeMin = xAxisRangeMin,
        xAxisRangeMax = xAxisRangeMax)

    analysis <- scatterplotClass$new(
        options = options,
        data = data)

    analysis$run()

    analysis$results
}

